import { DBS, type DbId } from "@/lib/sqlDbs";

/** Converte o script SQLite dos bancos de exemplo para PostgreSQL (tipos reais: IDENTITY, NUMERIC, DATE). */
export function pgScript(id: DbId): string {
  return DBS[id].script
    .replace(/INTEGER PRIMARY KEY/g, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bREAL\b/g, "NUMERIC(12,2)")
    .replace(/\b(criado_em|data|nascimento|admissao) TEXT/g, "$1 DATE");
}
