import { S, cat } from "@/content/helpers";

/* Lote 4 (CSS lote 2): recursos modernos, funções, background, tipografia, mídia/impressão e formulários.
   Recursos novos têm suporte em evolução nos navegadores: sempre cheque o caniuse.com antes de usar em produção. */

const SUP = "Suporte em evolução entre navegadores: confira em caniuse.com antes de depender disso em produção.";

export const cssD = [
  cat("css-avancado", "CSS Moderno & Avançado", "Recursos recentes que substituem JavaScript e pré-processadores: propriedades tipadas, âncoras, popover, escopo e cores relativas.", [
    S({ s: "property", t: "@property (variáveis tipadas)", d: "Registra uma variável CSS com tipo, valor inicial e herança, permitindo animá-la.", x: "@property --angulo { syntax: '<angle>'; inherits: false; initial-value: 0deg; }",
      n: "Variáveis normais são texto e não animam. Com @property o navegador sabe o tipo (<angle>, <color>, <length>, <percentage>) e consegue interpolar: dá para animar gradientes, ângulos e cores, algo impossível antes.",
      ex: `@property --giro { syntax: '<angle>'; inherits: false; initial-value: 0deg; }\n\n.borda-animada {\n  border: 3px solid transparent;\n  background: linear-gradient(#111 0 0) padding-box,\n              conic-gradient(from var(--giro), #2f6fed, #e4572e, #2f6fed) border-box;\n  animation: gira 3s linear infinite;\n}\n@keyframes gira { to { --giro: 360deg; } }`,
      r: "css/seletores-modernos/has|css/animacoes/animation", k: "animar gradiente|animar variável css|borda gradiente animada|variável tipada|registrar propriedade|houdini" }),
    S({ s: "anchor-positioning", t: "Anchor positioning", d: "Posiciona um elemento (tooltip, menu) ancorado em outro, sem JavaScript.", x: ".botao { anchor-name: --btn; }\n.menu { position: absolute; position-anchor: --btn; top: anchor(bottom); left: anchor(left); }",
      n: "Resolve o clássico problema de posicionar tooltips e dropdowns relativos ao gatilho (antes exigia JS ou bibliotecas como Popper). Também permite fallback automático quando o elemento sai da tela (position-try-fallbacks). " + SUP,
      ex: `.gatilho { anchor-name: --gatilho; }\n\n.dica {\n  position: absolute;\n  position-anchor: --gatilho;\n  top: calc(anchor(bottom) + 8px);\n  justify-self: anchor-center;\n  position-try-fallbacks: flip-block; /* vira para cima se faltar espaço */\n}`,
      k: "tooltip ancorado|menu ancorado no botão|posicionar relativo a outro elemento|popper|dropdown sem javascript|anchor" }),
    S({ s: "popover", t: "Popover API + :popover-open", d: "Janelas flutuantes nativas (menus, dicas, notificações) abertas por atributo HTML.", x: "<button popovertarget=\"menu\">Abrir</button>\n<div id=\"menu\" popover>...</div>",
      n: "O atributo popover faz o navegador cuidar de abrir/fechar, ESC, clique fora e camada superior (top layer), sem z-index. Estilize o estado aberto com :popover-open e o fundo com ::backdrop. Combine com @starting-style para animar.",
      ex: `<button popovertarget="info">Detalhes</button>\n<div id="info" popover>Conteúdo do popover</div>\n\n/* CSS */\n[popover] { border: 1px solid #ddd; border-radius: 12px; padding: 16px; }\n[popover]:popover-open { animation: surge .2s ease-out; }\n[popover]::backdrop { background: rgb(0 0 0 / .3); }\n@keyframes surge { from { opacity: 0; scale: .95; } }`,
      r: "css/transicoes/starting-style", k: "janela flutuante sem javascript|menu popover|abrir e fechar com atributo|top layer|dica clicável|notificação popover" }),
    S({ s: "scope", t: "@scope", d: "Limita as regras CSS a uma parte da página, sem classes gigantes nem Shadow DOM.", x: "@scope (.card) to (.card-conteudo-aninhado) { img { border-radius: 8px; } }",
      n: "Estilos dentro do @scope só valem dentro daquela raiz (e, opcionalmente, param em um limite 'to'). Evita conflito entre componentes e reduz nomes de classe longos. " + SUP,
      ex: `@scope (.card) {\n  :scope { padding: 16px; border-radius: 12px; }\n  h2 { font-size: 1.1rem; }\n  a:hover { text-decoration: underline; }\n}`, r: "css/seletores-modernos/layer", k: "escopo de css|css só dentro do componente|evitar conflito de classes|isolar estilos|scope" }),
    S({ s: "relative-color", t: "Cores relativas: oklch(from ...)", d: "Deriva uma cor a partir de outra alterando só um canal (luz, croma, matiz, transparência).", x: "background: oklch(from var(--marca) calc(l + .1) c h);",
      n: "Cria claros, escuros e transparências a partir de UMA cor da marca, sem precisar calcular à mão ou usar Sass. Funciona com rgb(), hsl(), oklch() e outros. " + SUP,
      ex: `:root { --marca: #2f6fed; }\n.btn { background: var(--marca); }\n.btn:hover { background: oklch(from var(--marca) calc(l - .08) c h); }   /* mais escura */\n.fundo-suave { background: oklch(from var(--marca) l c h / .12); }     /* 12% de opacidade */`,
      r: "css/unidades-funcoes/color-mix|css/unidades-funcoes/oklch", k: "variação de cor|clarear cor sem sass|escurecer cor|cor com transparência|derivar cor|paleta a partir de uma cor" }),
    S({ s: "interpolate-size", t: "interpolate-size / calc-size()", d: "Permite animar de/para height: auto (acordeões e menus que abrem suavemente).", x: ":root { interpolate-size: allow-keywords; }\n.painel { height: 0; transition: height .3s; }\n.painel.aberto { height: auto; }",
      n: "Animar height de 0 até auto sempre foi o problema clássico (o navegador não sabia o valor final). Com interpolate-size habilitado, a transição funciona sem JavaScript medindo altura. " + SUP,
      k: "animar height auto|acordeão suave|abrir e fechar com animação de altura|transição para auto|expandir suavemente" }),
    S({ s: "linear-easing", t: "linear() (easing com mola/quique)", d: "Curva de animação feita de pontos: simula mola, quique e elástico de verdade.", x: "transition-timing-function: linear(0, .6 20%, 1.1 45%, .95 70%, 1);",
      n: "cubic-bezier só faz uma curva suave; linear() aceita vários pontos e permite 'passar do ponto e voltar' várias vezes (mola). Use geradores visuais para criar a lista de pontos. " + SUP,
      ex: `.bola { transition: transform .9s linear(0, .25 8%, .88 20%, 1.12 32%, .96 46%, 1.02 62%, 1); }\n.bola:hover { transform: translateY(-80px); }`,
      r: "css/transicoes/cubic-bezier", k: "efeito mola|efeito elástico|bounce real|animação com quique|spring|easing personalizado" }),
    S({ s: "offset-path", t: "offset-path (movimento em trajeto)", d: "Faz um elemento percorrer uma curva ou caminho SVG.", x: "offset-path: path('M0 0 C 100 0, 100 100, 200 100');\nanimation: anda 3s linear infinite;\n@keyframes anda { to { offset-distance: 100%; } }",
      n: "offset-path define o trajeto e offset-distance (0% a 100%) a posição nele. offset-rotate: auto vira o elemento acompanhando a curva. Ótimo para setas seguindo rotas, ícones em órbita e animações de entrada.",
      ex: `.satelite {\n  offset-path: circle(80px at 50% 50%);\n  offset-rotate: auto;\n  animation: orbita 6s linear infinite;\n}\n@keyframes orbita { to { offset-distance: 100%; } }`, k: "mover em curva|animar em trajeto|elemento girando em órbita|seguir caminho svg|motion path" }),
    S({ s: "shape-outside", t: "shape-outside (texto contornando formas)", d: "Faz o texto contornar uma forma (círculo, polígono, imagem) em vez de um retângulo.", x: "float: left;\nshape-outside: circle(50%);",
      n: "Só funciona em elementos com float. Combine com clip-path igual à forma para o visual casar com o contorno do texto. Muito usado em revistas e artigos.",
      ex: `.foto {\n  float: left;\n  width: 160px; height: 160px;\n  margin: 0 20px 10px 0;\n  shape-outside: circle(50%);\n  clip-path: circle(50%);\n}`, r: "css/posicionamento/float|css/efeitos-avancados/clip-path", k: "texto contornando imagem redonda|texto em volta de círculo|layout de revista|float com forma" }),
    S({ s: "contain", t: "contain & content-visibility", d: "Avisa o navegador que um bloco é independente, acelerando renderização de páginas longas.", x: "contain: layout paint;\ncontent-visibility: auto;\ncontain-intrinsic-size: auto 500px;",
      n: "content-visibility: auto faz o navegador pular a renderização do que está fora da tela, melhora muito o tempo de carregamento de listas e feeds longos. contain-intrinsic-size reserva uma altura estimada para a barra de rolagem não 'pular'.",
      ex: `.secao-longa {\n  content-visibility: auto;\n  contain-intrinsic-size: auto 600px; /* altura estimada */\n}`, k: "performance css|página longa lenta|renderizar só o que aparece|otimizar rolagem|feed grande" }),
    S({ s: "container-units", t: "Unidades de container (cqw, cqi)", d: "Medidas relativas ao tamanho do container, não da janela.", x: "font-size: clamp(1rem, 4cqi, 2rem);",
      n: "Dentro de um elemento com container-type, 1cqw = 1% da largura do container (cqi = eixo inline, cqb = bloco). Torna o componente verdadeiramente independente do tamanho da tela.",
      ex: `.card-wrap { container-type: inline-size; }\n.card h2 { font-size: clamp(1.1rem, 5cqi, 2rem); }  /* cresce com o CARD, não com a tela */`,
      r: "css/seletores-modernos/container-queries", k: "fonte relativa ao container|cqw|tamanho relativo ao pai|texto que escala com o card|unidade de container" }),
    S({ s: "funcoes-matematicas", t: "round(), mod(), rem(), sin(), cos()", d: "Funções matemáticas nativas: arredondar para múltiplos, resto de divisão e trigonometria.", x: "width: round(down, 100%, 50px);\nrotate: calc(sin(30deg) * 90deg);",
      n: "round() faz 'snap' a múltiplos (grade de 8px, larguras em passos), mod() e rem() dão o resto, e sin()/cos() permitem layouts circulares (itens em volta de um círculo) só com CSS. Suporte já amplo nos navegadores atuais.",
      ex: `/* itens em círculo: i vai de 0 a n-1 */\n.item {\n  --a: calc(var(--i) * 360deg / var(--n));\n  translate: calc(cos(var(--a)) * 90px) calc(sin(var(--a)) * 90px);\n}`, r: "css/unidades-funcoes/calc", k: "arredondar no css|itens em círculo|trigonometria css|resto da divisão|snap em grade|seno cosseno" }),
    S({ s: "logical-properties", t: "Propriedades lógicas (inline/block)", d: "margin-inline, padding-block, inset-inline...: espaçamento que respeita o idioma e a direção do texto.", x: "margin-inline: auto;\npadding-block: 1rem;\nborder-inline-start: 4px solid;",
      n: "'inline' é o eixo do texto (horizontal em português) e 'block' o eixo de empilhamento (vertical). Em idiomas RTL (árabe, hebraico) ou texto vertical, o layout se adapta sozinho, sem escrever tudo de novo. margin-inline: auto é o jeito moderno de centralizar um bloco.",
      ex: `.caixa {\n  margin-inline: auto;          /* esquerda e direita */\n  padding-block: 1.5rem;        /* cima e baixo */\n  border-inline-start: 4px solid #2f6fed;  /* borda no 'começo' do texto */\n  inline-size: min(100%, 60ch); /* largura */\n}`, r: "css/caixa/margin", k: "margin left right|esquerda e direita juntos|rtl|idioma da direita para esquerda|margin inline|padding block" }),
    S({ s: "safe-area", t: "env(safe-area-inset-*)", d: "Evita que o conteúdo fique atrás do notch, da barra de gestos e dos cantos arredondados do celular.", x: "padding-bottom: env(safe-area-inset-bottom);",
      n: "Exige viewport-fit=cover na meta viewport. Útil para barras fixas no rodapé em iPhones e Androids modernos, que senão ficam coladas na área de gestos.",
      ex: `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n\n.barra-inferior {\n  position: fixed; inset: auto 0 0 0;\n  padding: 12px 16px calc(12px + env(safe-area-inset-bottom));\n}`, k: "notch do iphone|barra inferior no celular|área segura|conteúdo atrás da barra de gestos|safe area" }),
  ]),

  cat("midia-impressao", "Media Features & Impressão", "Adapte o site às preferências do usuário, ao tipo de dispositivo e à impressão.", [
    S({ s: "media-preferencias", t: "@media de preferências do usuário", d: "prefers-contrast, forced-colors, hover, pointer, orientation e mais.", x: "@media (hover: hover) { ... }\n@media (pointer: coarse) { ... }",
      n: "(hover: hover) aplica efeitos de hover só onde existe mouse, evitando 'hover preso' no toque. (pointer: coarse) detecta dedo, e aí os alvos de clique devem ter ao menos 44px. prefers-contrast e forced-colors respeitam quem precisa de alto contraste.",
      ex: `/* hover só com mouse */\n@media (hover: hover) { .card:hover { transform: translateY(-4px); } }\n\n/* alvos maiores no toque */\n@media (pointer: coarse) { .btn { min-height: 48px; } }\n\n/* mais contraste quando o usuário pede */\n@media (prefers-contrast: more) { :root { --borda: #000; } }\n\n/* orientação */\n@media (orientation: landscape) { .hero { min-height: 100dvh; } }`,
      r: "css/transicoes/prefers-reduced-motion|css/unidades-funcoes/prefers-color-scheme", k: "hover no celular|alvo de toque|dedo ou mouse|alto contraste|orientação da tela|paisagem retrato|forced colors" }),
    S({ s: "print", t: "@media print e @page", d: "Estilos para quando a página é impressa ou salva como PDF.", x: "@media print { nav, .anuncio { display: none; } }\n@page { size: A4; margin: 2cm; }",
      n: "Esconda navegação e botões, use fundo branco e texto preto, mostre a URL dos links e evite quebrar elementos no meio da página com break-inside: avoid. É assim que se gera um PDF bonito (currículos, faturas) direto do navegador.",
      ex: `@media print {\n  nav, footer, .btn, .anuncio { display: none !important; }\n  body { color: #000; background: #fff; font-size: 12pt; }\n  a[href]::after { content: " (" attr(href) ")"; font-size: 90%; }\n  .card, tr { break-inside: avoid; }\n  h2 { break-after: avoid; }\n}\n@page { size: A4; margin: 2cm; }`, k: "imprimir página|gerar pdf pelo navegador|css de impressão|esconder menu ao imprimir|currículo em pdf|fatura" }),
    S({ s: "touch-action", t: "touch-action", d: "Controla quais gestos de toque o navegador deve tratar (rolar, zoom, arrastar).", x: "touch-action: none | pan-x | pan-y | manipulation;",
      n: "touch-action: manipulation remove o atraso de ~300ms do toque duplo (zoom) em botões. none é necessário em áreas de arrastar/desenhar (canvas, sliders customizados), senão a página rola junto.",
      k: "delay do toque no celular|arrastar no mobile|desabilitar zoom do toque|canvas no celular|slider arrastando a página" }),
  ]),

  cat("background-detalhado", "Fundo & Imagens em Detalhe", "Tamanho, posição, repetição e recorte de imagens de fundo, além de bordas com imagem.", [
    S({ s: "background-size", t: "background-size / position / repeat", d: "Controla como a imagem de fundo é dimensionada, posicionada e repetida.", x: "background: url(foto.jpg) center / cover no-repeat;",
      n: "cover preenche tudo (corta o excesso); contain mostra a imagem inteira (pode sobrar espaço). Na forma curta: posição / tamanho, nessa ordem, separados por barra.",
      v: "p:background:linear-gradient(135deg,#2f6fed,#e4572e) center / 40px 40px;background-repeat:repeat;min-height:90px", k: "imagem de fundo cobrindo tudo|background cover|contain|centralizar fundo|não repetir fundo|tamanho do fundo" }),
    S({ s: "background-clip", t: "background-clip & background-origin", d: "Define até onde o fundo se estende: borda, padding ou conteúdo (e o truque do texto).", x: "background-clip: padding-box | content-box | text;",
      n: "background-clip: text recorta o fundo no formato das letras (texto degradê). padding-box impede que o fundo apareça sob uma borda semitransparente.",
      v: "p:background:#2f6fed;padding:14px;border:10px dashed #e4572e;background-clip:content-box", r: "css/tipografia-avancada/text-gradient", k: "fundo só dentro do padding|fundo sob a borda|recortar fundo|clip text" }),
    S({ s: "background-blend-mode", t: "background-blend-mode", d: "Mistura as camadas de fundo (imagem + cor) como no Photoshop.", x: "background: url(foto.jpg), #2f6fed;\nbackground-blend-mode: multiply;",
      n: "multiply escurece, screen clareia, overlay aumenta contraste, luminosity e color permitem tingir fotos com uma cor da marca. Ótimo para 'duotone' e heros com texto legível.",
      ex: `.hero {\n  background: url(foto.jpg) center / cover, #1d4ed8;\n  background-blend-mode: multiply; /* foto tingida de azul */\n}`, r: "css/efeitos-avancados/mix-blend-mode", k: "tingir imagem|efeito duotone|misturar imagem com cor|escurecer foto com cor|overlay colorido" }),
    S({ s: "border-image", t: "border-image", d: "Usa uma imagem ou gradiente como borda.", x: "border: 8px solid;\nborder-image: linear-gradient(45deg, #2f6fed, #e4572e) 1;",
      n: "O número no final ('1') é o corte (slice). Com gradiente, funciona como borda degradê. Atenção: border-image ignora border-radius; para borda degradê arredondada use o truque de dois backgrounds (padding-box e border-box).",
      v: "i:border:8px solid;border-image:linear-gradient(45deg,#2f6fed,#e4572e) 1", a: "Usar junto com border-radius (a imagem não acompanha a curva)", k: "borda com gradiente|borda degradê|borda de imagem|borda colorida|border gradient" }),
    S({ s: "object-position", t: "object-position", d: "Escolhe qual parte da imagem aparece quando object-fit corta o excesso.", x: "object-fit: cover;\nobject-position: top center;",
      n: "Em fotos de pessoas, use object-position: top para o corte preservar o rosto. Funciona em img e video.", r: "css/efeitos-avancados/object-fit", k: "cortar imagem mantendo o rosto|enquadrar foto|posição da imagem cortada|foco da imagem" }),
    S({ s: "box-decoration-break", t: "box-decoration-break", d: "Faz o fundo e a borda de um texto em várias linhas serem desenhados como se cada linha fosse separada.", x: "box-decoration-break: clone;",
      n: "Sem isso, um <span> com padding e fundo que quebra de linha tem as pontas 'cortadas'. clone repete padding, borda e raio em cada linha, perfeito para o efeito 'marca-texto'.",
      ex: `.marca-texto {\n  background: #fde68a;\n  padding: .1em .4em;\n  border-radius: .3em;\n  -webkit-box-decoration-break: clone;\n  box-decoration-break: clone;\n}`, k: "marca texto|texto destacado em várias linhas|highlight|fundo do span quebrando|efeito marcador" }),
  ]),

  cat("tipografia-extra", "Tipografia: Fontes Variáveis & Detalhes", "Fontes variáveis, números e ligaduras, letra capitular, contadores e texto vertical.", [
    S({ s: "font-variation-settings", t: "Fontes variáveis (font-weight contínuo)", d: "Uma única fonte com peso, largura e inclinação ajustáveis em qualquer valor.", x: "font-weight: 350;\nfont-variation-settings: 'wdth' 90, 'opsz' 14;",
      n: "Fontes variáveis (Inter, Roboto Flex, Recursive) substituem vários arquivos por um só, e permitem pesos como 350 ou 650. Prefira as propriedades normais (font-weight, font-stretch) e use font-variation-settings só para eixos personalizados.",
      ex: `@font-face {\n  font-family: "Inter";\n  src: url("Inter.var.woff2") format("woff2");\n  font-weight: 100 900;   /* faixa suportada */\n  font-display: swap;\n}\nh1 { font-weight: 750; }`, r: "css/tipografia/font-face", k: "fonte variável|peso intermediário da fonte|variable font|um arquivo de fonte só|font weight 350" }),
    S({ s: "font-feature-settings", t: "font-feature-settings / ligaduras", d: "Ativa recursos tipográficos: ligaduras, versaletes, numerais, frações.", x: "font-variant-ligatures: common-ligatures;\nfont-feature-settings: 'ss01', 'tnum';",
      n: "Quando existir propriedade própria (font-variant-numeric, font-variant-caps), use ela. font-feature-settings serve para conjuntos estilísticos ('ss01') e fontes de código (ligaduras como => e !=).",
      k: "ligaduras|versalete|small caps|números tabulares|fonte de código com ligaduras|alternativas de letras" }),
    S({ s: "font-display", t: "font-display", d: "Define o que mostrar enquanto uma fonte web ainda está carregando.", x: "@font-face { font-family: X; src: url(x.woff2); font-display: swap; }",
      n: "swap mostra a fonte do sistema imediatamente e troca quando a web carregar (evita texto invisível); optional só usa a fonte se já estiver pronta (melhor para desempenho). Pré-carregue com <link rel=\"preload\" as=\"font\">.",
      k: "texto invisível ao carregar fonte|fonte demorando|flash de fonte|fout foit|performance de fonte" }),
    S({ s: "initial-letter", t: "::first-letter e letra capitular", d: "Aumenta a primeira letra do parágrafo (efeito de livro e revista).", x: "p::first-letter { initial-letter: 3; }",
      n: "initial-letter faz a capitular ocupar N linhas alinhada automaticamente. Em navegadores sem suporte, o fallback clássico com float e font-size funciona em todos.",
      ex: `/* moderno */\n.artigo p:first-of-type::first-letter { initial-letter: 3; color: #b3261e; margin-right: .3rem; }\n\n/* fallback clássico */\n.artigo p:first-of-type::first-letter { float: left; font-size: 3.2em; line-height: .8; padding-right: .1em; }`,
      k: "primeira letra grande|letra capitular|drop cap|inicial de parágrafo|first letter" }),
    S({ s: "text-stroke", t: "-webkit-text-stroke & paint-order", d: "Contorno nas letras (texto vazado ou com borda).", x: "-webkit-text-stroke: 2px #2f6fed;\ncolor: transparent;",
      n: "Texto vazado: color transparent + stroke. Para borda que não 'come' a letra por dentro, use paint-order: stroke fill.",
      v: "p:-webkit-text-stroke:2px #2f6fed;color:transparent;font-size:34px;font-weight:900", k: "texto vazado|contorno na letra|texto com borda|outline no texto|letra oca" }),
    S({ s: "writing-mode", t: "writing-mode & text-orientation", d: "Texto na vertical (japonês, rótulos laterais, títulos em pé).", x: "writing-mode: vertical-rl;\ntext-orientation: mixed;",
      n: "vertical-rl escreve de cima para baixo; combine com rotate(180deg) para inverter o sentido de leitura em rótulos laterais.",
      v: "p:writing-mode:vertical-rl;height:90px;font-size:20px", k: "texto na vertical|texto de lado|rótulo lateral|título em pé|vertical text" }),
    S({ s: "counters", t: "counter-reset / counter-increment", d: "Numeração automática com CSS (títulos, listas e passos).", x: "body { counter-reset: secao; }\nh2::before { counter-increment: secao; content: counter(secao) '. '; }",
      n: "Gera 1., 2., 3. sem escrever números no HTML, e reinicia por seção. counters() cria numeração aninhada (1.1, 1.2). Muito usado em passos, sumários e termos jurídicos.",
      ex: `body { counter-reset: passo; }\n.passo { counter-increment: passo; }\n.passo::before {\n  content: counter(passo);\n  display: inline-grid; place-items: center;\n  width: 28px; height: 28px; margin-right: 10px;\n  border-radius: 50%; background: #2f6fed; color: #fff; font-weight: 700;\n}`, k: "numeração automática|numerar títulos|contador css|lista numerada personalizada|passos numerados|counter" }),
    S({ s: "text-indent-spacing", t: "text-indent, word-spacing, tab-size", d: "Recuo da primeira linha, espaço entre palavras e largura do Tab.", x: "text-indent: 2em;\nword-spacing: .1em;\ntab-size: 2;",
      n: "text-indent dá o recuo de parágrafo de livro. tab-size controla quantos espaços um Tab ocupa em blocos de código (<pre>), muito usado em sites de programação.",
      v: "p:text-indent:2em;word-spacing:.3em", k: "recuo de parágrafo|espaço entre palavras|largura do tab no código|primeira linha deslocada" }),
  ]),

  cat("formularios-css", "Formulários: Estados & Estilo", "Pseudo-classes de estado dos campos e partes internas de controles nativos.", [
    S({ s: "form-states", t: "Estados de formulário (:checked, :disabled, :placeholder-shown...)", d: "Estilize campos conforme o estado: marcado, desativado, vazio, obrigatório, válido.", x: "input:checked + label { ... }\ninput:disabled { ... }\ninput:placeholder-shown { ... }",
      n: ":user-valid e :user-invalid só avaliam depois que o usuário interage (melhor que :invalid, que marca vermelho antes de digitar). :placeholder-shown permite label flutuante só com CSS. :required, :optional, :read-only, :in-range e :indeterminate completam o conjunto.",
      ex: `input:required { border-left: 3px solid #e4572e; }\ninput:user-invalid { border-color: #dc2626; }\ninput:user-valid { border-color: #16a34a; }\ninput:disabled { opacity: .5; cursor: not-allowed; }\ninput:placeholder-shown { background: #f9fafb; }\ninput:checked + label { font-weight: 700; }\ninput:indeterminate { accent-color: #f59e0b; }`,
      r: "css/seletores-modernos/focus-within|css/efeitos-ui/appearance", k: "campo inválido|campo válido|campo obrigatório|checkbox marcado|input desativado|placeholder visível|validação css|user invalid" }),
    S({ s: "file-selector-button", t: "::file-selector-button e partes internas", d: "Estiliza o botão interno de input file e outras partes de controles nativos.", x: "input[type=file]::file-selector-button { ... }",
      n: "Outras partes úteis: ::placeholder (texto de dica), ::-webkit-search-cancel-button (X da busca), ::-webkit-slider-thumb e ::-webkit-slider-runnable-track (input range) e accent-color (cor de checkbox/radio/range sem recriar o controle).",
      ex: `input[type=file]::file-selector-button {\n  margin-right: 12px; padding: 8px 14px;\n  border: 0; border-radius: 8px;\n  background: #2f6fed; color: #fff; cursor: pointer;\n}\ninput::placeholder { color: #9ca3af; opacity: 1; }\ninput[type=range] { accent-color: #2f6fed; }`, r: "css/interacao/accent-color", k: "botão de escolher arquivo|estilizar input file|placeholder cor|slider range personalizado|campo de upload" }),
    S({ s: "autofill", t: ":autofill", d: "Estiliza campos preenchidos automaticamente pelo navegador (amarelo/azul padrão).", x: "input:autofill { box-shadow: inset 0 0 0 100px #fff; -webkit-text-fill-color: #111; }",
      n: "O navegador força um fundo próprio em campos autopreenchidos. O truque da sombra inset grande 'pinta' por cima, mantendo o visual do seu tema (especialmente em modo escuro).",
      k: "campo preenchido automático amarelo|autocomplete fundo azul|autofill estilo|input escuro com autopreenchimento" }),
  ]),

  cat("css-global", "Valores Globais & Cascata", "initial, inherit, unset, revert e all: como resetar e herdar estilos.", [
    S({ s: "valores-globais", t: "inherit, initial, unset, revert, all", d: "Palavras-chave que funcionam em qualquer propriedade para herdar ou resetar.", x: "color: inherit;\nall: unset;\nborder: revert;",
      n: "inherit: copia do pai. initial: valor padrão da especificação. unset: inherit se a propriedade é herdada, senão initial. revert: volta ao estilo padrão do navegador (o mais útil). all: unset zera tudo: ótimo para tirar o estilo nativo de um <button> e começar do zero.",
      ex: `a { color: inherit; text-decoration: none; }   /* links herdam a cor do texto */\n\n.btn-limpo { all: unset; cursor: pointer; }     /* zera o estilo nativo do botão */\n.btn-limpo:focus-visible { outline: 3px solid #2f6fed; }`,
      r: "css/selecao/especificidade", k: "resetar estilo|herdar cor do pai|remover estilo padrão do botão|all unset|voltar ao padrão|revert" }),
    S({ s: "important", t: "!important e como evitar", d: "Força uma regra a vencer a cascata, e por que isso quase sempre é sinal de problema.", x: "color: red !important;",
      n: "!important ignora a especificidade e só perde para outro !important. Cria uma 'corrida armamentista' difícil de manter. Prefira @layer, aumentar a especificidade de forma deliberada ou reorganizar o CSS. Usos legítimos: classes utilitárias (.hidden) e sobrescrever estilos inline de terceiros.",
      a: "Usar para 'consertar' uma regra que não aplica sem entender o motivo", r: "css/seletores-modernos/layer|css/selecao/especificidade", k: "important não funciona|estilo não aplica|regra não funciona|sobrescrever css|guerra de especificidade" }),
  ]),
];
