import { S, cat } from "@/content/helpers";

export const cssB = [
  cat("grid-detalhado", "Grid em Detalhe", "Controle fino de linhas, colunas e áreas nomeadas no CSS Grid.", [
    S({ s: "grid-template-columns", t: "grid-template-columns / rows", d: "Define o número e tamanho das colunas/linhas do grid.", x: "grid-template-columns: 1fr 2fr 1fr;\ngrid-template-columns: repeat(3, 1fr);",
      n: "'fr' distribui o espaço disponível em frações. repeat(auto-fit, minmax(200px, 1fr)) cria colunas responsivas que se ajustam sozinhas ao espaço.",
      v: "g:grid-template-columns:2fr 1fr",
      k: "colunas do grid|largura das colunas|linhas do grid|grid responsivo" }),
    S({ s: "grid-column-row", t: "grid-column / grid-row", d: "Faz um item do grid ocupar mais de uma coluna ou linha.", x: "grid-column: 1 / 3;\ngrid-row: span 2;",
      n: "'1 / 3' vai da linha de grade 1 até a 3 (ocupando 2 colunas). 'span 2' é um atalho para 'ocupe 2 colunas/linhas a partir daqui'.",
      v: "gi:grid-column:span 2;background:#e4572e;color:#fff",
      k: "item ocupar duas colunas|mesclar células do grid|item maior no grid|colspan no css" }),
    S({ s: "grid-template-areas", t: "grid-template-areas", d: "Nomeia regiões do grid para montar o layout visualmente no CSS.", x: "grid-template-areas:\n  \"header header\"\n  \"sidebar main\";",
      n: "Cada string é uma linha do grid; cada palavra é uma coluna. Depois, cada item usa grid-area: nome para se posicionar na região correspondente — o layout fica legível só de olhar o CSS.",
      ex: `.pagina {\n  display: grid;\n  grid-template-columns: 200px 1fr;\n  grid-template-areas:\n    "header header"\n    "sidebar main";\n}\n.header { grid-area: header; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }`,
      k: "layout nomeado|área do grid|montar layout de página|grid area" }),
    S({ s: "place-items", t: "place-items / place-content", d: "Atalho para centralizar em ambos os eixos de uma vez.", x: "place-items: center;\nplace-content: center;",
      n: "'place-items: center' equivale a align-items:center + justify-items:center — a forma mais curta de centralizar itens dentro de células do grid/flex.",
      v: "g:place-items:center;min-height:150px",
      k: "centralizar tudo|centralizar grid|atalho de centralização|place items center" }),
  ]),

  cat("visibilidade", "Display, Visibilidade & Camadas", "Mostrar, esconder e empilhar elementos.", [
    S({ s: "display-values", t: "display (block, inline, none...)", d: "Define como um elemento se comporta no fluxo da página.", x: "display: block | inline | inline-block | none | flex | grid;",
      n: "block ocupa a linha toda. inline não quebra linha e ignora width/height. inline-block é o meio-termo: fica na linha mas aceita tamanho. 'none' remove o elemento do layout como se não existisse.",
      v: "i:display:inline-block;background:#2f6fed;color:#fff",
      k: "tipo de exibição|bloco ou linha|esconder elemento|display none|mostrar elemento" }),
    S({ s: "visibility", t: "visibility", d: "Esconde um elemento mas mantém o espaço que ele ocupava.", x: "visibility: hidden | visible;",
      n: "Diferente de display:none (que remove o elemento do layout), visibility:hidden só o torna invisível — o espaço continua reservado. Elementos com visibility:hidden não recebem cliques.",
      v: "i:visibility:hidden;background:#2f6fed",
      k: "esconder mantendo espaço|invisível|ocultar sem remover layout" }),
    S({ s: "z-index", t: "z-index", d: "Controla qual elemento fica por cima em caso de sobreposição.", x: "z-index: 10;",
      n: "Só funciona em elementos com position diferente de static (relative, absolute, fixed, sticky). Números maiores ficam por cima de números menores.",
      ex: `.modal {\n  position: fixed;\n  z-index: 50;\n}\n.overlay {\n  position: fixed;\n  z-index: 40;\n}`,
      k: "camada por cima|sobrepor elementos|ordem de empilhamento|elemento na frente" }),
  ]),

  cat("seletores-avancados", "Seletores Avançados", "Formas mais precisas e modernas de escolher elementos.", [
    S({ s: "is-where-not", t: ":is() / :where() / :not()", d: "Agrupam ou excluem seletores para evitar repetição.", x: ":is(h1, h2, h3) { }\n:not(.ativo) { }",
      n: ":is() e :where() aceitam uma lista e casam com qualquer um deles (:where tem especificidade zero, :is herda a maior da lista). :not() exclui o que casar com o seletor dentro dos parênteses.",
      ex: `:is(h1, h2, h3) {\n  font-family: "Space Grotesk", sans-serif;\n}\n\nli:not(:last-child) {\n  border-bottom: 1px solid #eee;\n}`,
      k: "selecionar vários títulos de uma vez|exceto o último|excluir elemento do seletor|not css" }),
    S({ s: "attribute-selector", t: "Seletor de atributo [attr]", d: "Seleciona elementos pelo valor de um atributo HTML.", x: `[disabled] { }\n[type="email"] { }\n[href^="https"] { }`,
      n: "^= começa com, $= termina com, *= contém. Muito usado para estilizar inputs por tipo ou links externos sem precisar adicionar classes extras.",
      ex: `input[type="checkbox"] {\n  accent-color: #2f6fed;\n}\n\na[href^="http"]::after {\n  content: " ↗";\n}`,
      k: "selecionar por atributo|selecionar por tipo de input|link externo css|atributo html no css" }),
    S({ s: "nth-child-family", t: ":nth-child() / :first-child / :last-child", d: "Selecionam elementos pela posição entre os irmãos.", x: ":first-child { }\n:last-child { }\n:nth-child(3n) { }",
      n: ":nth-child(2n) pega pares, (2n+1) ímpares, (3n) todo terceiro. :nth-of-type ignora outros tipos de elemento na contagem, útil quando há tags diferentes misturadas.",
      ex: `li:first-child { margin-top: 0; }\nli:last-child { border-bottom: none; }\ntr:nth-child(3n) { background: #f3f4f6; }`,
      k: "primeiro item|último item|todo terceiro item|zebrar tabela|posição na lista" }),
    S({ s: "selection-placeholder", t: "::selection / ::placeholder", d: "Estilizam o texto selecionado e o texto de exemplo de um input.", x: "::selection { background: gold; }\ninput::placeholder { color: #999; }",
      ex: `::selection {\n  background: #2f6fed;\n  color: white;\n}\n\ninput::placeholder {\n  color: #9ca3af;\n  font-style: italic;\n}`,
      k: "cor da seleção de texto|estilizar placeholder|texto de exemplo do input" }),
    S({ s: "universal-selector", t: "* (seletor universal)", d: "Seleciona todos os elementos da página.", x: "* { box-sizing: border-box; }",
      ex: `* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}`, a: "Regras de performance pesadas aplicadas a * — afeta todo elemento da página",
      k: "selecionar tudo|reset css|todos os elementos|asterisco css" }),
  ]),

  cat("interacao", "Interação & Usabilidade", "Como a página responde ao mouse, toque e seleção do usuário.", [
    S({ s: "cursor", t: "cursor", d: "Define o ícone do mouse ao passar sobre um elemento.", x: "cursor: pointer | not-allowed | grab | text | wait;",
      n: "'pointer' (mãozinha) indica que é clicável — use em qualquer elemento clicável que não seja nativamente um botão/link.",
      v: "i:cursor:pointer;background:#2f6fed;color:#fff",
      k: "mãozinha do mouse|cursor de clique|cursor não permitido|ícone do mouse" }),
    S({ s: "user-select", t: "user-select", d: "Controla se o texto pode ser selecionado pelo usuário.", x: "user-select: none | text | all;",
      n: "'none' impede selecionar/copiar o texto — útil em botões e interfaces tipo app, mas evite em conteúdo de leitura.",
      v: "i:user-select:none;background:#2f6fed;color:#fff",
      k: "impedir seleção de texto|não deixar copiar|desabilitar seleção" }),
    S({ s: "pointer-events", t: "pointer-events", d: "Liga/desliga a capacidade de um elemento receber cliques.", x: "pointer-events: none | auto;",
      n: "'none' faz cliques 'atravessarem' o elemento como se ele não existisse — muito usado em ícones dentro de botões e overlays desabilitados.",
      ex: `.botao[disabled] {\n  pointer-events: none;\n  opacity: 0.5;\n}`,
      k: "desabilitar clique|ignorar cliques|elemento não clicável|bloquear interação" }),
    S({ s: "resize", t: "resize", d: "Permite o usuário redimensionar um elemento arrastando o canto.", x: "resize: both | horizontal | vertical | none;",
      n: "Só funciona em elementos com overflow diferente de visible (textareas já vêm com isso por padrão).",
      v: "i:resize:both;overflow:auto;width:120px;height:70px",
      k: "redimensionar caixa|arrastar canto|textarea redimensionável" }),
    S({ s: "accent-color", t: "accent-color", d: "Muda a cor de checkboxes, radios e outros controles nativos.", x: "input { accent-color: #2f6fed; }",
      ex: `input[type="checkbox"],\ninput[type="radio"] {\n  accent-color: #2f6fed;\n}`,
      k: "cor do checkbox|cor do radio button|colorir controles nativos" }),
  ]),

  cat("regras-especiais", "Regras Especiais (@)", "Diretivas que mudam como blocos inteiros de CSS se comportam.", [
    S({ s: "keyframes", t: "@keyframes", d: "Define as etapas de uma animação para usar com animation.", x: "@keyframes nome {\n  from { }\n  to { }\n}",
      n: "'from/to' são atalhos para 0%/100% — pode usar porcentagens intermediárias para controlar etapas no meio do caminho. A animação só roda quando referenciada via 'animation: nome duração'.",
      v: "a:animation:pulse 1s ease-in-out infinite",
      k: "criar animação|etapas da animação|animation keyframes|pulsar|girar sem parar" }),
    S({ s: "supports", t: "@supports", d: "Aplica um bloco de CSS só se o navegador suportar uma propriedade.", x: "@supports (display: grid) {\n  ...\n}",
      ex: `@supports (backdrop-filter: blur(10px)) {\n  .header {\n    backdrop-filter: blur(10px);\n    background: rgb(255 255 255 / 0.6);\n  }\n}`,
      k: "suporte do navegador|feature query|css condicional|verificar suporte" }),
    S({ s: "import", t: "@import", d: "Importa outro arquivo CSS de dentro de um CSS.", x: "@import url('reset.css');",
      n: "Deve vir no topo do arquivo. Tem um pequeno custo de performance (requisição extra) — para produção, muitas vezes é melhor combinar os arquivos no build.",
      ex: `@import url('https://fonts.googleapis.com/css2?family=Inter');\n@import 'variaveis.css';`,
      k: "importar outro css|combinar arquivos css|importar fonte" }),
  ]),

  cat("efeitos-avancados", "Efeitos Visuais Avançados", "Recursos modernos para composição visual e imagens.", [
    S({ s: "backdrop-filter", t: "backdrop-filter", d: "Aplica um filtro no que está atrás do elemento (efeito 'vidro fosco').", x: "backdrop-filter: blur(12px);",
      n: "Diferente de filter (que afeta o próprio elemento), backdrop-filter borra/ajusta o conteúdo que aparece por trás — muito usado em headers e modais translúcidos.",
      ex: `.header {\n  background: rgb(255 255 255 / 0.7);\n  backdrop-filter: blur(10px);\n}`,
      k: "vidro fosco|glassmorphism|desfocar fundo|efeito de vidro" }),
    S({ s: "clip-path", t: "clip-path", d: "Recorta um elemento numa forma customizada.", x: "clip-path: circle(50%);\nclip-path: polygon(50% 0%, 0% 100%, 100% 100%);",
      ex: `.avatar {\n  clip-path: circle(50%);\n}\n.banner {\n  clip-path: polygon(0 0, 100% 0, 100% 85%, 0 100%);\n}`,
      k: "recortar elemento|forma customizada|máscara de recorte|corte diagonal" }),
    S({ s: "mix-blend-mode", t: "mix-blend-mode", d: "Define como um elemento se mistura visualmente com o que está atrás.", x: "mix-blend-mode: multiply | screen | overlay | difference;",
      ex: `.texto-sobre-imagem {\n  mix-blend-mode: difference;\n  color: white;\n}`,
      k: "misturar cores|modo de mesclagem|efeito de sobreposição de cor" }),
    S({ s: "object-fit", t: "object-fit", d: "Controla como uma imagem/vídeo se ajusta dentro de um tamanho fixo.", x: "img { object-fit: cover; }",
      n: "'cover' preenche o espaço cortando o excesso (mantém proporção). 'contain' encolhe pra caber inteira, sem cortar. Sem isso, imagens em caixas fixas ficam esticadas/distorcidas.",
      ex: `.avatar {\n  width: 80px;\n  height: 80px;\n  object-fit: cover;\n  border-radius: 50%;\n}`,
      k: "imagem cortada certo|imagem não distorcida|ajustar imagem na caixa|cover contain" }),
    S({ s: "text-shadow", t: "text-shadow", d: "Aplica uma sombra atrás do texto.", x: "text-shadow: 1px 2px 4px rgba(0,0,0,0.4);",
      n: "Os valores são: deslocamento horizontal, vertical, desfoque e cor — igual ao box-shadow, mas seguindo o formato exato das letras em vez de um retângulo. Pode empilhar várias sombras separadas por vírgula.",
      v: "p:font-size:28px;font-weight:700;text-shadow:2px 2px 6px rgba(0,0,0,.4)",
      k: "sombra no texto|sombra na letra|efeito de sombra no título|text shadow" }),
    S({ s: "text-decoration", t: "text-decoration", d: "Sublinhado, tachado ou nenhuma decoração no texto.", x: "text-decoration: underline | line-through | none;",
      n: "Muito usado para remover o sublinhado padrão de links (text-decoration: none) ou adicionar sublinhado customizado com text-decoration-color/thickness.",
      v: "p:text-decoration:underline;text-decoration-color:#2f6fed;text-decoration-thickness:2px",
      k: "sublinhar texto|remover sublinhado do link|tachar texto|decoração de texto" }),
    S({ s: "text-align", t: "text-align", d: "Alinha o texto horizontalmente dentro do elemento.", x: "text-align: left | center | right | justify;",
      v: "p:text-align:center",
      k: "centralizar texto|alinhar texto à direita|justificar texto|alinhamento de texto" }),
    S({ s: "text-transform", t: "text-transform", d: "Transforma a capitalização do texto via CSS, sem mudar o HTML.", x: "text-transform: uppercase | lowercase | capitalize;",
      v: "p:text-transform:uppercase;letter-spacing:.05em",
      k: "texto maiúsculo com css|primeira letra maiúscula|caixa alta css|capitalizar" }),
    S({ s: "aspect-ratio", t: "aspect-ratio", d: "Mantém uma proporção fixa entre largura e altura.", x: "aspect-ratio: 16 / 9;",
      n: "Evita ter que calcular a altura manualmente — muito usado em vídeos, thumbnails e placeholders de imagem para evitar layout shift.",
      ex: `.video-wrapper {\n  aspect-ratio: 16 / 9;\n  width: 100%;\n}`,
      k: "proporção da imagem|16 por 9|manter proporção|evitar distorção" }),
  ]),
];
