import { S, cat } from "@/content/helpers";

export const cssA = [
  cat("caixa", "Modelo de Caixa (Box Model)", "As propriedades mais usadas do CSS: espaçamento, tamanho e overflow.", [
    S({ s: "margin", t: "margin", d: "Espaço fora do elemento, entre ele e os vizinhos.", x: "margin: cima direita baixo esquerda;",
      n: "Uma unidade só aplica nos 4 lados. Duas: vertical horizontal. Quatro: sentido horário a partir do topo. Use margin-top/right/bottom/left para um lado só. margin: 0 auto centraliza horizontalmente um bloco com largura definida.",
      v: "f:justify-content:flex-start;.box.target{margin-left:40px}",
      u: "Afastar um elemento dos vizinhos|Centralizar um bloco com margin:0 auto",
      k: "espaço entre elementos|afastar da borda|margem direita|margem esquerda|margem em cima|margem embaixo|espaçamento externo|centralizar com margin auto" }),
    S({ s: "padding", t: "padding", d: "Espaço interno, entre o conteúdo e a borda do elemento.", x: "padding: cima direita baixo esquerda;",
      n: "Mesma lógica de valores do margin, mas para dentro. Diferente de margin, padding conta na área clicável/de fundo do elemento.",
      v: "p:padding:24px 40px;background:#dbeafe",
      k: "espaço interno|preenchimento|respiro do texto|afastar conteúdo da borda|padding direita|padding embaixo" }),
    S({ s: "width-height", t: "width / height", d: "Largura e altura de um elemento.", x: "width: 100%;\nheight: 300px;\nmax-width: 600px;\nmin-height: 100vh;",
      n: "min-/max- definem limites sem travar um valor fixo — muito usados para responsividade. '100vh' é a altura total da tela.",
      v: "i:width:180px;height:60px;background:#dbeafe",
      k: "tamanho|largura|altura|largura máxima|altura mínima|ocupar tela toda" }),
    S({ s: "box-sizing", t: "box-sizing", d: "Decide se padding/border somam ao tamanho definido ou ficam dentro dele.", x: "* { box-sizing: border-box; }",
      n: "content-box (padrão): width define só o conteúdo, padding/border somam por cima. border-box: width já inclui padding e border — muito mais previsível, por isso é comum resetar tudo para border-box no início do CSS.",
      ex: `* {\n  box-sizing: border-box;\n}\n\n.caixa {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid;\n  /* com border-box, a largura total continua 200px */\n}`,
      k: "tamanho incluindo borda|largura previsível|reset css|content-box" }),
    S({ s: "overflow", t: "overflow", d: "Controla o que acontece quando o conteúdo é maior que a caixa.", x: "overflow: visible | hidden | scroll | auto;",
      n: "hidden corta o excesso. scroll sempre mostra barra de rolagem. auto só mostra a barra quando necessário. overflow-x/overflow-y controlam cada eixo separado.",
      v: "p:overflow:auto;height:56px;border:2px solid #2f6fed;padding:6px",
      k: "cortar conteúdo|barra de rolagem|scroll|esconder excesso|rolagem horizontal" }),
  ]),

  cat("cores-fundo", "Cores & Fundo", "Como definir cores, imagens de fundo e transparência.", [
    S({ s: "color-formats", t: "Formatos de cor (hex, rgb, hsl)", d: "As formas de escrever uma cor em CSS.", x: "color: #2f6fed;\ncolor: rgb(47 111 237 / 0.8);\ncolor: hsl(220 85% 56%);",
      n: "hex é o mais comum (#rrggbb). rgb() aceita um canal alpha após a barra para transparência. hsl(matiz saturação luminosidade) é mais intuitivo para criar variações da mesma cor ajustando só a luminosidade.",
      v: "p:color:hsl(220 85% 56%);font-weight:700",
      k: "cor hexadecimal|rgb|hsl|cor com transparência|código de cor" }),
    S({ s: "background", t: "background / background-color", d: "Define a cor ou imagem de fundo de um elemento.", x: "background: #f3f4f6;\nbackground: url('img.jpg') center/cover no-repeat;",
      n: "'background' é um shorthand que aceita cor, imagem, posição, tamanho e repetição juntos. Para só a cor, background-color é mais explícito.",
      v: "i:background:#1f9c7a;color:#fff",
      k: "cor de fundo|imagem de fundo|background color|fundo colorido" }),
    S({ s: "background-gradient", t: "Gradiente (linear-gradient)", d: "Cria uma transição suave entre duas ou mais cores como fundo.", x: "background: linear-gradient(to right, #2f6fed, #1f9c7a);",
      n: "O primeiro argumento é a direção (to right, to bottom, ou um ângulo em graus). radial-gradient() cria um gradiente circular a partir do centro.",
      ex: `.banner {\n  background: linear-gradient(135deg, #e4572e, #2f6fed);\n}\n\n.holofote {\n  background: radial-gradient(circle, #fff, #1f9c7a);\n}`,
      k: "degradê|gradiente de cor|fundo degradê|transição de cores no fundo|linear-gradient|radial-gradient" }),
    S({ s: "opacity", t: "opacity", d: "Transparência de um elemento inteiro (incluindo filhos).", x: "opacity: 0.5;",
      n: "Vai de 0 (invisível) a 1 (opaco). Diferente de 'color com alpha', opacity afeta TUDO dentro do elemento, inclusive texto e bordas — para transparência só do fundo, use rgb()/hsl() com canal alpha.",
      v: "i:opacity:0.5;background:#2f6fed;color:#fff",
      k: "transparência|elemento transparente|opacidade|semitransparente" }),
  ]),

  cat("bordas", "Bordas", "Contornos, cantos arredondados e o efeito de foco.", [
    S({ s: "border", t: "border", d: "Contorno ao redor de um elemento.", x: "border: largura estilo cor;",
      n: "border-style aceita solid, dashed, dotted, double, none. Para um lado só, use border-top/right/bottom/left (ex: border-bottom para uma linha só embaixo).",
      v: "i:border:3px solid #2f6fed",
      u: "border-bottom sozinho para uma linha divisória|border completo para destacar uma caixa",
      k: "contorno|moldura|linha ao redor|borda embaixo|borda em cima|borda tracejada|border-bottom" }),
    S({ s: "border-radius", t: "border-radius", d: "Arredonda os cantos de um elemento.", x: "border-radius: 8px;\nborder-radius: 50%;",
      n: "Um valor arredonda os 4 cantos igualmente. 50% num elemento quadrado cria um círculo perfeito. Pode dar 4 valores para cada canto (cima-esq, cima-dir, baixo-dir, baixo-esq).",
      v: "i:border-radius:16px;background:#2f6fed",
      u: "border-radius:50% para avatares e ícones circulares",
      k: "cantos arredondados|arredondar quinas|círculo com css|avatar redondo|border radius" }),
    S({ s: "outline", t: "outline", d: "Contorno que não afeta o layout — ótimo para foco de acessibilidade.", x: "outline: 2px solid #2f6fed;\noutline-offset: 2px;",
      n: "Diferente de border, outline não ocupa espaço no layout (não empurra outros elementos) e pode ficar por fora da caixa com outline-offset. Nunca remova outline:none sem colocar um substituto visível para quem navega pelo teclado.",
      ex: `button:focus-visible {\n  outline: 2px solid #2f6fed;\n  outline-offset: 2px;\n}`,
      a: "outline: none sem nenhum substituto — quebra a navegação por teclado",
      k: "contorno de foco|anel de foco|acessibilidade de teclado|focus ring" }),
  ]),

  cat("flexbox-detalhado", "Flexbox em Detalhe", "As propriedades individuais que fazem o flexbox funcionar direito.", [
    S({ s: "justify-content", t: "justify-content", d: "Alinha os itens ao longo do eixo principal do flex/grid.", x: "justify-content: flex-start | center | flex-end | space-between | space-around | space-evenly;",
      n: "No flex-direction padrão (row), o eixo principal é horizontal. space-between empurra o primeiro e último para as bordas; space-evenly distribui o espaço igualmente entre e ao redor de todos.",
      v: "f:justify-content:space-between",
      k: "distribuir espaço|alinhar horizontalmente|espaçar itens|centralizar itens flex" }),
    S({ s: "align-items", t: "align-items", d: "Alinha os itens no eixo cruzado (perpendicular) do flex/grid.", x: "align-items: stretch | flex-start | center | flex-end | baseline;",
      n: "No flex-direction padrão (row), o eixo cruzado é vertical — align-items:center centraliza os itens verticalmente dentro do container.",
      v: "f:align-items:center;min-height:150px",
      k: "centralizar verticalmente|alinhar verticalmente|align items center" }),
    S({ s: "flex-direction", t: "flex-direction", d: "Define se os itens do flex ficam em linha ou coluna.", x: "flex-direction: row | column | row-reverse | column-reverse;",
      n: "row (padrão): itens lado a lado. column: itens empilhados verticalmente — nesse caso, justify-content passa a controlar o eixo vertical e align-items o horizontal.",
      v: "f:flex-direction:column;gap:6px",
      k: "flex em coluna|empilhar itens|direção do flex|itens na vertical" }),
    S({ s: "flex-wrap", t: "flex-wrap", d: "Permite que os itens do flex quebrem para a próxima linha.", x: "flex-wrap: nowrap | wrap | wrap-reverse;",
      n: "Por padrão (nowrap), o flexbox tenta espremer tudo numa linha só, encolhendo os itens. Com wrap, quando não cabe mais, os itens que sobram vão para a linha de baixo.",
      ex: `.container {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 8px;\n}`,
      k: "quebrar linha no flex|itens flex várias linhas|flex responsivo" }),
    S({ s: "flex-grow-shrink-basis", t: "flex-grow / flex-shrink / flex-basis", d: "Controlam como um item cresce, encolhe ou seu tamanho inicial dentro do flex.", x: "flex: grow shrink basis;\nflex: 1;",
      n: "flex-grow define a 'ganância' do item ao ocupar espaço extra (0 = não cresce). flex-shrink controla se ele encolhe quando falta espaço. flex-basis é o tamanho de partida antes de crescer/encolher. 'flex: 1' é um atalho comum para 'ocupar todo espaço disponível igualmente'.",
      ex: `.sidebar {\n  flex: 0 0 250px; /* não cresce, não encolhe, 250px fixos */\n}\n.conteudo {\n  flex: 1; /* ocupa todo o resto do espaço */\n}`,
      k: "item flex crescer|ocupar espaço restante|largura fixa no flex|flex 1" }),
  ]),
];
