import { H, cat } from "@/content/helpers";

export const htmlA = [
  cat("estrutura", "Estrutura & Semântica", "Esqueleto da página.", [
    H({ s: "aside", t: "<aside>", d: "Conteúdo lateral, relacionado mas não essencial.", x: "<aside>...</aside>",
      n: "Barras laterais, caixas de destaque, publicidade, links relacionados. Se fosse removido, o conteúdo principal continuaria fazendo sentido.",
      ex: `<article>\n  <h2>Título do post</h2>\n  <p>Texto principal...</p>\n  <aside>\n    <h3>Você sabia?</h3>\n    <p>Curiosidade relacionada.</p>\n  </aside>\n</article>`,
      k: "barra lateral|sidebar|caixa de destaque|conteúdo relacionado|nota lateral" }),
    H({ s: "footer", t: "<footer>", d: "Rodapé de uma página ou seção.", x: "<footer>...</footer>",
      n: "Direitos autorais, links úteis, contato, autoria. Pode existir um por página e um por seção/artigo.",
      ex: `<footer>\n  <p>&copy; 2026 Minha Empresa</p>\n  <nav><a href='/privacidade'>Privacidade</a></nav>\n</footer>`,
      k: "rodapé|final da página|copyright|direitos autorais|créditos" }),
    H({ s: "div", t: "<div>", d: "Contêiner genérico, sem significado semântico.", x: "<div class='...'>...</div>",
      n: "Serve para agrupar elementos para estilizar com CSS ou manipular com JS quando nenhuma tag semântica se encaixa.",
      ex: `<div class='card'>\n  <h3>Título</h3>\n  <p>Conteúdo</p>\n</div>`, a: "Quando existe uma tag semântica melhor (section, article, nav, header...)",
      k: "caixa|contêiner|container|agrupar elementos|bloco genérico" }),
    H({ s: "span", t: "<span>", d: "Trecho de texto genérico, em linha (inline).", x: "<span class='...'>texto</span>",
      n: "Igual ao div, mas inline: não quebra linha. Ideal para estilizar uma palavra ou parte de um texto.",
      ex: `<p>Preço: <span style='color:crimson;font-weight:bold'>R$ 99</span></p>`,
      k: "estilizar parte do texto|texto em linha|inline|destacar palavra" }),
    H({ s: "body", t: "<body>", d: "Todo o conteúdo visível da página.", x: "<body>...</body>",
      n: "Vem depois do <head>, dentro de <html>. Só pode existir um.", ex: `<body>\n  <h1>Olá!</h1>\n</body>`, np: 1,
      k: "corpo da página|conteúdo visível|estrutura básica" }),
    H({ s: "html", t: "<html>", d: "Elemento raiz de todo documento HTML.", x: "<html lang='pt-BR'>...</html>",
      n: "Sempre defina lang: ajuda leitores de tela, tradutores e SEO.",
      ex: `<!doctype html>\n<html lang='pt-BR'>\n  <head>...</head>\n  <body>...</body>\n</html>`, np: 1,
      k: "raiz|estrutura básica|doctype|idioma da página|lang" }),
    H({ s: "hgroup", t: "<hgroup>", d: "Agrupa um título com seu subtítulo.", x: "<hgroup><h1>..</h1><p>..</p></hgroup>",
      ex: `<hgroup>\n  <h1>Título principal</h1>\n  <p>Subtítulo ou slogan</p>\n</hgroup>`, k: "título e subtítulo|slogan|cabeçalho de título" }),
    H({ s: "search", t: "<search>", d: "Região da página dedicada a busca ou filtros.", x: "<search>...</search>",
      n: "Landmark semântico para formulários de busca — leitores de tela conseguem pular direto até ele.",
      ex: `<search>\n  <form action='/busca'>\n    <input type='search' name='q' placeholder='Buscar...'>\n    <button>Buscar</button>\n  </form>\n</search>`,
      k: "campo de busca|pesquisa|filtro do site" }),
    H({ s: "address", t: "<address>", d: "Informações de contato do autor ou da página.", x: "<address>...</address>",
      ex: `<address>\n  Ana Souza<br>\n  <a href='mailto:ana@email.com'>ana@email.com</a>\n</address>`,
      a: "Para endereços postais quaisquer — só para contato de quem escreveu/manteve o conteúdo", k: "contato|endereço|e-mail do autor" }),
  ]),

  cat("texto", "Texto & Conteúdo", "Títulos, parágrafos e formatações de texto com significado.", [
    H({ s: "headings", t: "<h1> a <h6>", d: "Títulos em 6 níveis de importância.", x: "<h1>..</h1> ... <h6>..</h6>",
      n: "Use um único h1 por página e desça os níveis em ordem (h2 dentro de h1, h3 dentro de h2). Nunca escolha por tamanho — para isso existe CSS.",
      ex: `<h1>Título da página</h1>\n<h2>Seção</h2>\n<h3>Subseção</h3>`, u: "Estruturar o conteúdo — leitores de tela navegam pelos títulos", a: "Escolher h3 só porque é menor: ajuste o tamanho no CSS",
      k: "título|cabeçalho|subtítulo|heading|h1|h2|h3|tamanho de título" }),
    H({ s: "p", t: "<p>", d: "Parágrafo de texto.", x: "<p>texto</p>", n: "Navegadores adicionam margem acima e abaixo. Não use <br> para separar parágrafos.",
      ex: `<p>Este é um parágrafo.</p>\n<p>Este é outro.</p>`, k: "parágrafo|texto|bloco de texto" }),
    H({ s: "br", t: "<br>", d: "Quebra de linha dentro de um texto.", x: "<br>",
      ex: `<p>Rua das Flores, 100<br>Centro<br>Natal - RN</p>`, a: "Criar espaço entre blocos — use margin no CSS", k: "pular linha|quebra de linha|nova linha|enter" }),
    H({ s: "hr", t: "<hr>", d: "Linha horizontal que separa temas.", x: "<hr>",
      ex: `<p>Fim do capítulo 1.</p>\n<hr>\n<p>Começo do capítulo 2.</p>`, k: "linha divisória|separador|linha horizontal|divisor" }),
    H({ s: "strong", t: "<strong>", d: "Texto de forte importância (negrito semântico).", x: "<strong>importante</strong>",
      ex: `<p><strong>Atenção:</strong> não compartilhe sua senha.</p>`, k: "negrito|bold|texto importante|destacar" }),
    H({ s: "em", t: "<em>", d: "Ênfase (itálico semântico).", x: "<em>texto</em>",
      ex: `<p>Eu <em>realmente</em> gosto de código.</p>`, k: "itálico|italic|ênfase|inclinado" }),
    H({ s: "b", t: "<b>", d: "Negrito visual, sem importância extra.", x: "<b>texto</b>",
      ex: `<p>Ingredientes: <b>farinha</b>, <b>ovos</b>.</p>`, k: "negrito|bold|palavra-chave em destaque" }),
    H({ s: "i", t: "<i>", d: "Itálico visual (termos técnicos, outro idioma, pensamentos).", x: "<i>texto</i>",
      ex: `<p>O termo <i lang='en'>cache</i> vem do inglês.</p>`, k: "itálico|italic|estrangeirismo|ícone (uso antigo)" }),
    H({ s: "u", t: "<u>", d: "Texto com sublinhado não textual (ex.: erro ortográfico).", x: "<u>texto</u>",
      a: "Sublinhar links ou por estilo — o sublinhado já significa link", ex: `<p>Palavra <u>escrita erado</u>.</p>`, k: "sublinhado|underline|sublinhar texto" }),
    H({ s: "s", t: "<s>", d: "Texto riscado que não é mais relevante.", x: "<s>texto</s>",
      ex: `<p>Preço: <s>R$ 120</s> R$ 90</p>`, k: "riscado|tachado|preço antigo|strikethrough" }),
    H({ s: "mark", t: "<mark>", d: "Destaca um trecho, como marca-texto.", x: "<mark>texto</mark>",
      ex: `<p>Resultado da busca: aprenda <mark>HTML</mark> hoje.</p>`, k: "marca-texto|destacar|grifar|highlight" }),
    H({ s: "small", t: "<small>", d: "Texto pequeno de apoio (notas legais, direitos).", x: "<small>texto</small>",
      ex: `<p>Oferta válida hoje. <small>*Sujeito a estoque.</small></p>`, k: "letra pequena|nota de rodapé|texto menor" }),
    H({ s: "sub-sup", t: "<sub> / <sup>", d: "Subscrito e sobrescrito.", x: "<sub>2</sub>  <sup>2</sup>",
      ex: `<p>H<sub>2</sub>O e x<sup>2</sup> + y<sup>2</sup></p>`, k: "texto pequeno embaixo|expoente|potência|fórmula química|número elevado" }),
    H({ s: "code", t: "<code>", d: "Trecho de código inline.", x: "<code>let x = 1</code>",
      ex: `<p>Use <code>console.log()</code> para depurar.</p>`, k: "código|monoespaçado|fonte de código" }),
    H({ s: "pre", t: "<pre>", d: "Texto pré-formatado, preservando espaços e quebras.", x: "<pre>...</pre>",
      ex: `<pre><code>function ola() {\n  return 'oi';\n}</code></pre>`, k: "bloco de código|manter espaços|preservar formatação|texto formatado" }),
    H({ s: "kbd", t: "<kbd>", d: "Entrada de teclado (atalhos).", x: "<kbd>Ctrl</kbd>",
      ex: `<p>Salve com <kbd>Ctrl</kbd> + <kbd>S</kbd></p>`, k: "tecla|atalho de teclado|botão do teclado" }),
    H({ s: "samp", t: "<samp>", d: "Saída de um programa.", x: "<samp>saída</samp>", ex: `<p>O terminal mostrou: <samp>Arquivo salvo.</samp></p>`, k: "saída do programa|resultado do terminal|output" }),
    H({ s: "var", t: "<var>", d: "Nome de variável em texto/matemática.", x: "<var>x</var>", ex: `<p>Área = <var>b</var> × <var>h</var></p>`, k: "variável|fórmula|matemática" }),
    H({ s: "blockquote", t: "<blockquote>", d: "Citação longa, em bloco.", x: "<blockquote cite='url'>...</blockquote>",
      ex: `<blockquote cite='https://exemplo.com'>\n  <p>Código é poesia.</p>\n</blockquote>`, k: "citação|recuo de texto|quote|depoimento" }),
    H({ s: "q", t: "<q>", d: "Citação curta, em linha (o navegador coloca aspas).", x: "<q>texto</q>",
      ex: `<p>Ela disse: <q>vamos codar</q>.</p>`, k: "citação curta|aspas automáticas" }),
    H({ s: "cite", t: "<cite>", d: "Título de uma obra citada.", x: "<cite>obra</cite>", ex: `<p>Li <cite>Dom Casmurro</cite> ontem.</p>`, k: "fonte da citação|título do livro|referência" }),
    H({ s: "abbr", t: "<abbr>", d: "Abreviação com explicação ao passar o mouse.", x: "<abbr title='significado'>SIGLA</abbr>",
      ex: `<p><abbr title='HyperText Markup Language'>HTML</abbr> é a base da web.</p>`, k: "sigla|abreviatura|tooltip de sigla|significado" }),
    H({ s: "dfn", t: "<dfn>", d: "Termo sendo definido.", x: "<dfn>termo</dfn>", ex: `<p><dfn>Semântica</dfn> é o significado do conteúdo.</p>`, k: "definição|glossário|termo definido" }),
    H({ s: "time", t: "<time>", d: "Data ou hora legível por máquinas.", x: "<time datetime='2026-09-28'>28 set</time>",
      ex: `<p>Publicado em <time datetime='2026-09-28'>28 de setembro de 2026</time></p>`, k: "data|hora|data de publicação|datetime" }),
    H({ s: "del", t: "<del>", d: "Texto removido do documento.", x: "<del>texto</del>", ex: `<p>Reunião às <del>14h</del> <ins>15h</ins></p>`, k: "texto apagado|removido|riscado|revisão" }),
    H({ s: "ins", t: "<ins>", d: "Texto inserido no documento.", x: "<ins>texto</ins>", ex: `<p>Reunião às <del>14h</del> <ins>15h</ins></p>`, k: "texto adicionado|inserido|sublinhado de revisão" }),
    H({ s: "bdi-bdo", t: "<bdi> / <bdo>", d: "Controlam a direção do texto (esquerda/direita).", x: "<bdo dir='rtl'>texto</bdo>",
      ex: `<p>Usuário <bdi>إيان</bdi>: 3 pontos</p>\n<bdo dir='rtl'>Invertido</bdo>`, k: "texto da direita para esquerda|árabe|hebraico|rtl|direção do texto" }),
    H({ s: "ruby", t: "<ruby> / <rt> / <rp>", d: "Anotação de pronúncia (japonês, chinês).", x: "<ruby>漢<rt>kan</rt></ruby>",
      ex: `<ruby>漢字<rp>(</rp><rt>kanji</rt><rp>)</rp></ruby>`, k: "furigana|pronúncia|japonês|chinês|anotação" }),
    H({ s: "wbr", t: "<wbr>", d: "Sugere onde uma palavra longa pode quebrar.", x: "<wbr>",
      ex: `<p>www.exemplo<wbr>.com.br/pagina<wbr>/muito-longa</p>`, k: "quebrar palavra longa|quebra de url|oportunidade de quebra" }),
    H({ s: "data", t: "<data>", d: "Liga um conteúdo a um valor legível por máquina.", x: "<data value='123'>Produto</data>",
      ex: `<p><data value='398'>Mini fritadeira</data></p>`, k: "valor para máquina|código do produto|dado associado" }),
  ]),

  cat("listas", "Listas", "Listas ordenadas, não ordenadas e de definição.", [
    H({ s: "ul", t: "<ul>", d: "Lista não ordenada (com marcadores).", x: "<ul><li>item</li></ul>",
      ex: `<ul>\n  <li>Maçã</li>\n  <li>Banana</li>\n  <li>Uva</li>\n</ul>`, k: "lista com bolinhas|lista de itens|marcadores|bullet" }),
    H({ s: "ol", t: "<ol>", d: "Lista ordenada (numerada).", x: "<ol start='1' reversed type='1|a|A|i|I'>",
      n: "Atributos: start (número inicial), reversed (contagem regressiva), type (estilo do número).",
      ex: `<ol>\n  <li>Misture</li>\n  <li>Asse</li>\n  <li>Sirva</li>\n</ol>`, k: "lista numerada|passo a passo|ranking|ordem" }),
    H({ s: "li", t: "<li>", d: "Item de lista (dentro de ul, ol ou menu).", x: "<li>item</li>",
      ex: `<ul>\n  <li>Item 1\n    <ul><li>Subitem</li></ul>\n  </li>\n</ul>`, k: "item da lista|sublista|lista aninhada" }),
    H({ s: "dl-dt-dd", t: "<dl> / <dt> / <dd>", d: "Lista de definições (termo + descrição).", x: "<dl><dt>termo</dt><dd>descrição</dd></dl>",
      ex: `<dl>\n  <dt>HTML</dt>\n  <dd>Linguagem de marcação.</dd>\n  <dt>CSS</dt>\n  <dd>Linguagem de estilo.</dd>\n</dl>`, k: "glossário|perguntas e respostas|termo e descrição|dicionário" }),
    H({ s: "menu", t: "<menu>", d: "Lista de comandos/ações (barra de ferramentas).", x: "<menu><li>ação</li></menu>",
      ex: `<menu>\n  <li><button>Copiar</button></li>\n  <li><button>Colar</button></li>\n</menu>`, k: "barra de ferramentas|lista de botões|menu de ações" }),
  ]),
];
