import { H, cat } from "@/content/helpers";

export const htmlB = [
  cat("formularios-avancado", "Formulários Avançados", "Tipos de input, validação e componentes de formulário além do básico.", [
    H({ s: "textarea", t: "<textarea>", d: "Campo de texto de várias linhas.", x: "<textarea rows='4' cols='30'>...</textarea>",
      ex: `<label for='msg'>Mensagem</label>\n<textarea id='msg' rows='5' placeholder='Escreva aqui...'></textarea>`,
      k: "caixa de texto|texto longo|comentário|área de texto|multilinha" }),
    H({ s: "fieldset-legend", t: "<fieldset> / <legend>", d: "Agrupa campos relacionados com um título.", x: "<fieldset><legend>título</legend>...</fieldset>",
      ex: `<fieldset>\n  <legend>Endereço</legend>\n  <input placeholder='Rua'>\n  <input placeholder='Cidade'>\n</fieldset>`,
      k: "agrupar campos|seção do formulário|grupo de inputs" }),
    H({ s: "datalist", t: "<datalist>", d: "Lista de sugestões de autocomplete para um input.", x: "<input list='id'><datalist id='id'>...</datalist>",
      ex: `<input list='linguagens' name='lang'>\n<datalist id='linguagens'>\n  <option value='HTML'>\n  <option value='CSS'>\n  <option value='JavaScript'>\n</datalist>`,
      k: "autocomplete|sugestão de digitação|combobox com sugestões" }),
    H({ s: "output", t: "<output>", d: "Exibe o resultado de um cálculo/interação.", x: "<output name='res'>0</output>",
      ex: `<form oninput='res.value=Number(a.value)+Number(b.value)'>\n  <input id='a' type='number' value='0'> +\n  <input id='b' type='number' value='0'> =\n  <output name='res'>0</output>\n</form>`,
      k: "resultado do cálculo|exibir soma|resultado dinâmico" }),
    H({ s: "progress", t: "<progress>", d: "Barra de progresso de uma tarefa.", x: "<progress value='70' max='100'></progress>",
      ex: `<label for='p'>Enviando arquivo:</label>\n<progress id='p' value='70' max='100'></progress>`, k: "barra de progresso|carregando|percentual concluído" }),
    H({ s: "meter", t: "<meter>", d: "Medidor dentro de uma faixa conhecida (não é progresso).", x: "<meter value='6' min='0' max='10'></meter>",
      ex: `<label for='m'>Uso de disco:</label>\n<meter id='m' value='6' min='0' max='10' low='3' high='8' optimum='2'></meter>`,
      k: "medidor|nível|indicador de quantidade|gauge" }),
    H({ s: "optgroup", t: "<optgroup>", d: "Agrupa opções dentro de um <select>.", x: "<optgroup label='grupo'><option>..</option></optgroup>",
      ex: `<select>\n  <optgroup label='Frutas'>\n    <option>Maçã</option>\n    <option>Banana</option>\n  </optgroup>\n  <optgroup label='Legumes'>\n    <option>Cenoura</option>\n  </optgroup>\n</select>`,
      k: "agrupar opções|categorias no select|select com grupos" }),
    H({ s: "input-checkbox-radio", t: "input type=checkbox / radio", d: "Caixa de marcar e botão de opção única.", x: "<input type='checkbox'>  <input type='radio' name='g'>",
      n: "checkbox: várias opções podem ficar marcadas. radio: dentro do mesmo 'name', só uma opção fica selecionada.",
      ex: `<label><input type='checkbox' name='aceite'> Aceito os termos</label>\n\n<label><input type='radio' name='plano' value='basico'> Básico</label>\n<label><input type='radio' name='plano' value='pro'> Pro</label>`,
      k: "caixa de marcar|marcar opção|botão de rádio|escolher uma opção|múltipla escolha" }),
    H({ s: "input-range", t: "input type=range", d: "Controle deslizante para escolher um número.", x: "<input type='range' min='0' max='100' step='10'>",
      ex: `<label for='vol'>Volume</label>\n<input id='vol' type='range' min='0' max='100' value='50'>`, k: "slider|controle deslizante|barra deslizante|seletor de intervalo" }),
    H({ s: "input-color", t: "input type=color", d: "Seletor de cor nativo do navegador.", x: "<input type='color' value='#2f6fed'>",
      ex: `<label for='cor'>Cor do tema</label>\n<input id='cor' type='color' value='#2f6fed'>`, k: "seletor de cor|escolher cor|color picker|paleta" }),
    H({ s: "input-date", t: "input type=date / time / datetime-local", d: "Seletores nativos de data e hora.", x: "<input type='date'>  <input type='time'>",
      ex: `<label for='nasc'>Nascimento</label>\n<input id='nasc' type='date'>\n\n<label for='hr'>Horário</label>\n<input id='hr' type='time'>`,
      k: "campo de data|calendário|seletor de data|escolher hora|data de nascimento" }),
    H({ s: "input-file", t: "input type=file", d: "Seleciona um ou mais arquivos do dispositivo.", x: "<input type='file' accept='image/*' multiple>",
      ex: `<label for='foto'>Foto de perfil</label>\n<input id='foto' type='file' accept='image/png, image/jpeg'>`,
      k: "upload de arquivo|enviar arquivo|selecionar imagem|anexar arquivo" }),
    H({ s: "input-search-tel", t: "input type=search / tel / url", d: "Tipos que ajustam teclado e validação no mobile.", x: "<input type='search'>  <input type='tel'>  <input type='url'>",
      ex: `<input type='search' placeholder='Buscar...'>\n<input type='tel' placeholder='(84) 99999-9999'>\n<input type='url' placeholder='https://...'>`,
      k: "campo de telefone|campo de busca|campo de link|teclado numérico do telefone" }),
    H({ s: "input-hidden", t: "input type=hidden", d: "Campo invisível enviado junto com o formulário.", x: "<input type='hidden' name='id' value='42'>",
      ex: `<form>\n  <input type='hidden' name='usuarioId' value='42'>\n  <button>Enviar</button>\n</form>`, k: "campo oculto|valor escondido|dado invisível no form" }),
  ]),

  cat("multimidia-avancado", "Mídia Avançada & Interativa", "Canvas, SVG, iframes e conteúdo interativo embutido.", [
    H({ s: "canvas", t: "<canvas>", d: "Área para desenhar gráficos via JavaScript.", x: "<canvas id='c' width='300' height='150'></canvas>",
      ex: `<canvas id='c' width='200' height='100'></canvas>
<script>
const ctx = document.getElementById('c').getContext('2d');
ctx.fillStyle = '#2f6fed';
ctx.fillRect(10, 10, 120, 60);
</script>`, k: "desenhar com javascript|gráfico|jogo em html|pixel" }),
    H({ s: "svg", t: "<svg>", d: "Gráficos vetoriais inline, escaláveis sem perder qualidade.", x: "<svg viewBox='0 0 100 100'>...</svg>",
      ex: `<svg viewBox='0 0 100 100' width='80'>\n  <circle cx='50' cy='50' r='40' fill='#1f9c7a' />\n</svg>`, k: "ícone vetorial|gráfico vetorial|desenho escalável|ícone svg" }),
    H({ s: "iframe", t: "<iframe>", d: "Incorpora outra página dentro da atual.", x: "<iframe src='url' title='...' loading='lazy'></iframe>",
      n: "Sempre defina 'title' para acessibilidade, e 'sandbox' quando o conteúdo for de origem não confiável.",
      ex: `<iframe src='https://www.youtube.com/embed/ID' title='Vídeo' loading='lazy' width='560' height='315'></iframe>`,
      k: "incorporar vídeo|embed|iframe do youtube|janela dentro da página" }),
    H({ s: "embed-object", t: "<embed> / <object>", d: "Incorporam conteúdo externo (PDF, plugins).", x: "<embed src='doc.pdf' type='application/pdf'>",
      ex: `<object data='documento.pdf' type='application/pdf' width='100%' height='500'>\n  <p>Não foi possível exibir o PDF.</p>\n</object>`,
      k: "incorporar pdf|visualizar pdf|plugin|conteúdo externo" }),
    H({ s: "map-area", t: "<map> / <area>", d: "Torna regiões de uma imagem clicáveis (mapa de imagem).", x: "<img usemap='#m'><map name='m'><area shape='circle' coords='...' href='...'></map>",
      ex: `<img src='mapa.png' usemap='#regioes' alt='Mapa'>\n<map name='regioes'>\n  <area shape='rect' coords='0,0,100,100' href='/norte' alt='Norte'>\n</map>`,
      k: "imagem clicável|regiões clicáveis|mapa de imagem|hotspot" }),
    H({ s: "template", t: "<template>", d: "Marcação inerte, clonada via JS quando necessário.", x: "<template id='t'>...</template>",
      ex: `<template id='linha'>\n  <tr><td class='nome'></td></tr>\n</template>\n<script>\n  const clone = document.getElementById('linha').content.cloneNode(true);\n</script>`,
      k: "molde de html|clonar elemento|template javascript" }),
    H({ s: "slot", t: "<slot>", d: "Ponto de inserção de conteúdo em Web Components.", x: "<slot name='titulo'></slot>",
      ex: `<template id='cartao'>\n  <div class='card'><slot name='titulo'></slot></div>\n</template>`, k: "web component|slot de conteúdo|shadow dom" }),
    H({ s: "dialog", t: "<dialog>", d: "Modal/caixa de diálogo nativa do navegador.", x: "<dialog open>...</dialog>",
      ex: `<dialog id='modal'>\n  <p>Confirma a ação?</p>\n  <button onclick=\"modal.close()\">Fechar</button>\n</dialog>\n<button onclick=\"modal.showModal()\">Abrir</button>`,
      k: "modal|popup|caixa de diálogo|janela flutuante" }),
    H({ s: "details-summary", t: "<details> / <summary>", d: "Widget de mostrar/ocultar nativo (sanfona).", x: "<details><summary>título</summary>conteúdo</details>",
      ex: `<details>\n  <summary>Perguntas frequentes</summary>\n  <p>Aqui vai a resposta.</p>\n</details>`, k: "acordeão|sanfona|mostrar mais|expandir|collapse|faq" }),
  ]),

  cat("metadados", "Metadados & Configuração", "O que fica no <head> — SEO, ícones, fontes e configuração da página.", [
    H({ s: "head", t: "<head>", d: "Metadados da página, não visíveis diretamente.", x: "<head>...</head>", np: 1,
      ex: `<head>\n  <meta charset='utf-8'>\n  <title>Minha página</title>\n</head>`, k: "cabeçalho do documento|metadados|configuração da página" }),
    H({ s: "title", t: "<title>", d: "Título exibido na aba do navegador e no Google.", x: "<title>Nome da página</title>",
      ex: `<title>Cheat/dev — referência de HTML, CSS, JS e SQL</title>`, k: "título da aba|título do google|seo título" }),
    H({ s: "meta-charset-viewport", t: "<meta charset> / viewport", d: "Codificação de caracteres e comportamento em telas pequenas.", x: "<meta charset='utf-8'>\n<meta name='viewport' content='width=device-width, initial-scale=1'>",
      ex: `<meta charset='utf-8'>\n<meta name='viewport' content='width=device-width, initial-scale=1'>`, k: "acentos quebrados|responsivo mobile|viewport|utf-8" }),
    H({ s: "meta-description", t: "meta name=description", d: "Resumo da página exibido nos resultados de busca.", x: "<meta name='description' content='...'>",
      ex: `<meta name='description' content='Referência rápida de HTML, CSS, JS e SQL com exemplos.'>`, k: "seo descrição|resumo do google|meta description" }),
    H({ s: "og-tags", t: "Open Graph (og:*)", d: "Controlam o preview ao compartilhar o link (WhatsApp, redes sociais).", x: "<meta property='og:title' content='...'>",
      ex: `<meta property='og:title' content='Meu site'>\n<meta property='og:description' content='Descrição do site'>\n<meta property='og:image' content='https://site.com/capa.jpg'>\n<meta property='og:url' content='https://site.com'>`,
      k: "preview do link|compartilhar no whatsapp|imagem de compartilhamento|og image" }),
    H({ s: "link-css", t: "<link rel=stylesheet>", d: "Importa um arquivo CSS externo.", x: "<link rel='stylesheet' href='estilo.css'>",
      ex: `<link rel='stylesheet' href='/css/estilo.css'>`, k: "importar css|vincular css|arquivo de estilo externo" }),
    H({ s: "link-icon", t: "<link rel=icon>", d: "Define o favicon da página.", x: "<link rel='icon' href='favicon.svg' type='image/svg+xml'>",
      ex: `<link rel='icon' href='/favicon.svg' type='image/svg+xml'>\n<link rel='apple-touch-icon' href='/icon-180.png'>`, k: "favicon|ícone da aba|ícone do site" }),
    H({ s: "script-tag", t: "<script>", d: "Insere ou vincula JavaScript.", x: "<script src='app.js' defer></script>",
      n: "'defer' baixa em paralelo e executa após o HTML ser parseado — normalmente a melhor opção para scripts que mexem no DOM.",
      ex: `<script src='/js/app.js' defer></script>\n<script>\n  console.log('inline');\n</script>`, k: "importar javascript|vincular js|script externo|defer async" }),
    H({ s: "noscript", t: "<noscript>", d: "Conteúdo exibido só se JavaScript estiver desabilitado.", x: "<noscript>...</noscript>",
      ex: `<noscript>\n  <p>Ative o JavaScript para usar este site.</p>\n</noscript>`, k: "javascript desabilitado|fallback sem js" }),
    H({ s: "base", t: "<base>", d: "Define a URL base para todos os links relativos da página.", x: "<base href='https://site.com/app/'>",
      ex: `<head>\n  <base href='https://meusite.com/blog/'>\n</head>\n<a href='post-1'>...</a> <!-- vira /blog/post-1 -->`, k: "url base|caminho relativo|base href" }),
  ]),
];
