import { Q, cat, type Raw } from "@/content/helpers";

/* Recursos exclusivos do PostgreSQL, que é também o banco do Supabase.
   Cada comando traz uma consulta que roda num Postgres de verdade dentro do navegador (PGlite). */

type PgDemo = { db: "loja" | "escola" | "rh"; pg: string };
export const SQL_PG_ONLY: Record<string, PgDemo> = {};

const P = (db: PgDemo["db"], pg: string, o: Raw) => {
  SQL_PG_ONLY[o.s] = { db, pg };
  return Q({ ...o, ex: o.ex ?? pg });
};

export const sqlD = [
  cat("postgres-supabase", "PostgreSQL & Supabase", "O que o Supabase usa por baixo: tipos modernos, JSONB, arrays, triggers e segurança por linha (RLS). Tudo roda num Postgres real no seu navegador.", [
    P("loja", `CREATE TABLE notas (\n  id         uuid        DEFAULT gen_random_uuid() PRIMARY KEY,   -- id único universal, gerado pelo banco\n  titulo     text        NOT NULL,\n  criado_em  timestamptz DEFAULT now()                           -- data e hora COM fuso horário\n);\n\nINSERT INTO notas (titulo) VALUES ('Primeira nota'), ('Segunda nota') RETURNING id, titulo, criado_em;`,
      { s: "uuid-timestamptz", t: "uuid e timestamptz (o padrão do Supabase)", d: "Ids universais e datas com fuso horário: as duas escolhas que quase todo projeto Supabase faz.", x: "id uuid DEFAULT gen_random_uuid() PRIMARY KEY,\ncriado_em timestamptz DEFAULT now()",
        n: "Nas tabelas criadas pelo Supabase, o id costuma ser uuid (128 bits, gerado por gen_random_uuid()) em vez de um inteiro sequencial. Vantagens: não revela quantos registros existem, pode ser gerado fora do banco (no app) e não colide entre sistemas. Custo: ocupa mais espaço e não é legível.\ntimestamptz guarda um instante absoluto (internamente em UTC) e converte para o fuso do cliente ao exibir. Prefira-o a timestamp (sem fuso) para qualquer coisa que aconteceu em um momento real: criado_em, atualizado_em, agendamentos. now() devolve o instante atual.\nOutra regra de ouro do Postgres: use text em vez de varchar(n), a não ser que precise limitar o tamanho. Não há diferença de desempenho.",
        u: "Chaves primárias expostas na URL ou na API|Sistemas com mais de um banco/serviço", a: "Usar timestamp sem fuso para eventos reais (vira bagunça com horário de verão e usuários em vários fusos)", r: "sql/modelagem/tipos-de-dados|sql/dialetos/autoincrement", k: "uuid|gen_random_uuid|timestamptz|data com fuso horário|id universal|supabase tabela padrão|chave primária uuid|now()" }),
    P("loja", `CREATE TABLE eventos (id serial PRIMARY KEY, dados jsonb);\nINSERT INTO eventos (dados) VALUES\n  ('{"tipo":"compra","valor":199.9,"cliente":{"nome":"Ana","vip":true},"tags":["natal","oferta"]}'),\n  ('{"tipo":"clique","pagina":"/home","tags":["a"]}'),\n  ('{"tipo":"compra","valor":59.9,"cliente":{"nome":"Bruno","vip":false},"tags":["oferta"]}');\n\n-- @>  "contém":  quem tem esse pedaço de JSON?\nSELECT id, dados ->> 'tipo' AS tipo FROM eventos WHERE dados @> '{"tipo":"compra"}';\n\n-- Caminho aninhado + conversão de tipo\nSELECT dados -> 'cliente' ->> 'nome' AS cliente, (dados ->> 'valor')::numeric AS valor\nFROM eventos WHERE (dados -> 'cliente' ->> 'vip')::boolean;\n\n-- ? testa se a chave/valor existe no array\nSELECT id FROM eventos WHERE dados -> 'tags' ? 'natal';\n\n-- Índice GIN: acelera @>, ? e ?| em tabelas grandes\nCREATE INDEX idx_eventos_dados ON eventos USING gin (dados);`,
      { s: "jsonb-operadores", t: "JSONB: operadores e índice GIN", d: "Consultar e indexar documentos JSON dentro do Postgres, a base de colunas flexíveis no Supabase.", x: "dados -> 'a'  (JSON)  ·  dados ->> 'a'  (texto)  ·  dados @> '{...}'  ·  dados ? 'chave'",
        n: "JSONB guarda JSON em formato binário: mais rápido de consultar e indexável (JSON simples é só texto). Operadores principais: -> devolve JSON (pode encadear), ->> devolve TEXTO (converta com ::numeric, ::boolean...), @> testa se contém um pedaço de JSON, ? testa se uma chave existe, #> navega por um caminho em array.\nUm índice GIN (USING gin) torna @> e ? rápidos mesmo com milhões de linhas. Atualizações: jsonb_set() altera um campo, || mescla objetos.\nQuando usar: dados com formato variável (configurações, eventos, respostas de APIs). Para campos que você filtra, ordena e junta o tempo todo, colunas normais continuam melhores. Este é o equivalente do MongoDB dentro do Postgres.",
        u: "Preferências do usuário, metadados, payloads de webhook", a: "Guardar TUDO em JSONB e perder tipagem, chaves estrangeiras e validações", r: "sql/json-recursao/json-no-sql", k: "jsonb|operador contém|json no postgres|supabase json|índice gin|campo flexível|arrow operator|->>" }),
    P("loja", `-- Colunas que guardam LISTAS (array de texto)\nCREATE TABLE posts (id serial PRIMARY KEY, titulo text, tags text[]);\nINSERT INTO posts (titulo, tags) VALUES\n  ('Guia de JOIN', ARRAY['sql','iniciante']),\n  ('Flexbox do zero', ARRAY['css','iniciante']),\n  ('Window functions', ARRAY['sql','avancado']);\n\n-- Tem a tag? (ANY compara com cada elemento)\nSELECT titulo FROM posts WHERE 'sql' = ANY(tags);\n\n-- Tem TODAS estas tags?  @> = "contém"\nSELECT titulo FROM posts WHERE tags @> ARRAY['sql','iniciante'];\n\n-- unnest "desmonta" o array em linhas; array_agg faz o caminho inverso\nSELECT tag, COUNT(*) AS posts FROM posts, unnest(tags) AS tag GROUP BY tag ORDER BY posts DESC, tag;`,
      { s: "arrays-postgres", t: "Arrays: ANY, @>, unnest e array_agg", d: "Colunas que guardam listas e as funções para consultá-las.", x: "tags text[]  ·  'x' = ANY(tags)  ·  tags @> ARRAY['a']  ·  unnest(tags)  ·  array_agg(col)",
        n: "O Postgres tem tipos de array nativos (text[], int[]...). Servem para listas curtas e simples, como tags, papéis e permissões, evitando uma tabela associativa quando não há dados extras no relacionamento.\nANY(array) compara um valor com cada elemento; @> testa se o array contém todos os valores dados; && testa se há interseção. unnest(array) transforma o array em linhas (para contar, agrupar, juntar). array_agg(coluna) faz o inverso, agregando linhas em um array.\nLimitação: sem chave estrangeira entre o elemento do array e outra tabela. Se precisar de integridade referencial ou metadados do vínculo (quem, quando), use tabela associativa.",
        u: "Tags, permissões, listas curtas|Resultados que você quer devolver agrupados em uma só linha", a: "Arrays gigantes ou que precisam de integridade (use tabela relacionada)", r: "sql/modelagem/relacionamento-nn|sql/agregacao-avancada/group-concat", k: "array no postgres|lista em coluna|any|unnest|array_agg|tags em array|text[]|coluna com várias tags" }),
    P("loja", `-- ILIKE: LIKE sem diferenciar maiúsculas/minúsculas (exclusivo do Postgres)\nSELECT nome FROM clientes WHERE nome ILIKE '%AN%';\n\n-- ~* : expressão regular, sem diferenciar maiúsculas\nSELECT nome, email FROM clientes WHERE email ~* '^[a-d].*@gmail\\.com$';\n\n-- Extrair e limpar texto\nSELECT nome,\n  split_part(email, '@', 2)          AS provedor,\n  regexp_replace(nome, '\\s+.*$', '') AS primeiro_nome,\n  initcap(lower('mARIA dA sILVA'))   AS titulo_maiusculas\nFROM clientes WHERE email IS NOT NULL LIMIT 5;`,
      { s: "ilike-regex", t: "ILIKE e expressões regulares (~)", d: "Busca sem diferenciar caixa e padrões avançados com regex, direto no Postgres.", x: "col ILIKE '%texto%'  ·  col ~* 'regex'  ·  regexp_replace(col, 'regex', 'novo')",
        n: "No Postgres, LIKE diferencia maiúsculas de minúsculas (no MySQL e SQL Server isso depende da 'collation'). Para ignorar a caixa use ILIKE. Para padrões mais complexos há os operadores de regex: ~ (casa, diferencia caixa), ~* (casa, ignora caixa), !~ e !~* (não casa).\nFunções úteis: split_part(texto, separador, posição), regexp_replace, regexp_matches, initcap (Primeira Maiúscula), left/right e position.\nDesempenho: ILIKE '%x%' não usa índice comum em tabelas grandes; para busca de texto séria use a extensão pg_trgm (índice trigram) ou busca full-text (to_tsvector / to_tsquery), ambas disponíveis no Supabase.",
        u: "Busca de usuário sem se preocupar com caixa|Validar ou limpar textos", r: "sql/consultas/like|sql/textos-numeros/funcoes-texto", k: "ilike|busca sem diferenciar maiúsculas|regex no sql|expressão regular|case insensitive|postgres texto|buscar nome ignorando caixa" }),
    P("loja", `-- Para CADA cliente, o seu pedido de maior valor (top 1 por grupo)\nSELECT c.nome, p.id AS pedido, p.total\nFROM clientes c\nCROSS JOIN LATERAL (\n  SELECT id, total FROM pedidos\n  WHERE cliente_id = c.id          -- LATERAL: a subconsulta enxerga a linha de c\n  ORDER BY total DESC\n  LIMIT 1\n) p\nORDER BY p.total DESC;\n\n-- LEFT JOIN LATERAL mantém também os clientes sem pedido\n-- SELECT c.nome, p.id FROM clientes c LEFT JOIN LATERAL (...) p ON true;`,
      { s: "lateral-join", t: "JOIN LATERAL (top N por grupo, do jeito Postgres)", d: "Uma subconsulta que pode usar colunas da tabela à esquerda, uma vez por linha.", x: "FROM a CROSS JOIN LATERAL (SELECT ... WHERE x = a.id LIMIT 1) b",
        n: "Normalmente uma subconsulta no FROM não enxerga as outras tabelas. Com LATERAL ela enxerga, e é executada para cada linha da tabela à esquerda. O resultado clássico é 'os N últimos/maiores de cada grupo' de forma simples e rápida (com índice em (cliente_id, total)).\nÉ a alternativa elegante ao ROW_NUMBER() com subconsulta externa. Use CROSS JOIN LATERAL (ou JOIN LATERAL ... ON true) para descartar quem não tem linhas, e LEFT JOIN LATERAL ... ON true para mantê-los.\nExistem equivalentes em outros bancos (CROSS APPLY no SQL Server, LATERAL no MySQL 8.0.14+), mas o SQLite não tem.",
        r: "sql/agregacao-avancada/top-n-por-grupo|sql/subqueries-conjuntos/subquery-correlacionada", k: "lateral|top n por grupo|último pedido de cada cliente|cross apply|maior de cada grupo postgres|join lateral" }),
    P("loja", `-- CTE que ALTERA dados: apaga e, na mesma instrução, arquiva o que foi apagado\nCREATE TABLE pedidos_arquivo (LIKE pedidos);\n\n-- Um pedido cancelado e sem itens, para termos o que arquivar:\nINSERT INTO pedidos (cliente_id, data, status, total) VALUES (1, '2024-12-01', 'cancelado', 0);\n\nWITH removidos AS (\n  DELETE FROM pedidos\n  WHERE status = 'cancelado'\n    AND NOT EXISTS (SELECT 1 FROM itens_pedido i WHERE i.pedido_id = pedidos.id)   -- sem itens ligados\n  RETURNING *\n)\nINSERT INTO pedidos_arquivo SELECT * FROM removidos;\n\nSELECT COUNT(*) AS arquivados FROM pedidos_arquivo;\nSELECT COUNT(*) AS restantes FROM pedidos;`,
      { s: "cte-gravavel", t: "CTE com DELETE/UPDATE ... RETURNING (mover linhas)", d: "Apaga ou altera linhas e usa o resultado na mesma instrução, de forma atômica.", x: "WITH r AS (DELETE FROM t WHERE ... RETURNING *) INSERT INTO arquivo SELECT * FROM r;",
        n: "No Postgres, uma CTE pode conter INSERT, UPDATE ou DELETE com RETURNING, e o resultado alimenta o comando principal. Tudo acontece numa única instrução atômica, sem risco de apagar sem arquivar (ou o contrário).\nPadrões comuns: mover linhas para uma tabela de arquivo, inserir em duas tabelas relacionadas devolvendo o id gerado na primeira, e fazer fila de tarefas (UPDATE ... RETURNING com SKIP LOCKED).\nNo exemplo, só são arquivados os pedidos cancelados que não têm itens, para não violar a chave estrangeira.",
        r: "sql/dml-detalhado/returning|sql/views-cte/with-cte", k: "mover linhas entre tabelas|arquivar dados|delete returning|cte que apaga|atomico|insert select delete|fila de tarefas" }),
    P("loja", `-- View materializada: o resultado fica GUARDADO (rápido), e você decide quando atualizar\nCREATE MATERIALIZED VIEW vendas_por_mes AS\nSELECT to_char(data, 'YYYY-MM') AS mes, COUNT(*) AS pedidos, SUM(total) AS receita\nFROM pedidos\nWHERE status = 'pago'\nGROUP BY 1;\n\nSELECT * FROM vendas_por_mes ORDER BY mes;\n\n-- Chegou um pedido novo...\nINSERT INTO pedidos (cliente_id, data, status, total) VALUES (1, '2024-12-10', 'pago', 1000);\n\n-- ...a view guardada NÃO muda sozinha:\nSELECT SUM(receita) AS receita_antes FROM vendas_por_mes;\n\nREFRESH MATERIALIZED VIEW vendas_por_mes;   -- recalcula\nSELECT SUM(receita) AS receita_depois FROM vendas_por_mes;`,
      { s: "view-materializada", t: "View materializada (MATERIALIZED VIEW)", d: "Uma view cujo resultado fica gravado em disco: leituras instantâneas, atualização sob demanda.", x: "CREATE MATERIALIZED VIEW nome AS SELECT ...;\nREFRESH MATERIALIZED VIEW nome;",
        n: "Uma view comum recalcula a consulta toda vez. Uma view materializada executa uma vez e guarda o resultado como uma tabela, ideal para relatórios e painéis pesados. O preço é a defasagem: os dados só se atualizam quando você manda (REFRESH), normalmente por um job agendado (pg_cron no Supabase).\nREFRESH MATERIALIZED VIEW CONCURRENTLY atualiza sem bloquear as leituras (exige um índice único na view). Dá para criar índices sobre ela como em qualquer tabela.\nO SQLite e o MySQL não têm views materializadas nativas.",
        u: "Dashboards e relatórios pesados|Agregações que mudam pouco", a: "Quando o usuário precisa ver o dado em tempo real", r: "sql/views-cte/create-view|sql/performance-sql/indice-composto", k: "view materializada|materialized view|relatório rápido|cache de consulta|refresh|painel pesado|pg_cron" }),
    P("loja", `-- Trigger: função que roda sozinha a cada UPDATE (padrão do Supabase para "atualizado_em")\nALTER TABLE produtos ADD COLUMN atualizado_em timestamptz DEFAULT now();\n\nCREATE FUNCTION marcar_atualizacao() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n  NEW.atualizado_em := now();   -- NEW = a linha com os valores novos\n  RETURN NEW;\nEND;\n$$;\n\nCREATE TRIGGER trg_produtos_atualizado\nBEFORE UPDATE ON produtos\nFOR EACH ROW EXECUTE FUNCTION marcar_atualizacao();\n\nUPDATE produtos SET preco = preco + 1 WHERE id = 1;\n\nSELECT id, nome, preco, atualizado_em IS NOT NULL AS carimbado FROM produtos WHERE id IN (1, 2);`,
      { s: "trigger-atualizado-em", t: "Triggers e funções PL/pgSQL", d: "Código que o banco executa automaticamente antes ou depois de INSERT, UPDATE e DELETE.", x: "CREATE FUNCTION f() RETURNS trigger LANGUAGE plpgsql AS $$ ... $$;\nCREATE TRIGGER t BEFORE UPDATE ON tabela FOR EACH ROW EXECUTE FUNCTION f();",
        n: "Um trigger liga uma função a um evento da tabela. O uso mais comum no Supabase é manter atualizado_em automaticamente (como no exemplo), mas também serve para validações complexas, auditoria (gravar quem mudou o quê) e criar o perfil de um usuário quando ele se cadastra.\nNo corpo da função PL/pgSQL, NEW é a linha nova e OLD a antiga. BEFORE permite alterar NEW; AFTER é para efeitos colaterais. FOR EACH ROW roda por linha afetada.\nFunções criadas no Postgres podem ser chamadas pelo supabase-js com .rpc('nome', {args}), o que transforma o banco numa API de lógica de negócio.\nCuidado: lógica demais escondida em triggers dificulta depuração; documente e use com moderação.",
        a: "Colocar regras de negócio complexas e difíceis de testar dentro de triggers", r: "sql/views-cte/create-view|sql/dml-detalhado/returning", k: "trigger|atualizado_em automático|updated_at|plpgsql|função no banco|rpc supabase|auditoria|gatilho do banco|stored procedure" }),
    P("loja", `-- 1) Simulação do ambiente Supabase: função auth.uid() e o papel "authenticated"\nCREATE SCHEMA auth;\nCREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS\n  $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;\nCREATE ROLE authenticated NOLOGIN;\nGRANT USAGE ON SCHEMA auth TO authenticated;\n\n-- 2) Tabela de tarefas: cada linha tem um dono (user_id)\nCREATE TABLE tarefas (id serial PRIMARY KEY, user_id uuid NOT NULL, titulo text);\nINSERT INTO tarefas (user_id, titulo) VALUES\n  ('11111111-1111-1111-1111-111111111111', 'Tarefa da Ana'),\n  ('11111111-1111-1111-1111-111111111111', 'Outra tarefa da Ana'),\n  ('22222222-2222-2222-2222-222222222222', 'Tarefa do Bruno');\n\n-- 3) Liga a segurança por linha e cria a POLICY: só vê o que é seu\nALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;\nGRANT SELECT ON tarefas TO authenticated;\nCREATE POLICY "ver só as próprias tarefas" ON tarefas\n  FOR SELECT TO authenticated\n  USING (user_id = auth.uid());\n\n-- 4) Testando: agora você é a Ana (o Supabase faz isso com o JWT do login)\nSET ROLE authenticated;\nSELECT set_config('request.jwt.claim.sub', '11111111-1111-1111-1111-111111111111', false);\nSELECT 'Ana vê:' AS quem, titulo FROM tarefas;\n\n-- Agora é o Bruno\nSELECT set_config('request.jwt.claim.sub', '22222222-2222-2222-2222-222222222222', false);\nSELECT 'Bruno vê:' AS quem, titulo FROM tarefas;\n\nRESET ROLE;`,
      { s: "rls-policies", t: "Row Level Security (RLS) e policies do Supabase", d: "Regras no banco que decidem quais LINHAS cada usuário pode ver ou alterar.", x: "ALTER TABLE t ENABLE ROW LEVEL SECURITY;\nCREATE POLICY nome ON t FOR SELECT TO authenticated USING (user_id = auth.uid());",
        n: "No Supabase, o navegador do usuário conversa direto com o banco pela API. O que impede um usuário de ler os dados de outro é o RLS: com ele ligado, TODA consulta passa por policies que filtram as linhas. Sem RLS, qualquer pessoa com a chave pública (anon) poderia ler a tabela inteira. Por isso o Supabase avisa quando uma tabela pública está sem RLS.\nUma policy tem: o comando (SELECT, INSERT, UPDATE, DELETE ou ALL), o papel (anon, authenticated), USING (quais linhas existentes são visíveis/alteráveis) e WITH CHECK (quais linhas novas são aceitas em INSERT/UPDATE). auth.uid() devolve o id do usuário logado, lido do JWT.\nRLS ligado e NENHUMA policy = ninguém acessa (a negação é o padrão). O papel service_role do Supabase ignora o RLS: nunca o exponha no navegador.\nO exemplo recria o ambiente: define auth.uid() a partir de uma configuração (é assim que o Supabase passa o JWT) e alterna entre usuários. Nada disso exige o serviço Supabase; é Postgres puro.",
        u: "Todo app Supabase com dados por usuário|Multi-tenant (um cliente não pode ver o outro)", a: "Deixar uma tabela com dados pessoais sem RLS|Usar a service_role no código do navegador", r: "sql/seguranca-sql/grant-revoke|sql/seguranca-sql/sql-injection", k: "rls|row level security|policy|supabase segurança|auth.uid|cada usuário vê só os seus dados|create policy|multi tenant|proteger tabela supabase" }),
    Q({ s: "supabase-js-para-sql", t: "supabase-js ⇄ SQL (tradutor)", d: "Cada método do supabase-js e o SQL que ele gera por baixo, lado a lado.", x: "supabase.from('tabela').select('*').eq('campo', valor)  ⇄  SELECT * FROM tabela WHERE campo = valor;",
      n: "O supabase-js monta SQL (via PostgREST) a partir de métodos encadeados. Saber o SQL equivalente ajuda a pensar em índices, joins e RLS, e a depurar lentidão. Abaixo, os pares mais usados, com a consulta equivalente que você pode rodar no banco de exemplo (aba Loja).\n.select('*, pedidos(*)') faz um JOIN pela chave estrangeira e devolve os pedidos aninhados dentro de cada cliente. .single() espera exatamente uma linha (erro se vierem 0 ou 2+). Filtros: eq (=), neq (<>), gt/gte/lt/lte, like/ilike, in, is (null) e or(). .order(), .limit() e .range(de, até) paginam.\ninsert/update/delete aceitam .select() no final para devolver as linhas afetadas (é o RETURNING). upsert usa ON CONFLICT. rpc('nome') chama uma função do Postgres.",
      ex: `// 1) Listar com filtro e ordem\nconst { data } = await supabase.from('produtos').select('nome, preco').eq('categoria', 'Livros').order('preco', { ascending: false }).limit(5);\n-- SQL: SELECT nome, preco FROM produtos WHERE categoria = 'Livros' ORDER BY preco DESC LIMIT 5;\n---\n// 2) Relacionamento: cliente com seus pedidos\nconst { data } = await supabase.from('clientes').select('nome, pedidos(id, total)');\n-- SQL: SELECT c.nome, p.id, p.total FROM clientes c LEFT JOIN pedidos p ON p.cliente_id = c.id;\n---\n// 3) Inserir e devolver a linha criada\nconst { data } = await supabase.from('clientes').insert({ nome: 'Ana', estado: 'RN' }).select().single();\n-- SQL: INSERT INTO clientes (nome, estado) VALUES ('Ana', 'RN') RETURNING *;\n---\n// 4) Atualizar\nawait supabase.from('produtos').update({ estoque: 0 }).eq('id', 5);\n-- SQL: UPDATE produtos SET estoque = 0 WHERE id = 5;\n---\n// 5) Filtro OU, texto sem caixa e paginação (itens 10 a 19)\nawait supabase.from('clientes').select('*').or('estado.eq.RN,estado.eq.PE').ilike('nome', '%ana%').range(10, 19);\n-- SQL: SELECT * FROM clientes WHERE (estado = 'RN' OR estado = 'PE') AND nome ILIKE '%ana%' LIMIT 10 OFFSET 10;\n---\n// 6) Upsert e chamada de função\nawait supabase.from('contador').upsert({ id: 1, total: 5 });\n-- SQL: INSERT INTO contador (id, total) VALUES (1, 5) ON CONFLICT (id) DO UPDATE SET total = excluded.total;\nawait supabase.rpc('marcar_atualizacao', { arg: 1 });\n-- SQL: SELECT * FROM marcar_atualizacao(1);`,
      u: "Aprender a pensar em SQL mesmo usando a biblioteca|Depurar consultas lentas ou resultados inesperados", a: "Esquecer que o RLS também filtra os resultados do supabase-js: um select vazio pode ser política, não bug", r: "sql/postgres-supabase/rls-policies|sql/dml-detalhado/returning|sql/dml-detalhado/upsert", k: "supabase js|supabase select|supabase eq|supabase insert|supabase relacionamento|from select eq|tradutor supabase sql|postgrest|supabase query" }),
  ]),
];
