import { SQL_EXERCISES } from "@/content/sql-exercises";
import type { DbId } from "@/lib/sqlDbs";

export type Level = "iniciante" | "intermediário" | "avançado" | "chefe";
export type Lang = "html" | "css" | "js" | "sql";
export type Code = { html: string; css: string; js: string };
export type Test = { name: string; /** expressão JavaScript avaliada dentro da página do desafio; verdadeiro = passou (pode ser uma Promise) */ check: string };

export type WebChallenge = { kind: "web"; id: string; lang: "html" | "css" | "js"; level: Level; title: string; brief: string; hint: string; starter: Code; solution: Code; tests: Test[] };
export type SqlChallenge = { kind: "sql"; id: string; lang: "sql"; level: Level; title: string; brief: string; hint: string; db: DbId; solution: string };
export type Challenge = WebChallenge | SqlChallenge;

export const LEVEL_XP: Record<Level, number> = { "iniciante": 10, "intermediário": 25, "avançado": 50, "chefe": 100 };
export const LEVELS: Level[] = ["iniciante", "intermediário", "avançado", "chefe"];

const E: Code = { html: "", css: "", js: "" };
const page = (body: string, head = "") => `<!DOCTYPE html>\n<html lang="pt-BR">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Minha página</title>${head}\n</head>\n<body>\n${body}\n</body>\n</html>`;
const q = (sel: string) => `document.querySelector('${sel}')`;
const cs = (sel: string, prop: string) => `getComputedStyle(${q(sel)}).${prop}`;
const rect = (sel: string) => `${q(sel)}.getBoundingClientRect()`;

/* ============================== JAVASCRIPT ============================== */
const js = (id: string, level: Level, title: string, brief: string, hint: string, starter: string, solution: string, tests: Test[]): WebChallenge => ({
  kind: "web", id, lang: "js", level, title, brief, hint, starter: { ...E, js: starter }, solution: { ...E, js: solution }, tests,
});

const JS: WebChallenge[] = [
  js("js-soma", "iniciante", "Função soma", "Escreva a função soma(a, b) que devolve a soma dos dois números.", "function soma(a, b) { return ... }  Não esqueça do return.",
    "function soma(a, b) {\n  // seu código aqui\n}", "function soma(a, b) {\n  return a + b;\n}",
    [{ name: "soma(2, 3) vale 5", check: "soma(2, 3) === 5" }, { name: "soma(-1, 1) vale 0", check: "soma(-1, 1) === 0" }, { name: "soma(0.5, 0.25) vale 0.75", check: "soma(0.5, 0.25) === 0.75" }]),
  js("js-par", "iniciante", "Par ou ímpar", "Escreva ehPar(n) que devolve true se o número for par e false se for ímpar.", "O operador % devolve o resto da divisão. Um número par tem resto 0 ao dividir por 2.",
    "function ehPar(n) {\n  // seu código aqui\n}", "function ehPar(n) {\n  return n % 2 === 0;\n}",
    [{ name: "ehPar(4) é true", check: "ehPar(4) === true" }, { name: "ehPar(7) é false", check: "ehPar(7) === false" }, { name: "ehPar(0) é true", check: "ehPar(0) === true" }, { name: "ehPar(-2) é true", check: "ehPar(-2) === true" }]),
  js("js-inverter", "iniciante", "Inverter texto", "Escreva inverter(texto) que devolve o texto de trás para frente. Exemplo: inverter('abc') devolve 'cba'.", "Transforme em array com split(''), inverta com reverse() e junte com join('').",
    "function inverter(texto) {\n  // seu código aqui\n}", "function inverter(texto) {\n  return texto.split('').reverse().join('');\n}",
    [{ name: "inverter('abc') é 'cba'", check: "inverter('abc') === 'cba'" }, { name: "inverter('') é ''", check: "inverter('') === ''" }, { name: "inverter('JS rocks') é 'skcor SJ'", check: "inverter('JS rocks') === 'skcor SJ'" }]),
  js("js-maior", "iniciante", "Maior da lista", "Escreva maiorDaLista(lista) que devolve o maior número do array.", "Percorra o array guardando o maior valor visto, ou use Math.max(...lista).",
    "function maiorDaLista(lista) {\n  // seu código aqui\n}", "function maiorDaLista(lista) {\n  return Math.max(...lista);\n}",
    [{ name: "[3, 9, 2] → 9", check: "maiorDaLista([3, 9, 2]) === 9" }, { name: "[-5, -1, -9] → -1", check: "maiorDaLista([-5, -1, -9]) === -1" }, { name: "[7] → 7", check: "maiorDaLista([7]) === 7" }]),
  js("js-vogais", "intermediário", "Contar vogais", "Escreva contarVogais(texto) que conta quantas vogais (a, e, i, o, u, maiúsculas ou minúsculas) existem no texto. Ignore acentos: só as letras simples.", "Use uma expressão regular com a flag i e g: texto.match(/[aeiou]/gi) devolve null se não houver nenhuma.",
    "function contarVogais(texto) {\n  // seu código aqui\n}", "function contarVogais(texto) {\n  return (texto.match(/[aeiou]/gi) || []).length;\n}",
    [{ name: "'banana' → 3", check: "contarVogais('banana') === 3" }, { name: "'AEIOU' → 5", check: "contarVogais('AEIOU') === 5" }, { name: "'rhythm' → 0", check: "contarVogais('rhythm') === 0" }, { name: "'' → 0", check: "contarVogais('') === 0" }]),
  js("js-soma-pares", "intermediário", "Soma dos pares", "Escreva somaDosPares(lista) que soma apenas os números pares do array. Use filter e reduce.", "lista.filter(n => n % 2 === 0).reduce((acc, n) => acc + n, 0)",
    "function somaDosPares(lista) {\n  // seu código aqui\n}", "function somaDosPares(lista) {\n  return lista.filter((n) => n % 2 === 0).reduce((acc, n) => acc + n, 0);\n}",
    [{ name: "[1, 2, 3, 4] → 6", check: "somaDosPares([1, 2, 3, 4]) === 6" }, { name: "[1, 3, 5] → 0", check: "somaDosPares([1, 3, 5]) === 0" }, { name: "[] → 0", check: "somaDosPares([]) === 0" }, { name: "[10, -4, 7] → 6", check: "somaDosPares([10, -4, 7]) === 6" }]),
  js("js-duplicados", "intermediário", "Remover duplicados", "Escreva removerDuplicados(lista) que devolve um novo array sem repetições, mantendo a ordem da primeira aparição.", "Um Set guarda valores únicos: [...new Set(lista)] já mantém a ordem de inserção.",
    "function removerDuplicados(lista) {\n  // seu código aqui\n}", "function removerDuplicados(lista) {\n  return [...new Set(lista)];\n}",
    [{ name: "[1, 2, 2, 3, 1] → [1, 2, 3]", check: "JSON.stringify(removerDuplicados([1, 2, 2, 3, 1])) === '[1,2,3]'" }, { name: "mantém a ordem", check: "JSON.stringify(removerDuplicados(['b', 'a', 'b'])) === '[\"b\",\"a\"]'" }, { name: "não altera o array original", check: "(() => { const a = [1, 1]; removerDuplicados(a); return a.length === 2; })()" }]),
  js("js-palindromo", "intermediário", "Palíndromo", "Escreva ehPalindromo(texto): true se o texto lê igual de trás para frente, ignorando maiúsculas, espaços e pontuação. Exemplo: 'Socorram-me, subi no onibus em Marrocos'.", "Normalize: toLowerCase(), remova tudo que não é letra com replace(/[^a-z0-9]/g, ''), e compare com a versão invertida.",
    "function ehPalindromo(texto) {\n  // seu código aqui\n}", "function ehPalindromo(texto) {\n  const t = texto.toLowerCase().replace(/[^a-z0-9]/g, '');\n  return t === t.split('').reverse().join('');\n}",
    [{ name: "'arara' é palíndromo", check: "ehPalindromo('arara') === true" }, { name: "'banana' não é", check: "ehPalindromo('banana') === false" }, { name: "ignora caixa e espaços", check: "ehPalindromo('A base do teto desaba') === true" }, { name: "ignora pontuação", check: "ehPalindromo('Socorram-me, subi no onibus em Marrocos!') === true" }]),
  js("js-agrupar", "avançado", "Agrupar por chave", "Escreva agruparPor(lista, chave): recebe um array de objetos e devolve um objeto agrupando-os pelo valor da propriedade `chave`. Exemplo: agruparPor([{t:'a'},{t:'b'},{t:'a'}], 't') → { a: [{t:'a'},{t:'a'}], b: [{t:'b'}] }.", "Use reduce com um objeto como acumulador; crie o array do grupo se ainda não existir: (acc[k] ??= []).push(item).",
    "function agruparPor(lista, chave) {\n  // seu código aqui\n}", "function agruparPor(lista, chave) {\n  return lista.reduce((acc, item) => {\n    (acc[item[chave]] ??= []).push(item);\n    return acc;\n  }, {});\n}",
    [{ name: "agrupa por categoria", check: "(() => { const r = agruparPor([{c:'x',n:1},{c:'y',n:2},{c:'x',n:3}], 'c'); return Object.keys(r).length === 2 && r.x.length === 2 && r.y[0].n === 2; })()" }, { name: "lista vazia → objeto vazio", check: "JSON.stringify(agruparPor([], 'c')) === '{}'" }, { name: "mantém os objetos originais", check: "(() => { const o = {c:'z'}; return agruparPor([o], 'c').z[0] === o; })()" }]),
  js("js-debounce", "avançado", "debounce", "Escreva debounce(fn, ms): devolve uma nova função que só chama `fn` depois de `ms` milissegundos SEM novas chamadas. Se for chamada de novo antes disso, o tempo recomeça. (Usado em campos de busca.)", "Guarde o id do setTimeout numa variável do escopo externo (closure); a cada chamada, clearTimeout e agende de novo. Repasse os argumentos.",
    "function debounce(fn, ms) {\n  // seu código aqui\n}", "function debounce(fn, ms) {\n  let id;\n  return (...args) => {\n    clearTimeout(id);\n    id = setTimeout(() => fn(...args), ms);\n  };\n}",
    [{ name: "3 chamadas seguidas executam só 1 vez", check: "(async () => { let n = 0; const f = debounce(() => n++, 40); f(); f(); f(); await new Promise((r) => setTimeout(r, 120)); return n === 1; })()" }, { name: "usa os argumentos da última chamada", check: "(async () => { let v; const f = debounce((x) => (v = x), 30); f(1); f(2); f(3); await new Promise((r) => setTimeout(r, 100)); return v === 3; })()" }, { name: "não executa antes do tempo", check: "(async () => { let n = 0; const f = debounce(() => n++, 80); f(); await new Promise((r) => setTimeout(r, 20)); return n === 0; })()" }]),
  js("js-memoize", "avançado", "memoize", "Escreva memoize(fn): devolve uma função que guarda os resultados já calculados e, se for chamada de novo com o mesmo argumento, devolve o valor guardado sem chamar `fn` outra vez. (Considere funções de um único argumento.)", "Use um Map no escopo externo: cache.has(arg), cache.get(arg), cache.set(arg, resultado).",
    "function memoize(fn) {\n  // seu código aqui\n}", "function memoize(fn) {\n  const cache = new Map();\n  return (arg) => {\n    if (cache.has(arg)) return cache.get(arg);\n    const r = fn(arg);\n    cache.set(arg, r);\n    return r;\n  };\n}",
    [{ name: "devolve o resultado correto", check: "memoize((x) => x * 2)(21) === 42" }, { name: "não recalcula o mesmo argumento", check: "(() => { let n = 0; const f = memoize((x) => (n++, x + 1)); f(1); f(1); f(1); return n === 1; })()" }, { name: "calcula novamente para argumentos novos", check: "(() => { let n = 0; const f = memoize((x) => (n++, x)); f(1); f(2); return n === 2; })()" }]),
  js("js-curry", "avançado", "curry", "Escreva curry(fn): transforma uma função de vários parâmetros em uma que aceita os argumentos aos poucos. curry((a,b,c)=>a+b+c) permite chamar f(1)(2)(3), f(1,2)(3) ou f(1)(2,3).", "fn.length é o número de parâmetros. Acumule os argumentos; quando tiver o suficiente, chame fn(...acumulados); senão devolva outra função.",
    "function curry(fn) {\n  // seu código aqui\n}", "function curry(fn) {\n  return function acumular(...args) {\n    return args.length >= fn.length ? fn(...args) : (...mais) => acumular(...args, ...mais);\n  };\n}",
    [{ name: "f(1)(2)(3) = 6", check: "curry((a, b, c) => a + b + c)(1)(2)(3) === 6" }, { name: "f(1, 2)(3) = 6", check: "curry((a, b, c) => a + b + c)(1, 2)(3) === 6" }, { name: "f(1)(2, 3) = 6", check: "curry((a, b, c) => a + b + c)(1)(2, 3) === 6" }, { name: "todos de uma vez", check: "curry((a, b) => a * b)(3, 4) === 12" }]),
  js("js-lru", "chefe", "Cache LRU", "Implemente a classe LRUCache(capacidade) com get(chave) e put(chave, valor). get devolve o valor (ou -1 se não existir) e marca a chave como usada recentemente. put grava; ao passar da capacidade, remove a chave MENOS usada recentemente.", "Um Map mantém a ordem de inserção. Para 'usar' uma chave: delete e set de novo (vai para o fim). A menos usada é a primeira: map.keys().next().value.",
    "class LRUCache {\n  constructor(capacidade) {\n    // seu código aqui\n  }\n  get(chave) {\n    // ...\n  }\n  put(chave, valor) {\n    // ...\n  }\n}", "class LRUCache {\n  constructor(capacidade) {\n    this.cap = capacidade;\n    this.mapa = new Map();\n  }\n  get(chave) {\n    if (!this.mapa.has(chave)) return -1;\n    const v = this.mapa.get(chave);\n    this.mapa.delete(chave);\n    this.mapa.set(chave, v);\n    return v;\n  }\n  put(chave, valor) {\n    this.mapa.delete(chave);\n    this.mapa.set(chave, valor);\n    if (this.mapa.size > this.cap) this.mapa.delete(this.mapa.keys().next().value);\n  }\n}",
    [{ name: "get devolve -1 se não existe", check: "new LRUCache(2).get('x') === -1" }, { name: "guarda e devolve valores", check: "(() => { const c = new LRUCache(2); c.put('a', 1); c.put('b', 2); return c.get('a') === 1 && c.get('b') === 2; })()" }, { name: "remove o menos usado ao exceder", check: "(() => { const c = new LRUCache(2); c.put('a', 1); c.put('b', 2); c.put('c', 3); return c.get('a') === -1 && c.get('b') === 2 && c.get('c') === 3; })()" }, { name: "get conta como uso recente", check: "(() => { const c = new LRUCache(2); c.put('a', 1); c.put('b', 2); c.get('a'); c.put('c', 3); return c.get('b') === -1 && c.get('a') === 1; })()" }, { name: "put em chave existente atualiza o valor", check: "(() => { const c = new LRUCache(2); c.put('a', 1); c.put('a', 9); return c.get('a') === 9; })()" }]),
  js("js-promise-all", "chefe", "Seu próprio Promise.all", "Escreva promiseAll(promessas): recebe um array de promises (ou valores) e devolve UMA promise que resolve com um array dos resultados, na mesma ordem. Se qualquer uma rejeitar, a promise devolvida rejeita com esse erro. Não use Promise.all.", "Crie uma new Promise; conte quantas já resolveram e guarde cada resultado na posição certa; chame reject no primeiro erro. Use Promise.resolve(p) para aceitar valores comuns.",
    "function promiseAll(promessas) {\n  // seu código aqui\n}", "function promiseAll(promessas) {\n  return new Promise((resolve, reject) => {\n    if (promessas.length === 0) return resolve([]);\n    const res = [];\n    let feitas = 0;\n    promessas.forEach((p, i) => {\n      Promise.resolve(p).then((v) => {\n        res[i] = v;\n        if (++feitas === promessas.length) resolve(res);\n      }, reject);\n    });\n  });\n}",
    [{ name: "resolve com os resultados na ordem", check: "(async () => { const r = await promiseAll([new Promise((ok) => setTimeout(() => ok('a'), 40)), 'b', Promise.resolve('c')]); return JSON.stringify(r) === '[\"a\",\"b\",\"c\"]'; })()" }, { name: "array vazio resolve com []", check: "(async () => JSON.stringify(await promiseAll([])) === '[]')()" }, { name: "rejeita se uma promise rejeitar", check: "(async () => { try { await promiseAll([Promise.resolve(1), Promise.reject(new Error('x'))]); return false; } catch (e) { return e.message === 'x'; } })()" }]),
  js("js-query", "chefe", "Parser de query string", "Escreva parseQuery(texto) que converte uma query string em objeto. 'a=1&b=2' → {a:'1', b:'2'}. Chaves repetidas viram array: 'x=1&x=2' → {x:['1','2']}. Decodifique os valores (decodeURIComponent) e trate '+' como espaço. Ignore um '?' inicial.", "Tire o ? do começo, divida por &, divida cada par por = (só o primeiro), troque + por espaço e use decodeURIComponent. Ao repetir a chave, transforme em array.",
    "function parseQuery(texto) {\n  // seu código aqui\n}", "function parseQuery(texto) {\n  const out = {};\n  texto.replace(/^\\?/, '').split('&').filter(Boolean).forEach((par) => {\n    const i = par.indexOf('=');\n    const dec = (s) => decodeURIComponent(s.replace(/\\+/g, ' '));\n    const k = dec(i < 0 ? par : par.slice(0, i));\n    const v = i < 0 ? '' : dec(par.slice(i + 1));\n    if (k in out) out[k] = [].concat(out[k], v);\n    else out[k] = v;\n  });\n  return out;\n}",
    [{ name: "pares simples", check: "JSON.stringify(parseQuery('a=1&b=2')) === '{\"a\":\"1\",\"b\":\"2\"}'" }, { name: "ignora o ? inicial", check: "parseQuery('?q=js').q === 'js'" }, { name: "chaves repetidas viram array", check: "JSON.stringify(parseQuery('x=1&x=2&x=3').x) === '[\"1\",\"2\",\"3\"]'" }, { name: "decodifica %20 e +", check: "parseQuery('nome=Ana%20Souza&cidade=Sao+Paulo').nome === 'Ana Souza' && parseQuery('cidade=Sao+Paulo').cidade === 'Sao Paulo'" }, { name: "valor com = no meio", check: "parseQuery('t=a=b').t === 'a=b'" }, { name: "texto vazio → {}", check: "JSON.stringify(parseQuery('')) === '{}'" }]),
];

/* ============================== CSS ============================== */
const css = (id: string, level: Level, title: string, brief: string, hint: string, starter: Code, solution: Code, tests: Test[]): WebChallenge => ({ kind: "web", id, lang: "css", level, title, brief, hint, starter, solution, tests });

const CSS: WebChallenge[] = [
  css("css-azul", "iniciante", "Título azul", "Deixe o título <h1> da página azul. Qualquer tom de azul serve (o canal azul deve ser claramente o maior).", "Use a propriedade color. Exemplos de valores: blue, #2f6fed, rgb(47, 111, 237).",
    { html: "<h1>Olá, CSS!</h1>\n<p>Meu primeiro desafio.</p>", css: "/* seu CSS aqui */\n", js: "" }, { html: "<h1>Olá, CSS!</h1>\n<p>Meu primeiro desafio.</p>", css: "h1 { color: #2f6fed; }", js: "" },
    [{ name: "o h1 é azul", check: "(() => { const c = " + cs("h1", "color") + ".match(/\\d+/g).map(Number); return c[2] > c[0] + 40 && c[2] > c[1] + 40; })()" }, { name: "o parágrafo não foi alterado", check: "(() => { const c = " + cs("p", "color") + ".match(/\\d+/g).map(Number); return !(c[2] > c[0] + 40 && c[2] > c[1] + 40); })()" }]),
  css("css-card", "iniciante", "Cartão com modelo de caixa", "Estilize a div .card: largura TOTAL de 300px (incluindo padding e borda), padding de 20px, borda de 2px sólida e cantos arredondados de 12px.", "box-sizing: border-box faz width incluir padding e borda. Sem isso, o cartão ficaria com 344px.",
    { html: '<div class="card">Sou um cartão</div>', css: ".card {\n  /* seu CSS aqui */\n}\n", js: "" }, { html: '<div class="card">Sou um cartão</div>', css: ".card {\n  box-sizing: border-box;\n  width: 300px;\n  padding: 20px;\n  border: 2px solid #2f6fed;\n  border-radius: 12px;\n}", js: "" },
    [{ name: "largura total de 300px", check: q(".card") + ".offsetWidth === 300" }, { name: "padding de 20px", check: cs(".card", "paddingTop") + " === '20px' && " + cs(".card", "paddingLeft") + " === '20px'" }, { name: "borda de 2px sólida", check: cs(".card", "borderTopWidth") + " === '2px' && " + cs(".card", "borderTopStyle") + " === 'solid'" }, { name: "cantos de 12px", check: cs(".card", "borderTopLeftRadius") + " === '12px'" }]),
  css("css-centro", "iniciante", "Centralizar de verdade", "Centralize a .caixa (100×100) horizontal E verticalmente dentro do .palco (que tem 300px de altura). Use o método que preferir.", "O mais curto: display: grid + place-items: center no .palco. Também vale flex com justify-content e align-items.",
    { html: '<div class="palco"><div class="caixa"></div></div>', css: ".palco {\n  height: 300px;\n  background: #e5e7eb;\n}\n.caixa {\n  width: 100px;\n  height: 100px;\n  background: #2f6fed;\n}\n", js: "" }, { html: '<div class="palco"><div class="caixa"></div></div>', css: ".palco {\n  height: 300px;\n  background: #e5e7eb;\n  display: grid;\n  place-items: center;\n}\n.caixa {\n  width: 100px;\n  height: 100px;\n  background: #2f6fed;\n}", js: "" },
    [{ name: "centralizada na horizontal", check: "(() => { const p = " + rect(".palco") + ", c = " + rect(".caixa") + "; return Math.abs((c.left + c.width / 2) - (p.left + p.width / 2)) < 2; })()" }, { name: "centralizada na vertical", check: "(() => { const p = " + rect(".palco") + ", c = " + rect(".caixa") + "; return Math.abs((c.top + c.height / 2) - (p.top + p.height / 2)) < 2; })()" }, { name: "a caixa continua com 100×100", check: q(".caixa") + ".offsetWidth === 100 && " + q(".caixa") + ".offsetHeight === 100" }]),
  css("css-navbar", "intermediário", "Navbar com flexbox", "Faça a <nav> mostrar a .logo na esquerda e os três links na direita, na mesma linha, alinhados verticalmente ao centro, com 16px de espaço entre os links.", "display: flex na nav; justify-content: space-between separa logo e links. Agrupe os links em um contêiner flex com gap: 16px.",
    { html: '<nav>\n  <span class="logo">Marca</span>\n  <div class="links">\n    <a href="#">Início</a>\n    <a href="#">Sobre</a>\n    <a href="#">Contato</a>\n  </div>\n</nav>', css: "nav {\n  background: #f3f4f6;\n  padding: 12px 20px;\n}\n/* seu CSS aqui */\n", js: "" }, { html: '<nav>\n  <span class="logo">Marca</span>\n  <div class="links">\n    <a href="#">Início</a>\n    <a href="#">Sobre</a>\n    <a href="#">Contato</a>\n  </div>\n</nav>', css: "nav {\n  background: #f3f4f6;\n  padding: 12px 20px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n.links {\n  display: flex;\n  gap: 16px;\n}", js: "" },
    [{ name: "a nav usa flexbox", check: cs("nav", "display") + " === 'flex'" }, { name: "logo à esquerda e links à direita", check: "(() => { const n = " + rect("nav") + ", l = " + rect(".logo") + ", k = " + rect(".links") + "; return l.left - n.left < 40 && n.right - k.right < 40; })()" }, { name: "tudo na mesma linha", check: "(() => { const l = " + rect(".logo") + ", k = " + rect(".links") + "; return Math.abs((l.top + l.height / 2) - (k.top + k.height / 2)) < 4; })()" }, { name: "16px entre os links", check: "(() => { const a = [...document.querySelectorAll('.links a')].map((x) => x.getBoundingClientRect()); return Math.abs(a[1].left - a[0].right - 16) < 1.5 && Math.abs(a[2].left - a[1].right - 16) < 1.5; })()" }]),
  css("css-grid3", "intermediário", "Grade de 3 colunas", "Organize os 6 itens da .grade em 3 colunas de largura igual, com 12px de espaço entre eles.", "display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px;",
    { html: '<div class="grade">\n  <div>1</div><div>2</div><div>3</div>\n  <div>4</div><div>5</div><div>6</div>\n</div>', css: ".grade div {\n  background: #dbeafe;\n  border: 2px solid #2f6fed;\n  padding: 16px;\n  text-align: center;\n}\n/* seu CSS aqui */\n", js: "" }, { html: '<div class="grade">\n  <div>1</div><div>2</div><div>3</div>\n  <div>4</div><div>5</div><div>6</div>\n</div>', css: ".grade {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 12px;\n}\n.grade div {\n  background: #dbeafe;\n  border: 2px solid #2f6fed;\n  padding: 16px;\n  text-align: center;\n}", js: "" },
    [{ name: "usa CSS Grid", check: cs(".grade", "display") + " === 'grid'" }, { name: "3 itens na primeira linha", check: "(() => { const t = [...document.querySelectorAll('.grade div')].map((d) => Math.round(d.getBoundingClientRect().top)); return t[0] === t[1] && t[1] === t[2] && t[3] > t[0]; })()" }, { name: "colunas de largura igual", check: "(() => { const w = [...document.querySelectorAll('.grade div')].slice(0, 3).map((d) => d.getBoundingClientRect().width); return Math.abs(w[0] - w[1]) < 1 && Math.abs(w[1] - w[2]) < 1; })()" }, { name: "espaço de 12px entre colunas", check: "(() => { const r = [...document.querySelectorAll('.grade div')].map((d) => d.getBoundingClientRect()); return Math.abs(r[1].left - r[0].right - 12) < 1.5; })()" }]),
  css("css-hover", "intermediário", "Botão com hover e transição", "Dê ao .btn um efeito ao passar o mouse: ao :hover ele muda a cor de fundo E sobe 2px (transform: translateY(-2px)), com transição suave de pelo menos 150ms.", "Defina a transition no estado normal, não no :hover. As regras :hover vão no CSS (o teste procura a regra .btn:hover).",
    { html: '<button class="btn">Passe o mouse</button>', css: ".btn {\n  padding: 12px 24px;\n  border: 0;\n  border-radius: 8px;\n  background: #2f6fed;\n  color: #fff;\n  cursor: pointer;\n}\n/* seu CSS aqui */\n", js: "" }, { html: '<button class="btn">Passe o mouse</button>', css: ".btn {\n  padding: 12px 24px;\n  border: 0;\n  border-radius: 8px;\n  background: #2f6fed;\n  color: #fff;\n  cursor: pointer;\n  transition: background .2s ease, transform .2s ease;\n}\n.btn:hover {\n  background: #1d4ed8;\n  transform: translateY(-2px);\n}", js: "" },
    [{ name: "existe uma regra .btn:hover", check: "[...document.styleSheets].some((s) => [...s.cssRules].some((r) => r.selectorText && /\\.btn:hover/.test(r.selectorText)))" }, { name: ":hover muda a cor de fundo", check: "(() => { const r = [...document.styleSheets].flatMap((s) => [...s.cssRules]).find((r) => r.selectorText && /\\.btn:hover/.test(r.selectorText)); return !!r && !!r.style.backgroundColor && r.style.backgroundColor !== " + cs(".btn", "backgroundColor") + "; })()" }, { name: ":hover sobe o botão com translateY", check: "(() => { const r = [...document.styleSheets].flatMap((s) => [...s.cssRules]).find((r) => r.selectorText && /\\.btn:hover/.test(r.selectorText)); return !!r && /translate/.test(r.style.transform); })()" }, { name: "transição de pelo menos 150ms", check: "(() => { const d = " + cs(".btn", "transitionDuration") + ".split(',').map((x) => parseFloat(x) * (x.includes('ms') ? 1 : 1000)); return Math.max(...d) >= 150; })()" }]),
  css("css-media", "intermediário", "Responsivo com media query", "Os 3 cartões (.c) devem ficar lado a lado (flex) em telas largas e EMPILHADOS em telas de até 600px. Escreva a media query (max-width: 600px) que troca a direção para coluna.", "Base: .lista { display: flex; gap: 12px }. Dentro de @media (max-width: 600px) { .lista { flex-direction: column } }.",
    { html: '<div class="lista"><div class="c">A</div><div class="c">B</div><div class="c">C</div></div>', css: ".c { padding: 20px; background: #dbeafe; flex: 1; text-align: center; }\n/* seu CSS aqui */\n", js: "" }, { html: '<div class="lista"><div class="c">A</div><div class="c">B</div><div class="c">C</div></div>', css: ".lista { display: flex; gap: 12px; }\n.c { padding: 20px; background: #dbeafe; flex: 1; text-align: center; }\n@media (max-width: 600px) {\n  .lista { flex-direction: column; }\n}", js: "" },
    [{ name: "os cartões ficam lado a lado (flex)", check: cs(".lista", "display") + " === 'flex'" }, { name: "existe uma @media com max-width", check: "[...document.styleSheets].some((s) => [...s.cssRules].some((r) => r instanceof CSSMediaRule && /max-width\\s*:\\s*\\d+/.test(r.conditionText)))" }, { name: "a @media troca para flex-direction: column", check: "[...document.styleSheets].some((s) => [...s.cssRules].some((r) => r instanceof CSSMediaRule && [...r.cssRules].some((x) => /column/.test(x.style && x.style.flexDirection))))" }]),
  css("css-flip", "avançado", "Cartão que vira em 3D", "Faça o .cartao virar 180° no eixo Y ao passar o mouse, mostrando o verso. Use perspective, transform-style: preserve-3d, backface-visibility: hidden nas duas faces e a regra :hover com rotateY(180deg).", "O contêiner .cena tem perspective; o .cartao tem preserve-3d e transição; .frente e .verso são position:absolute com backface-visibility hidden; o .verso já começa rotateY(180deg).",
    { html: '<div class="cena">\n  <div class="cartao">\n    <div class="frente">Frente</div>\n    <div class="verso">Verso</div>\n  </div>\n</div>', css: ".cena { width: 200px; height: 120px; margin: 20px; }\n.frente, .verso { display: grid; place-items: center; font: 700 20px system-ui; color: #fff; }\n.frente { background: #2f6fed; }\n.verso { background: #e4572e; }\n/* seu CSS aqui */\n", js: "" }, { html: '<div class="cena">\n  <div class="cartao">\n    <div class="frente">Frente</div>\n    <div class="verso">Verso</div>\n  </div>\n</div>', css: ".cena { width: 200px; height: 120px; margin: 20px; perspective: 800px; }\n.cartao { position: relative; width: 100%; height: 100%; transform-style: preserve-3d; transition: transform .7s; }\n.cena:hover .cartao { transform: rotateY(180deg); }\n.frente, .verso { position: absolute; inset: 0; display: grid; place-items: center; font: 700 20px system-ui; color: #fff; backface-visibility: hidden; }\n.frente { background: #2f6fed; }\n.verso { background: #e4572e; transform: rotateY(180deg); }", js: "" },
    [{ name: "a .cena tem perspective", check: cs(".cena", "perspective") + " !== 'none'" }, { name: "o .cartao preserva o 3D", check: cs(".cartao", "transformStyle") + " === 'preserve-3d'" }, { name: "as duas faces escondem o verso (backface-visibility)", check: cs(".frente", "backfaceVisibility") + " === 'hidden' && " + cs(".verso", "backfaceVisibility") + " === 'hidden'" }, { name: "existe uma regra :hover com rotateY(180deg)", check: "[...document.styleSheets].some((s) => [...s.cssRules].some((r) => r.selectorText && /:hover/.test(r.selectorText) && /rotateY\\(180deg\\)/.test(r.style.transform)))" }, { name: "a transição está definida", check: "parseFloat(" + cs(".cartao", "transitionDuration") + ") > 0" }]),
  css("css-vars", "avançado", "Tema com variáveis CSS", "Defina a variável --marca no :root (uma cor) e use var(--marca) como cor de fundo do .btn E como cor da borda do .card. Mudar a variável deve mudar os dois.", "No :root: --marca: #7c3aed;  Depois: background: var(--marca); border: 2px solid var(--marca).",
    { html: '<button class="btn">Botão</button>\n<div class="card">Cartão</div>', css: ".btn { padding: 10px 18px; color: #fff; border: 0; border-radius: 8px; }\n.card { margin-top: 12px; padding: 16px; border-radius: 10px; }\n/* seu CSS aqui */\n", js: "" }, { html: '<button class="btn">Botão</button>\n<div class="card">Cartão</div>', css: ":root { --marca: #7c3aed; }\n.btn { padding: 10px 18px; color: #fff; border: 0; border-radius: 8px; background: var(--marca); }\n.card { margin-top: 12px; padding: 16px; border-radius: 10px; border: 2px solid var(--marca); }", js: "" },
    [{ name: "--marca está definida no :root", check: "getComputedStyle(document.documentElement).getPropertyValue('--marca').trim() !== ''" }, { name: "o fundo do botão usa a variável", check: "(() => { const t = document.createElement('i'); t.style.color = getComputedStyle(document.documentElement).getPropertyValue('--marca').trim(); document.body.append(t); const ok = getComputedStyle(t).color === " + cs(".btn", "backgroundColor") + "; t.remove(); return ok; })()" }, { name: "a borda do cartão usa a variável", check: "(() => { const t = document.createElement('i'); t.style.color = getComputedStyle(document.documentElement).getPropertyValue('--marca').trim(); document.body.append(t); const ok = getComputedStyle(t).color === " + cs(".card", "borderTopColor") + "; t.remove(); return ok; })()" }, { name: "o código usa var(--marca)", check: "[...document.styleSheets].flatMap((s) => [...s.cssRules]).filter((r) => r.cssText && r.cssText.includes('var(--marca)')).length >= 2" }]),
  css("css-areas", "chefe", "Layout completo com grid-template-areas", "Monte o layout clássico usando grid-template-areas: cabeçalho ocupando toda a largura no topo, menu lateral de 160px à esquerda, conteúdo ao lado e rodapé embaixo ocupando toda a largura. A página deve ter pelo menos 300px de altura.", "No .pagina: display: grid; grid-template-areas: \"topo topo\" \"menu conteudo\" \"base base\"; grid-template-columns: 160px 1fr; grid-template-rows: auto 1fr auto; min-height: 300px. Cada filho com grid-area.",
    { html: '<div class="pagina">\n  <header>Topo</header>\n  <aside>Menu</aside>\n  <main>Conteúdo</main>\n  <footer>Rodapé</footer>\n</div>', css: "header, aside, main, footer { padding: 14px; border: 1px solid #94a3b8; background: #f1f5f9; }\n/* seu CSS aqui */\n", js: "" }, { html: '<div class="pagina">\n  <header>Topo</header>\n  <aside>Menu</aside>\n  <main>Conteúdo</main>\n  <footer>Rodapé</footer>\n</div>', css: ".pagina {\n  display: grid;\n  grid-template-areas: \"topo topo\" \"menu conteudo\" \"base base\";\n  grid-template-columns: 160px 1fr;\n  grid-template-rows: auto 1fr auto;\n  min-height: 300px;\n}\nheader { grid-area: topo; }\naside { grid-area: menu; }\nmain { grid-area: conteudo; }\nfooter { grid-area: base; }\nheader, aside, main, footer { padding: 14px; border: 1px solid #94a3b8; background: #f1f5f9; }", js: "" },
    [{ name: "a .pagina é um grid", check: cs(".pagina", "display") + " === 'grid'" }, { name: "usa grid-template-areas", check: cs(".pagina", "gridTemplateAreas") + " !== 'none'" }, { name: "cabeçalho ocupa toda a largura, no topo", check: "(() => { const p = " + rect(".pagina") + ", h = " + rect("header") + "; return Math.abs(h.width - p.width) < 2 && Math.abs(h.top - p.top) < 2; })()" }, { name: "menu de 160px à esquerda do conteúdo", check: "(() => { const a = " + rect("aside") + ", m = " + rect("main") + "; return Math.abs(a.width - 160) < 2 && m.left >= a.right - 1 && Math.abs(a.top - m.top) < 2; })()" }, { name: "rodapé embaixo, em largura total", check: "(() => { const p = " + rect(".pagina") + ", f = " + rect("footer") + ", m = " + rect("main") + "; return Math.abs(f.width - p.width) < 2 && f.top >= m.bottom - 1 && Math.abs(f.bottom - p.bottom) < 2; })()" }, { name: "altura mínima de 300px", check: q(".pagina") + ".offsetHeight >= 300" }]),
  css("css-anim", "chefe", "Animação infinita", "Faça a .bola se mover de um lado para o outro SEM parar: crie @keyframes (translateX de 0 até 200px), aplique com duração de 1 a 3 segundos, infinite e alternate, com easing suave (ease-in-out). Respeite quem prefere menos movimento: dentro de @media (prefers-reduced-motion: reduce) desligue a animação.", "animation: vai 2s ease-in-out infinite alternate;  e  @keyframes vai { from { transform: translateX(0) } to { transform: translateX(200px) } }.",
    { html: '<div class="bola"></div>', css: ".bola { width: 40px; height: 40px; border-radius: 50%; background: #e4572e; }\n/* seu CSS aqui */\n", js: "" }, { html: '<div class="bola"></div>', css: ".bola { width: 40px; height: 40px; border-radius: 50%; background: #e4572e; animation: vai 2s ease-in-out infinite alternate; }\n@keyframes vai { from { transform: translateX(0); } to { transform: translateX(200px); } }\n@media (prefers-reduced-motion: reduce) { .bola { animation: none; } }", js: "" },
    [{ name: "tem uma animação aplicada", check: cs(".bola", "animationName") + " !== 'none'" }, { name: "repete infinitamente", check: cs(".bola", "animationIterationCount") + " === 'infinite'" }, { name: "vai e volta (alternate)", check: cs(".bola", "animationDirection") + " === 'alternate'" }, { name: "duração entre 1s e 3s", check: "(() => { const d = parseFloat(" + cs(".bola", "animationDuration") + "); return d >= 1 && d <= 3; })()" }, { name: "existe @keyframes com translateX", check: "[...document.styleSheets].some((s) => [...s.cssRules].some((r) => r instanceof CSSKeyframesRule && /translate/.test(r.cssText)))" }, { name: "respeita prefers-reduced-motion", check: "[...document.styleSheets].some((s) => [...s.cssRules].some((r) => r instanceof CSSMediaRule && /prefers-reduced-motion/.test(r.conditionText)))" }]),
];

/* ============================== HTML ============================== */
const html = (id: string, level: Level, title: string, brief: string, hint: string, starter: string, solution: string, tests: Test[]): WebChallenge => ({ kind: "web", id, lang: "html", level, title, brief, hint, starter: { ...E, html: starter }, solution: { ...E, html: solution }, tests });

const HTML: WebChallenge[] = [
  html("html-esqueleto", "iniciante", "Esqueleto de uma página", "Complete o documento: declare o idioma português do Brasil, a codificação UTF-8, a meta viewport e um <title> com pelo menos 5 caracteres. No corpo, um <h1> com texto.", "<html lang=\"pt-BR\">, <meta charset=\"UTF-8\">, <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> e <title>.",
    "<!DOCTYPE html>\n<html>\n<head>\n  <!-- seu código aqui -->\n</head>\n<body>\n  <h1></h1>\n</body>\n</html>", page("  <h1>Olá, mundo!</h1>"),
    [{ name: "html com lang pt-BR", check: "document.documentElement.lang.toLowerCase() === 'pt-br'" }, { name: "meta charset UTF-8", check: "!!document.querySelector('meta[charset]') && document.characterSet === 'UTF-8'" }, { name: "meta viewport com width=device-width", check: "/width=device-width/.test((document.querySelector('meta[name=viewport]') || {}).content || '')" }, { name: "title com pelo menos 5 caracteres", check: "document.title.trim().length >= 5" }, { name: "h1 com texto", check: "!!document.querySelector('h1') && document.querySelector('h1').textContent.trim().length > 0" }]),
  html("html-semantica", "iniciante", "Estrutura semântica", "Monte uma página de blog usando as tags com significado: header (com nav), main com DOIS article (cada um com um h2) e footer. Apenas um h1 na página.", "Troque as <div> por <header>, <nav>, <main>, <article> e <footer>. Cada <article> precisa de um <h2>.",
    page('  <div>\n    <div>Meu Blog</div>\n    <div><a href="#">Início</a></div>\n  </div>\n  <div>\n    <div>Post 1</div>\n    <div>Post 2</div>\n  </div>\n  <div>© 2026</div>'), page('  <header>\n    <h1>Meu Blog</h1>\n    <nav><a href="#">Início</a> <a href="#">Sobre</a></nav>\n  </header>\n  <main>\n    <article><h2>Post 1</h2><p>Texto do primeiro post.</p></article>\n    <article><h2>Post 2</h2><p>Texto do segundo post.</p></article>\n  </main>\n  <footer>© 2026</footer>'),
    [{ name: "tem <header> com <nav>", check: "!!document.querySelector('header nav')" }, { name: "tem exatamente um <main>", check: "document.querySelectorAll('main').length === 1" }, { name: "o <main> tem pelo menos 2 <article>", check: "document.querySelectorAll('main article').length >= 2" }, { name: "cada <article> tem um <h2>", check: "[...document.querySelectorAll('article')].length > 0 && [...document.querySelectorAll('article')].every((a) => a.querySelector('h2'))" }, { name: "tem <footer>", check: "!!document.querySelector('footer')" }, { name: "apenas um <h1>", check: "document.querySelectorAll('h1').length === 1" }]),
  html("html-form", "intermediário", "Formulário acessível", "Complete o formulário de cadastro: cada campo precisa de um <label> ligado (for/id), o e-mail deve ser type=email e obrigatório, a senha type=password com no mínimo 8 caracteres e obrigatória, e o botão deve ser type=submit. Dê também autocomplete=\"email\" ao e-mail.", "<label for=\"email\">E-mail</label> <input id=\"email\" name=\"email\" type=\"email\" required autocomplete=\"email\">",
    page('  <form>\n    E-mail: <input>\n    Senha: <input>\n    <button>Cadastrar</button>\n  </form>'), page('  <form>\n    <p><label for="email">E-mail</label>\n    <input id="email" name="email" type="email" required autocomplete="email"></p>\n    <p><label for="senha">Senha</label>\n    <input id="senha" name="senha" type="password" minlength="8" required></p>\n    <button type="submit">Cadastrar</button>\n  </form>'),
    [{ name: "existe um campo de e-mail (type=email) obrigatório", check: "(() => { const e = document.querySelector('input[type=email]'); return !!e && e.required; })()" }, { name: "o e-mail tem autocomplete=\"email\"", check: "(document.querySelector('input[type=email]') || {}).autocomplete === 'email'" }, { name: "existe senha (type=password) obrigatória com mínimo de 8", check: "(() => { const s = document.querySelector('input[type=password]'); return !!s && s.required && s.minLength >= 8; })()" }, { name: "todo campo tem um <label> associado", check: "(() => { const i = [...document.querySelectorAll('form input')]; return i.length >= 2 && i.every((x) => x.labels && x.labels.length > 0); })()" }, { name: "todo campo tem name", check: "[...document.querySelectorAll('form input')].every((x) => x.name)" }, { name: "o botão é type=submit", check: "(() => { const b = document.querySelector('form button'); return !!b && b.type === 'submit'; })()" }]),
  html("html-img", "intermediário", "Imagens bem feitas", "Corrija as 3 imagens: a primeira é informativa (alt descritivo com pelo menos 10 caracteres), a segunda é só um enfeite (alt vazio) e a terceira fica abaixo da dobra (loading=lazy). Todas devem ter width e height definidos.", "alt=\"\" (vazio, mas presente) marca imagem decorativa. loading=\"lazy\" adia o carregamento.",
    page('  <img src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'120\' height=\'80\'%3E%3Crect width=\'120\' height=\'80\' fill=\'%232f6fed\'/%3E%3C/svg%3E">\n  <img src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'40\' height=\'40\'%3E%3Ccircle cx=\'20\' cy=\'20\' r=\'18\' fill=\'%23e4572e\'/%3E%3C/svg%3E">\n  <img src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'120\' height=\'80\'%3E%3Crect width=\'120\' height=\'80\' fill=\'%231f9c7a\'/%3E%3C/svg%3E">'),
    page('  <img src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'120\' height=\'80\'%3E%3Crect width=\'120\' height=\'80\' fill=\'%232f6fed\'/%3E%3C/svg%3E" alt="Retângulo azul usado como capa do artigo" width="120" height="80">\n  <img src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'40\' height=\'40\'%3E%3Ccircle cx=\'20\' cy=\'20\' r=\'18\' fill=\'%23e4572e\'/%3E%3C/svg%3E" alt="" width="40" height="40">\n  <img src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'120\' height=\'80\'%3E%3Crect width=\'120\' height=\'80\' fill=\'%231f9c7a\'/%3E%3C/svg%3E" alt="Retângulo verde ilustrando a galeria" width="120" height="80" loading="lazy">'),
    [{ name: "existem 3 imagens", check: "document.images.length === 3" }, { name: "a 1ª tem alt descritivo (10+ caracteres)", check: "(document.images[0].getAttribute('alt') || '').trim().length >= 10" }, { name: "a 2ª é decorativa: alt presente e vazio", check: "document.images[1].hasAttribute('alt') && document.images[1].getAttribute('alt') === ''" }, { name: "a 3ª tem loading=lazy", check: "document.images[2].getAttribute('loading') === 'lazy'" }, { name: "todas têm width e height", check: "[...document.images].every((i) => i.getAttribute('width') && i.getAttribute('height'))" }]),
  html("html-tabela", "intermediário", "Tabela acessível", "Transforme os dados em uma tabela de verdade: com <caption>, <thead> (th com scope=\"col\"), <tbody> com pelo menos 2 linhas e a primeira célula de cada linha como <th scope=\"row\">.", "<table><caption>…</caption><thead><tr><th scope=\"col\">…</th></tr></thead><tbody><tr><th scope=\"row\">…</th><td>…</td></tr></tbody></table>",
    page("  <div>Produto - Preço</div>\n  <div>Caneta - R$ 3</div>\n  <div>Caderno - R$ 15</div>"), page('  <table>\n    <caption>Lista de produtos</caption>\n    <thead><tr><th scope="col">Produto</th><th scope="col">Preço</th></tr></thead>\n    <tbody>\n      <tr><th scope="row">Caneta</th><td>R$ 3</td></tr>\n      <tr><th scope="row">Caderno</th><td>R$ 15</td></tr>\n    </tbody>\n  </table>'),
    [{ name: "existe uma <table> com <caption>", check: "!!document.querySelector('table caption') && document.querySelector('table caption').textContent.trim().length > 0" }, { name: "tem <thead> com th scope=col", check: "document.querySelectorAll('thead th[scope=col]').length >= 2" }, { name: "o <tbody> tem pelo menos 2 linhas", check: "document.querySelectorAll('tbody tr').length >= 2" }, { name: "a 1ª célula de cada linha é th scope=row", check: "[...document.querySelectorAll('tbody tr')].every((r) => r.firstElementChild && r.firstElementChild.tagName === 'TH' && r.firstElementChild.getAttribute('scope') === 'row')" }]),
  html("html-a11y", "avançado", "Página acessível ao teclado", "Deixe a página navegável por teclado e leitor de tela: um link \"Pular para o conteúdo\" como PRIMEIRO elemento focável apontando para #conteudo; <main id=\"conteudo\">; duas <nav> diferenciadas por aria-label; e o botão só com ícone precisa de um nome acessível.", "<a class=\"skip\" href=\"#conteudo\">Pular para o conteúdo</a> logo no começo do body; aria-label=\"Principal\" e aria-label=\"Rodapé\" nas navs; aria-label no botão do ícone.",
    page('  <nav><a href="/">Início</a> <a href="/sobre">Sobre</a></nav>\n  <div>\n    <h1>Minha página</h1>\n    <button>🔍</button>\n  </div>\n  <nav><a href="/termos">Termos</a></nav>'), page('  <a class="skip" href="#conteudo">Pular para o conteúdo</a>\n  <nav aria-label="Principal"><a href="/">Início</a> <a href="/sobre">Sobre</a></nav>\n  <main id="conteudo">\n    <h1>Minha página</h1>\n    <button type="button" aria-label="Buscar">🔍</button>\n  </main>\n  <nav aria-label="Rodapé"><a href="/termos">Termos</a></nav>'),
    [{ name: "o primeiro elemento focável é o link para #conteudo", check: "(() => { const f = document.querySelector('a[href], button, input, select, textarea, [tabindex]'); return !!f && f.getAttribute('href') === '#conteudo'; })()" }, { name: "existe <main id=\"conteudo\">", check: "!!document.querySelector('main#conteudo')" }, { name: "as <nav> têm aria-label diferentes", check: "(() => { const n = [...document.querySelectorAll('nav')]; const l = n.map((x) => x.getAttribute('aria-label')); return n.length >= 2 && l.every(Boolean) && new Set(l).size === l.length; })()" }, { name: "o botão de ícone tem nome acessível", check: "(() => { const b = document.querySelector('button'); return !!b && (b.getAttribute('aria-label') || '').trim().length > 0; })()" }, { name: "o botão tem type definido", check: "document.querySelector('button').hasAttribute('type')" }]),
  html("html-seo", "avançado", "SEO e compartilhamento", "Prepare o <head> para buscadores e redes sociais: title entre 10 e 60 caracteres, meta description entre 50 e 160, link canonical, Open Graph (og:title, og:description, og:image) e dados estruturados JSON-LD válidos com @type.", "Use <meta property=\"og:title\" content=\"…\">. O JSON-LD vai em <script type=\"application/ld+json\"> com @context e @type.",
    "<!DOCTYPE html>\n<html lang=\"pt-BR\">\n<head>\n  <meta charset=\"UTF-8\">\n  <!-- seu código aqui -->\n</head>\n<body>\n  <h1>Tênis de corrida Runner</h1>\n</body>\n</html>", "<!DOCTYPE html>\n<html lang=\"pt-BR\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Tênis de corrida Runner | Loja Exemplo</title>\n  <meta name=\"description\" content=\"Tênis leve e confortável para corrida de rua, com amortecimento e entrega rápida.\">\n  <link rel=\"canonical\" href=\"https://exemplo.com/tenis-runner\">\n  <meta property=\"og:title\" content=\"Tênis de corrida Runner\">\n  <meta property=\"og:description\" content=\"Leve, confortável e com entrega rápida.\">\n  <meta property=\"og:image\" content=\"https://exemplo.com/tenis.jpg\">\n  <script type=\"application/ld+json\">{\"@context\":\"https://schema.org\",\"@type\":\"Product\",\"name\":\"Tênis de corrida Runner\"}</script>\n</head>\n<body>\n  <h1>Tênis de corrida Runner</h1>\n</body>\n</html>",
    [{ name: "title entre 10 e 60 caracteres", check: "document.title.length >= 10 && document.title.length <= 60" }, { name: "meta description entre 50 e 160 caracteres", check: "(() => { const d = (document.querySelector('meta[name=description]') || {}).content || ''; return d.length >= 50 && d.length <= 160; })()" }, { name: "link canonical com URL completa", check: "/^https?:\\/\\//.test((document.querySelector('link[rel=canonical]') || {}).href || '')" }, { name: "Open Graph: og:title, og:description e og:image", check: "['og:title', 'og:description', 'og:image'].every((p) => { const m = document.querySelector('meta[property=\"' + p + '\"]'); return !!m && m.content.trim().length > 0; })" }, { name: "JSON-LD válido com @type", check: "(() => { try { const j = JSON.parse(document.querySelector('script[type=\"application/ld+json\"]').textContent); return !!j['@type'] && !!j['@context']; } catch (e) { return false; } })()" }]),
  html("html-completa", "chefe", "Página completa e bem estruturada", "Construa do zero uma página de 'Receitas': documento completo em pt-BR; header com h1 e nav (aria-label); main com uma section (aria-labelledby apontando para um h2) contendo 2 article (h3 em cada) e um aside; um formulário de newsletter com label, e-mail obrigatório e botão; footer. Os títulos devem seguir a ordem (h1 → h2 → h3, sem pular níveis) e deve existir uma ÚNICA landmark main.", "Combine tudo que você praticou: esqueleto, semântica, acessibilidade e formulário. Confira a ordem dos títulos antes de rodar os testes.",
    "<!DOCTYPE html>\n<html>\n<head>\n</head>\n<body>\n  <!-- construa a página aqui -->\n</body>\n</html>", page('  <header>\n    <h1>Receitas da Vovó</h1>\n    <nav aria-label="Principal"><a href="#receitas">Receitas</a> <a href="#news">Newsletter</a></nav>\n  </header>\n  <main>\n    <section aria-labelledby="t-receitas" id="receitas">\n      <h2 id="t-receitas">Receitas em destaque</h2>\n      <article><h3>Bolo de cenoura</h3><p>Fofinho e com cobertura de chocolate.</p></article>\n      <article><h3>Pão de queijo</h3><p>Crocante por fora, macio por dentro.</p></article>\n    </section>\n    <aside aria-label="Dica">Use ingredientes em temperatura ambiente.</aside>\n    <section aria-labelledby="t-news" id="news">\n      <h2 id="t-news">Receba novidades</h2>\n      <form>\n        <label for="e">E-mail</label>\n        <input id="e" name="email" type="email" required>\n        <button type="submit">Assinar</button>\n      </form>\n    </section>\n  </main>\n  <footer>© 2026 Receitas da Vovó</footer>'),
    [{ name: "documento em pt-BR com title e charset", check: "document.documentElement.lang.toLowerCase() === 'pt-br' && document.title.trim().length > 0 && !!document.querySelector('meta[charset]')" }, { name: "header com h1 e nav com aria-label", check: "!!document.querySelector('header h1') && !!document.querySelector('header nav[aria-label]')" }, { name: "uma única landmark <main>", check: "document.querySelectorAll('main').length === 1" }, { name: "section ligada a um h2 por aria-labelledby", check: "(() => { const s = document.querySelector('main section[aria-labelledby]'); if (!s) return false; const h = document.getElementById(s.getAttribute('aria-labelledby')); return !!h && h.tagName === 'H2'; })()" }, { name: "2 article com h3 e um aside", check: "document.querySelectorAll('main article').length >= 2 && [...document.querySelectorAll('article')].every((a) => a.querySelector('h3')) && !!document.querySelector('aside')" }, { name: "formulário com label, e-mail obrigatório e botão", check: "(() => { const f = document.querySelector('form'); if (!f) return false; const i = f.querySelector('input[type=email]'); return !!i && i.required && i.labels.length > 0 && !!f.querySelector('button[type=submit]'); })()" }, { name: "títulos em ordem, sem pular níveis", check: "(() => { const h = [...document.querySelectorAll('h1,h2,h3,h4,h5,h6')].map((x) => +x.tagName[1]); return h[0] === 1 && h.every((n, i) => i === 0 || n - h[i - 1] <= 1) && h.filter((n) => n === 1).length === 1; })()" }, { name: "tem <footer>", check: "!!document.querySelector('footer')" }]),
];

/* ============================== SQL ============================== */
const LEVEL_MAP: Record<string, Level> = { "iniciante": "iniciante", "intermediário": "intermediário", "avançado": "avançado" };

const sqlFromExercises: SqlChallenge[] = SQL_EXERCISES.map((e) => ({
  kind: "sql", id: e.id, lang: "sql", level: LEVEL_MAP[e.level], title: e.title, brief: e.text, hint: e.hint, db: e.db, solution: e.solution,
}));

const sqlNew = (id: string, db: DbId, level: Level, title: string, brief: string, hint: string, solution: string): SqlChallenge => ({ kind: "sql", id, lang: "sql", level, title, brief, hint, db, solution });

const SQL_EXTRA: SqlChallenge[] = [
  sqlNew("loja-11", "loja", "avançado", "Acima da média de gastos", "Quais clientes gastaram (soma dos pedidos pagos) MAIS do que a média de gasto dos clientes que compraram? Mostre o nome e o gasto, do maior para o menor.", "Calcule o gasto por cliente numa CTE (WITH) e compare com (SELECT AVG(gasto) FROM a_cte).", "WITH g AS (SELECT cliente_id, SUM(total) AS gasto FROM pedidos WHERE status = 'pago' GROUP BY cliente_id) SELECT c.nome, g.gasto FROM g JOIN clientes c ON c.id = g.cliente_id WHERE g.gasto > (SELECT AVG(gasto) FROM g) ORDER BY g.gasto DESC;"),
  sqlNew("loja-12", "loja", "avançado", "Variação da receita mês a mês", "Para os pedidos pagos, mostre cada mês (AAAA-MM), a receita do mês e a diferença para a receita do mês anterior. O primeiro mês fica com a diferença vazia (NULL). Em ordem cronológica.", "Agrupe por mês numa CTE; depois use LAG(receita) OVER (ORDER BY mes) e subtraia.", "WITH m AS (SELECT strftime('%Y-%m', data) AS mes, SUM(total) AS receita FROM pedidos WHERE status = 'pago' GROUP BY mes) SELECT mes, receita, receita - LAG(receita) OVER (ORDER BY mes) AS variacao FROM m ORDER BY mes;"),
  sqlNew("escola-5", "escola", "avançado", "Melhor nota de cada curso", "Para cada curso, mostre o nome do curso, o nome do aluno com a MAIOR nota e a nota. (Se houver empate, qualquer um dos empatados deve aparecer; confira só quem ficar em 1º por RANK.)", "ROW_NUMBER ou RANK com PARTITION BY curso ORDER BY nota DESC, em uma subconsulta; filtre posição = 1. Notas NULL ficam fora.", "SELECT curso, aluno, nota FROM (SELECT c.nome AS curso, a.nome AS aluno, m.nota, RANK() OVER (PARTITION BY c.id ORDER BY m.nota DESC) AS pos FROM matriculas m JOIN cursos c ON c.id = m.curso_id JOIN alunos a ON a.id = m.aluno_id WHERE m.nota IS NOT NULL) WHERE pos = 1;"),
  sqlNew("rh-5", "rh", "chefe", "Organograma com níveis", "Usando uma CTE recursiva, mostre cada funcionário com seu nível na hierarquia (0 = quem não tem gerente, 1 = subordinados diretos...). Colunas: nome e nivel. Ordene por nível e depois por nome.", "WITH RECURSIVE: âncora = gerente_id IS NULL com nivel 0; parte recursiva junta funcionarios com a CTE por gerente_id = arvore.id, somando 1 ao nível.", "WITH RECURSIVE arvore(id, nome, nivel) AS (SELECT id, nome, 0 FROM funcionarios WHERE gerente_id IS NULL UNION ALL SELECT f.id, f.nome, a.nivel + 1 FROM funcionarios f JOIN arvore a ON f.gerente_id = a.id) SELECT nome, nivel FROM arvore ORDER BY nivel, nome;"),
  sqlNew("loja-13", "loja", "chefe", "Ranking com participação no total", "Para os pedidos pagos, mostre cada cliente (nome), o gasto total e o PERCENTUAL do gasto dele sobre o total geral (arredondado a 1 casa decimal), em ordem decrescente de gasto.", "SUM(total) por cliente e, na mesma consulta, SUM(SUM(total)) OVER () para o total geral. Multiplique por 100.0 para evitar divisão inteira.", "SELECT c.nome, SUM(p.total) AS gasto, ROUND(100.0 * SUM(p.total) / SUM(SUM(p.total)) OVER (), 1) AS percentual FROM pedidos p JOIN clientes c ON c.id = p.cliente_id WHERE p.status = 'pago' GROUP BY c.id, c.nome ORDER BY gasto DESC;"),
  sqlNew("rh-6", "rh", "chefe", "Maior salário de cada departamento (e quem é)", "Para cada departamento (inclusive os vazios), mostre o nome do departamento, o funcionário de maior salário e o salário. Departamentos sem funcionários aparecem com valores vazios. Ordene pelo nome do departamento.", "Subconsulta com ROW_NUMBER por depto ordenada por salário DESC; depois LEFT JOIN de departamentos com essa subconsulta filtrando pos = 1 no ON.", "SELECT d.nome AS departamento, t.nome AS funcionario, t.salario FROM departamentos d LEFT JOIN (SELECT depto_id, nome, salario, ROW_NUMBER() OVER (PARTITION BY depto_id ORDER BY salario DESC) AS pos FROM funcionarios) t ON t.depto_id = d.id AND t.pos = 1 ORDER BY d.nome;"),
];

export const CHALLENGES: Challenge[] = [...HTML, ...CSS, ...JS, ...sqlFromExercises, ...SQL_EXTRA];

export const CHALLENGE_BY_ID = new Map(CHALLENGES.map((c) => [c.id, c]));
export const LANG_META: Record<Lang, { label: string; color: string; emoji: string }> = {
  html: { label: "HTML", color: "#e4572e", emoji: "🧱" },
  css: { label: "CSS", color: "#2f6fed", emoji: "🎨" },
  js: { label: "JavaScript", color: "#d4a017", emoji: "⚡" },
  sql: { label: "SQL", color: "#1f9c7a", emoji: "🗄️" },
};
