/** O que é primordial em cada área, na ordem em que deve ser aprendido.
 *  Links usam "lang:slug" (comando), "/rota" (página do site). São resolvidos na renderização. */
export type EssStep = {
  id: string;
  title: string;
  why: string;
  /** o que acontece se você pular este passo */
  skip: string;
  /** tarefa prática, para fazer agora */
  task: string;
  links: string[];
};

export type EssTrack = { id: string; title: string; emoji: string; intro: string; steps: EssStep[] };

export const ESSENCIAL: EssTrack[] = [
  {
    id: "html", title: "HTML", emoji: "🧱",
    intro: "A estrutura de tudo na web. Quem domina HTML semântico escreve menos CSS e JavaScript, tem sites mais acessíveis e mais bem posicionados no Google.",
    steps: [
      { id: "html-1", title: "Esqueleto da página: doctype, lang, charset e viewport", why: "É a base de todo documento: define o idioma, a codificação (acentos!) e faz a página funcionar no celular.", skip: "Sem viewport o site aparece minúsculo no celular; sem charset os acentos viram símbolos estranhos; sem doctype o navegador entra em 'modo antigo'.", task: "Crie uma página em branco no Lab com <html lang=\"pt-BR\">, charset UTF-8 e viewport, e escreva uma frase com acentos.", links: ["html:html", "html:meta-charset-viewport", "html:comentarios-html"] },
      { id: "html-2", title: "Semântica: header, nav, main, section, article, footer", why: "Tags com significado dão estrutura para leitores de tela, buscadores e para você mesmo.", skip: "Uma página só de <div> é um muro de texto para quem usa leitor de tela e perde pontos de SEO.", task: "Monte uma página de blog com header, nav, main, 2 article e footer. Compare com a versão feita só de div.", links: ["html:header", "html:main", "html:section", "html:article", "html:role-landmarks", "/comparativos/div-section-article"] },
      { id: "html-3", title: "Títulos em ordem (h1 a h6) e textos", why: "A hierarquia de títulos é o 'sumário' da página. Use um h1 por página e não pule níveis.", skip: "Títulos escolhidos pelo tamanho visual embaralham a navegação por títulos e o SEO.", task: "Escreva um artigo com 1 h1, 3 h2 e subseções h3. Depois mude o tamanho dos títulos só com CSS.", links: ["html:headings", "html:p", "html:strong", "html:em"] },
      { id: "html-4", title: "Links: a, rel, âncoras e texto que faz sentido", why: "Links são a essência da web. O texto do link deve fazer sentido sozinho.", skip: "'Clique aqui' e links sem href quebram acessibilidade, teclado e SEO.", task: "Crie um menu que leva a seções da mesma página e um link externo que abre em nova aba com rel=noopener.", links: ["html:a", "html:a-target-rel", "html:ancora-interna", "html:skip-link", "/comparativos/button-vs-a"] },
      { id: "html-5", title: "Imagens: alt, width/height e lazy loading", why: "Toda imagem informativa precisa de alt; as dimensões evitam que a página 'pule' ao carregar.", skip: "Sem alt a imagem some para quem não enxerga; sem dimensões a página pula (CLS) e o Google penaliza.", task: "Insira 3 imagens: uma informativa (alt descritivo), uma decorativa (alt vazio) e uma com loading=lazy.", links: ["html:img", "html:alt-boas-praticas", "html:loading-lazy", "html:srcset-sizes"] },
      { id: "html-6", title: "Listas e tabelas", why: "Menus são listas; dados tabulares são tabelas. Nunca use tabela para layout.", skip: "Menu feito com <br> e dados em div viram bagunça acessível e difícil de estilizar.", task: "Faça um menu com <ul> e uma tabela com thead, tbody e th scope.", links: ["html:ul", "html:ol", "html:table", "html:th-scope", "css:table-responsiva"] },
      { id: "html-7", title: "Formulários: label, name e tipos de input", why: "Formulários são a principal forma de interação do usuário. Todo campo precisa de label e name.", skip: "Campos sem label são inacessíveis e difíceis de tocar no celular; sem name o dado não é enviado.", task: "Construa um formulário de cadastro com nome, e-mail, senha e checkbox, todos com label ligado por for/id.", links: ["html:form", "html:input", "html:label", "html:input-tipos-texto", "html:button-types", "/comparativos/get-vs-post"] },
      { id: "html-8", title: "Validação nativa e preenchimento automático", why: "required, type=email, pattern e autocomplete entregam validação e conversão sem JavaScript.", skip: "Sem eles você escreve validação à mão (e erra) e perde preenchimento automático no celular.", task: "Adicione required, minlength, pattern e autocomplete ao formulário e tente enviar vazio.", links: ["html:validacao-nativa", "html:autocomplete", "html:inputmode-enterkeyhint"] },
      { id: "html-9", title: "Acessibilidade básica: foco, ARIA e teclado", why: "Parte dos seus usuários usa só o teclado ou um leitor de tela. O HTML correto resolve a maioria.", skip: "Site inutilizável para teclado e leitor de tela: perda de usuários e risco legal.", task: "Navegue pelo seu site só com Tab/Enter. Tudo é alcançável? O foco aparece? Corrija o que faltar.", links: ["html:aria-primeira-regra", "html:tabindex-foco", "html:aria-label", "css:focus-visible"] },
      { id: "html-10", title: "Metadados para SEO e compartilhamento", why: "title, description e Open Graph decidem como sua página aparece no Google e no WhatsApp.", skip: "Link compartilhado sem imagem nem descrição e snippet ruim no Google.", task: "Escreva title (até 60 caracteres), meta description (até 155) e og:title/og:image na sua página.", links: ["html:title", "html:meta-description", "html:og-tags", "html:meta-robots-canonical", "html:json-ld"] },
    ],
  },
  {
    id: "css", title: "CSS", emoji: "🎨",
    intro: "Layout, tipografia e movimento. Com poucos conceitos bem entendidos (caixa, flex, grid, cascata) você faz quase qualquer interface.",
    steps: [
      { id: "css-1", title: "O modelo de caixa e box-sizing: border-box", why: "Todo elemento é uma caixa (conteúdo, padding, borda, margem). Entender isso resolve metade dos 'bugs' de layout.", skip: "Larguras que 'estouram' a tela e espaçamentos imprevisíveis em todo projeto.", task: "Aplique * { box-sizing: border-box } e compare dois blocos de width: 300px com padding e borda, antes e depois.", links: ["css:box-sizing", "css:margin", "css:padding", "css:width-height", "/comparativos/margin-vs-padding"] },
      { id: "css-2", title: "Seletores, cascata e especificidade", why: "Saber por que uma regra 'ganha' evita o uso desesperado de !important.", skip: "CSS impossível de manter, cheio de !important e regras que 'não pegam'.", task: "Crie 3 regras conflitantes para o mesmo elemento e preveja qual vence antes de testar no Lab.", links: ["css:especificidade", "css:combinadores", "css:pseudo-classes", "css:important", "css:layer"] },
      { id: "css-3", title: "Cores, tipografia e legibilidade", why: "Fonte, tamanho, espaçamento entre linhas e contraste fazem o texto ser lido (ou abandonado).", skip: "Texto cansativo, com baixo contraste, que falha em acessibilidade.", task: "Defina font-size 1rem, line-height 1.6 e largura máxima de 65ch no corpo do texto; confira o contraste das cores.", links: ["css:font-family-weight", "css:line-height", "css:font-size", "css:color-formats", "css:units"] },
      { id: "css-4", title: "Display e position", why: "block, inline, none, relative, absolute, sticky e fixed explicam onde cada elemento aparece.", skip: "Elementos sobrepostos, menus que somem e z-index que 'não funciona'.", task: "Faça um cabeçalho sticky e um selo posicionado no canto de um card (relative + absolute).", links: ["css:display-values", "css:position", "css:sticky", "css:z-index", "css:isolation"] },
      { id: "css-5", title: "Flexbox", why: "A ferramenta para alinhar e distribuir itens em uma dimensão: menus, barras, cards em linha, centralização.", skip: "Layouts frágeis feitos com float e margens manuais.", task: "Monte uma navbar (logo à esquerda, links à direita) e centralize uma div na tela com flex.", links: ["css:display-flex", "css:justify-content", "css:align-items", "css:flex-wrap", "css:centralizar", "/geradores"] },
      { id: "css-6", title: "CSS Grid", why: "Layouts em duas dimensões: páginas inteiras, galerias e dashboards, com pouco código.", skip: "Você continua forçando flexbox onde grid resolveria em 3 linhas.", task: "Crie uma galeria responsiva sem media query com repeat(auto-fit, minmax(220px, 1fr)).", links: ["css:display-grid", "css:grid-template-columns", "css:grid-auto-fit", "css:grid-template-areas", "/comparativos/flexbox-vs-grid"] },
      { id: "css-7", title: "Design responsivo: mobile-first e media queries", why: "A maior parte do tráfego é de celular. Comece pelo menor e acrescente para telas maiores.", skip: "Site quebrado no celular, que é onde a maioria das pessoas vai acessar.", task: "Teste seu layout nos tamanhos 375, 768 e 1280 no Lab (multi-tela) e ajuste onde quebrar.", links: ["css:media-query", "css:clamp-min-max", "css:container-queries", "css:dvh", "/lab"] },
      { id: "css-8", title: "Variáveis CSS (custom properties) e tokens de design", why: "Cores e espaçamentos em um lugar só: mudar o tema vira trocar variáveis.", skip: "Cores repetidas em 80 lugares e retrabalho a cada mudança de marca.", task: "Defina --cor-marca, --raio e --espaco em :root e use-os em botão, card e link.", links: ["css:custom-properties", "css:root", "css:color-mix", "css:light-dark"] },
      { id: "css-9", title: "Estados e interação: hover, focus-visible, disabled", why: "Todo elemento interativo precisa mostrar que responde (hover) e onde está o foco (teclado).", skip: "Interface 'morta', e usuário de teclado sem saber onde está.", task: "Estilize um botão com hover, active, :focus-visible e :disabled.", links: ["css:pseudo-classes", "css:focus-visible", "css:cursor", "css:form-states", "css:hover-receitas"] },
      { id: "css-10", title: "Transições e animações com moderação", why: "Movimento guia a atenção, mas deve ser sutil, rápido e respeitar quem prefere menos movimento.", skip: "Interface travada, animações pesadas e desconforto (enjoo) em parte dos usuários.", task: "Anime só transform e opacity em um card e inclua a media query prefers-reduced-motion.", links: ["css:transition", "css:keyframes", "css:animacoes-prontas", "css:prefers-reduced-motion", "css:will-change"] },
      { id: "css-11", title: "Reset moderno e organização do CSS", why: "Uma base consistente (reset, tokens, utilitários) torna o projeto previsível.", skip: "Cada página com margens e fontes diferentes dependendo do navegador.", task: "Cole o starter completo do snippet cd-css (VS Code) no começo de um projeto novo.", links: ["/vscode", "css:valores-globais", "css:nesting"] },
    ],
  },
  {
    id: "js", title: "JavaScript", emoji: "⚡",
    intro: "A linguagem que dá vida à página. O essencial é entender dados, funções, arrays e o DOM antes de qualquer framework.",
    steps: [
      { id: "js-1", title: "Variáveis, tipos e igualdade", why: "const por padrão, let quando muda; e === sempre. Isso evita uma classe inteira de bugs.", skip: "Bugs sutis de coerção de tipos e variáveis que 'vazam' de blocos.", task: "Teste no console: 1 == '1', 1 === '1', [] == false. Explique cada resultado.", links: ["/comparativos/let-const-var", "/comparativos/igual-duplo-vs-triplo", "js:template-literals"] },
      { id: "js-2", title: "Funções, escopo e closures", why: "Funções são a unidade básica de reuso; closures explicam callbacks, eventos e quase todo código assíncrono.", skip: "Código copiado sem entender e bugs de 'this' e de escopo.", task: "Escreva uma função contador() que devolve uma função que incrementa e retorna o valor.", links: ["js:arrow-functions", "js:closures", "js:default-params", "js:this-context"] },
      { id: "js-3", title: "Arrays: map, filter, reduce, find", why: "Quase todo dado real é uma lista. Esses métodos substituem a maioria dos laços.", skip: "Laços repetitivos e propensos a erro para tarefas simples.", task: "Dada uma lista de produtos, calcule o total dos que custam mais de 100 com filter + reduce.", links: ["js:map", "js:filter", "js:reduce", "js:find-findindex", "js:sort", "/comparativos/map-foreach-filter-reduce"] },
      { id: "js-4", title: "Objetos, desestruturação e spread", why: "Dados vêm em objetos (APIs, JSON). Desestruturar e copiar com spread é o dia a dia.", skip: "Código verboso e mutação acidental de dados compartilhados.", task: "Extraia nome e cidade de um objeto aninhado e crie uma cópia atualizada sem alterar o original.", links: ["js:destructuring", "js:spread-rest", "js:object-entries", "js:optional-chaining", "js:nullish-coalescing"] },
      { id: "js-5", title: "O DOM: selecionar, alterar e criar elementos", why: "É assim que JavaScript muda a página: ler, alterar texto, classes e criar elementos.", skip: "Sem DOM você não interage com a página; com innerHTML mal usado, abre brecha de segurança (XSS).", task: "Crie uma lista de tarefas que adiciona itens ao DOM com createElement e textContent.", links: ["js:queryselector", "js:classlist", "js:createelement", "js:innerhtml-textcontent", "js:dataset"] },
      { id: "js-6", title: "Eventos", why: "Cliques, teclas e envio de formulário: todo comportamento nasce de um evento.", skip: "Interface estática e handlers duplicados ou que vazam memória.", task: "Capture o submit de um formulário, evite o recarregamento e mostre os dados no console.", links: ["js:addeventlistener", "js:settimeout-setinterval"] },
      { id: "js-7", title: "Assíncrono: promises, async/await e fetch", why: "Toda comunicação com servidores e APIs é assíncrona. É o que separa páginas estáticas de aplicações.", skip: "Chamadas que 'não funcionam', condições de corrida e telas sem estado de carregamento ou erro.", task: "Busque dados de uma API pública com fetch/async-await e mostre loading, sucesso e erro.", links: ["js:fetch", "js:async-await", "js:new-promise", "js:promise-all", "js:try-catch-finally"] },
      { id: "js-8", title: "JSON e armazenamento local", why: "JSON é o formato universal de dados; localStorage guarda preferências e rascunhos no navegador.", skip: "Dados perdidos ao recarregar e erros ao serializar objetos.", task: "Salve a lista de tarefas no localStorage como JSON e a recupere ao abrir a página.", links: ["js:json-stringify-parse", "js:localstorage", "js:sessionstorage"] },
      { id: "js-9", title: "Tratamento de erros", why: "Tudo falha: rede, dados inesperados, permissões. Um app profissional trata e comunica o erro.", skip: "A tela quebra em branco e o usuário não sabe o que aconteceu.", task: "Envolva JSON.parse de uma entrada inválida em try/catch e mostre uma mensagem amigável.", links: ["js:try-catch-finally", "js:promise-race-allsettled"] },
      { id: "js-10", title: "Classes e organização do código", why: "Agrupar dados e comportamento facilita projetos maiores e é base de frameworks e bibliotecas.", skip: "Arquivos gigantes e funções soltas impossíveis de reaproveitar.", task: "Crie uma classe Carrinho com adicionar(), remover() e total().", links: ["js:class-basica", "js:extends-super", "js:getters-setters", "js:static"] },
    ],
  },
  {
    id: "sql", title: "SQL e Banco de Dados", emoji: "🗄️",
    intro: "Todo produto real guarda dados. SQL é a linguagem universal para consultá-los: poucos comandos bem entendidos cobrem 90% do trabalho.",
    steps: [
      { id: "sql-1", title: "SELECT, WHERE, ORDER BY e LIMIT", why: "O alicerce: escolher colunas, filtrar linhas, ordenar e limitar.", skip: "Tudo o mais em SQL depende disto.", task: "No SQL Lab, liste os 5 produtos mais caros da loja.", links: ["sql:select-where", "sql:order-by", "sql:limit", "sql:like", "sql:between-isnull", "/sql-lab"] },
      { id: "sql-2", title: "NULL, DISTINCT e as armadilhas dos valores vazios", why: "NULL não é zero nem texto vazio, e não se compara com '='. É a fonte número 1 de resultados errados.", skip: "Relatórios com números errados que ninguém percebe.", task: "Compare COUNT(*), COUNT(email) e COUNT(DISTINCT estado) na tabela de clientes.", links: ["sql:distinct", "sql:coalesce", "sql:nullif", "/comparativos/count-estrela-vs-coluna"] },
      { id: "sql-3", title: "JOINs: INNER e LEFT", why: "Dados vivem em várias tabelas. JOIN é como você os reúne.", skip: "Sem JOIN você faz várias consultas à mão e perde a integridade dos resultados.", task: "Liste todos os clientes e quantos pedidos cada um fez, incluindo quem nunca comprou.", links: ["sql:inner-join", "sql:left-right-join", "sql:self-join", "/comparativos/inner-vs-left-join"] },
      { id: "sql-4", title: "GROUP BY, agregações e HAVING", why: "Relatórios são agregações: total por mês, média por categoria, contagem por status.", skip: "Cálculos feitos na aplicação, lentos e repetidos.", task: "Calcule a receita por mês dos pedidos pagos.", links: ["sql:group-by-having", "sql:count", "sql:sum-avg", "sql:max-min", "/comparativos/where-vs-having"] },
      { id: "sql-5", title: "INSERT, UPDATE e DELETE com segurança", why: "Alterar dados é perigoso: um UPDATE sem WHERE altera a tabela inteira.", skip: "Perda ou corrupção de dados em produção.", task: "Rode primeiro o SELECT equivalente, depois o UPDATE, dentro de uma transação com ROLLBACK.", links: ["sql:insert", "sql:update", "sql:delete", "sql:begin-commit-rollback", "sql:delete-vs-truncate"] },
      { id: "sql-6", title: "Chaves e restrições: PRIMARY KEY, FOREIGN KEY, UNIQUE", why: "O banco pode garantir a integridade dos dados por você: sem duplicatas, sem vínculos quebrados.", skip: "Dados inconsistentes que nenhum código da aplicação consegue consertar depois.", task: "Crie duas tabelas relacionadas e tente inserir um vínculo inexistente.", links: ["sql:primary-key", "sql:foreign-key", "sql:unique-not-null", "sql:check-constraint", "/comparativos/primary-key-vs-unique"] },
      { id: "sql-7", title: "Modelagem e normalização", why: "Bom modelo evita dados repetidos e contraditórios; é a decisão mais difícil de mudar depois.", skip: "Tabelas 'tudo junto' com dados duplicados e anomalias de atualização.", task: "Desenhe o modelo de um sistema de matrículas escolares com relacionamento N:N.", links: ["sql:normalizacao", "sql:relacionamento-nn", "sql:tipos-de-dados", "sql:soft-delete"] },
      { id: "sql-8", title: "Subconsultas e CTEs", why: "Quebrar um problema complexo em partes legíveis é o que separa consultas de iniciante e de profissional.", skip: "Consultas gigantes e ilegíveis.", task: "Reescreva uma consulta com subconsulta usando WITH (CTE).", links: ["sql:subquery", "sql:with-cte", "sql:exists", "sql:in-vs-exists", "sql:cte-recursiva"] },
      { id: "sql-9", title: "Funções de janela", why: "Ranking, acumulados e comparação com a linha anterior sem perder o detalhe de cada linha.", skip: "Soluções complicadas com subconsultas correlacionadas lentas.", task: "Calcule o top 2 de pedidos de cada cliente e o total acumulado por data.", links: ["sql:over-partition", "sql:row-number-rank", "sql:lag-lead", "sql:running-total", "sql:top-n-por-grupo"] },
      { id: "sql-10", title: "Índices e plano de execução", why: "Consulta correta mas lenta é consulta errada em produção. EXPLAIN mostra o porquê.", skip: "Sistema que funciona com 100 linhas e trava com 1 milhão.", task: "Rode EXPLAIN antes e depois de criar um índice e compare o plano.", links: ["sql:create-index", "sql:explain", "sql:indice-composto", "sql:funcao-na-coluna", "sql:select-asterisco"] },
      { id: "sql-11", title: "Segurança: SQL injection, permissões e RLS", why: "Banco exposto é o maior risco de vazamento. Parâmetros, privilégio mínimo e RLS são obrigatórios.", skip: "Vazamento de dados de clientes (e responsabilidade legal por isso).", task: "No Supabase/Postgres, crie uma policy RLS em que cada usuário só vê as próprias linhas.", links: ["sql:sql-injection", "sql:grant-revoke", "sql:rls-policies", "sql:supabase-js-para-sql"] },
    ],
  },
  {
    id: "git", title: "Git, GitHub e Deploy", emoji: "🚀",
    intro: "Código sem versionamento e sem deploy não existe para o mundo. Estes passos transformam um projeto local em um site publicado e em um portfólio.",
    steps: [
      { id: "git-1", title: "Git: init, add, commit, status, log", why: "O histórico do seu código: desfazer erros, entender mudanças e trabalhar com outras pessoas.", skip: "Código perdido, 'versão-final-2-agora-vai.zip' e medo de mexer no que funciona.", task: "Inicie um repositório e faça 3 commits pequenos com mensagens claras.", links: ["/guias/publicar-site-github-vercel"] },
      { id: "git-2", title: "Configurar o e-mail certo no Git", why: "O e-mail do commit precisa estar ligado à sua conta do GitHub para o commit contar no seu perfil.", skip: "Commits 'sem dono': não aparecem no gráfico de contribuições do GitHub.", task: "Use git config user.email com o endereço noreply do GitHub e confira com git log.", links: ["/guias/publicar-site-github-vercel"] },
      { id: "git-3", title: "GitHub: repositório remoto, push e README", why: "Seu portfólio público de código. O README é a vitrine do projeto.", skip: "Recrutadores e clientes não veem seu trabalho.", task: "Publique um projeto com README (o que é, como rodar, prints) e uma boa descrição.", links: ["/guias/publicar-site-github-vercel"] },
      { id: "git-4", title: ".gitignore e segredos fora do código", why: "Chaves de API e senhas nunca vão para o repositório.", skip: "Chave vazada em repositório público e conta comprometida em minutos.", task: "Crie o .gitignore (node_modules, .env) e uma .env.example sem valores reais.", links: ["/guias/publicar-site-github-vercel", "sql:sql-injection"] },
      { id: "git-5", title: "Branches e commits atômicos", why: "Commits pequenos e com mensagem clara contam a história do projeto e facilitam reverter.", skip: "Um commit gigante 'atualizações' que ninguém consegue revisar nem desfazer.", task: "Crie uma branch, faça 3 commits (feat, fix, docs) e junte na main.", links: ["/guias/publicar-site-github-vercel"] },
      { id: "git-6", title: "Deploy contínuo (Vercel, Netlify ou GitHub Pages)", why: "Cada push publica o site automaticamente. Você ganha um endereço para mostrar.", skip: "O projeto só existe no seu computador.", task: "Conecte o repositório à Vercel e publique. Teste o link no celular.", links: ["/guias/publicar-site-github-vercel"] },
    ],
  },
  {
    id: "qualidade", title: "Qualidade: acessibilidade, segurança e performance", emoji: "🛡️",
    intro: "O que separa um projeto de estudo de um profissional. São os três critérios que mais pesam em entrevistas e em clientes exigentes.",
    steps: [
      { id: "q-1", title: "Acessibilidade: o mínimo que todo site precisa", why: "Teclado, contraste, alt, rótulos e landmarks. É ética, é lei em vários países e melhora o SEO.", skip: "Exclui milhões de pessoas e pode gerar processos.", task: "Rode o Lighthouse na sua página e corrija tudo o que aparece na categoria Acessibilidade.", links: ["html:aria-primeira-regra", "html:alt-boas-praticas", "html:skip-link", "css:prefers-reduced-motion", "css:media-preferencias"] },
      { id: "q-2", title: "Segurança no front-end: XSS e dados do usuário", why: "Nunca insira texto do usuário com innerHTML sem sanitizar. Validar no navegador é conveniência; validar no servidor é obrigação.", skip: "Injeção de scripts e vazamento de dados.", task: "Troque um innerHTML com entrada do usuário por textContent e explique a diferença.", links: ["js:innerhtml-textcontent", "html:validacao-nativa", "sql:sql-injection"] },
      { id: "q-3", title: "Performance: imagens, scripts e fontes", why: "Páginas lentas perdem usuários e posição no Google. Imagens e JavaScript são os maiores culpados.", skip: "Site que demora a carregar, principalmente em redes móveis.", task: "Aplique loading=lazy, width/height, defer em scripts e font-display: swap; compare no Lighthouse.", links: ["html:loading-lazy", "html:script-defer-async", "html:preload-preconnect", "css:font-display", "css:contain"] },
      { id: "q-4", title: "Responsividade e testes em vários dispositivos", why: "Seu site será aberto em telas de 280 a 2560 pixels.", skip: "Layout quebrado em aparelhos que você nunca testou.", task: "No Lab, use o modo multi-tela (celular, tablet e desktop) e corrija tudo o que quebrar.", links: ["/lab", "css:media-query", "css:container-queries"] },
      { id: "q-5", title: "Ler documentação e depurar", why: "A habilidade mais valiosa é descobrir sozinho: ler erro, usar o DevTools, consultar o MDN.", skip: "Dependência constante de tutoriais e de terceiros para qualquer erro.", task: "Abra o DevTools, ative a visualização de contornos e inspecione o box model de 3 elementos.", links: ["/lab", "/sql-lab"] },
    ],
  },
];

export const ESS_TOTAL = ESSENCIAL.reduce((n, t) => n + t.steps.length, 0);

/** Conjunto "lang/slug" de todos os comandos citados na trilha (para a etiqueta "Essencial"). */
export const ESS_COMMANDS = new Set(
  ESSENCIAL.flatMap((t) => t.steps.flatMap((s) => s.links.filter((l) => /^[a-z]+:/.test(l)).map((l) => l.replace(":", "/")))),
);
