import { T } from "@/content/themes";

export const templatesExtra = [
  /* ============================== BLOG / REVISTA ============================== */
  T({
    slug: "blog-revista", title: "Blog / revista", category: "Conteúdo",
    description: "Destaque em tela larga, grade de artigos, categorias, barra de assinatura e rodapé.",
    tags: ["blog", "conteúdo", "grid", "responsivo"], themes: ["editorial", "claro", "escuro", "pastel", "minimal"],
    css: `header{border-bottom:1px solid color-mix(in srgb,var(--text) 12%,transparent)}.top{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem 0;flex-wrap:wrap}.logo{font:800 1.6rem var(--head)}nav{display:flex;gap:1.2rem;flex-wrap:wrap}nav a{color:var(--muted);font-weight:600}nav a:hover{color:var(--text)}
.feat{display:grid;grid-template-columns:1.3fr 1fr;gap:2rem;align-items:center}.feat .ph{aspect-ratio:4/3}.feat h1{font-size:clamp(1.8rem,4vw,2.8rem);margin:.5rem 0}.meta{font-size:.85rem;color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:1.5rem}.post{display:grid;gap:.6rem}.post .ph{aspect-ratio:16/10;transition:transform .3s}.post:hover .ph{transform:scale(1.02)}.post h3{font-size:1.2rem}
.cats{display:flex;gap:.5rem;flex-wrap:wrap;margin-bottom:1.5rem}.cats a{padding:.35rem .9rem;border-radius:99px;border:1px solid color-mix(in srgb,var(--text) 18%,transparent);font-size:.9rem}.cats a:hover,.cats a.on{background:var(--text);color:var(--bg)}
.nl{text-align:center;background:var(--surface);border-radius:var(--radius);padding:2.5rem 1rem}.nl form{display:flex;gap:.5rem;justify-content:center;flex-wrap:wrap;margin-top:1rem}.nl input{padding:.75rem 1rem;border-radius:var(--radius);border:1.5px solid color-mix(in srgb,var(--text) 18%,transparent);background:var(--bg);color:var(--text);font:inherit;min-width:min(100%,260px)}
footer{padding:2rem 0;color:var(--muted);font-size:.9rem;border-top:1px solid color-mix(in srgb,var(--text) 12%,transparent)}@media(max-width:720px){.feat{grid-template-columns:1fr}}`,
    body: `<header><div class="wrap top"><a class="logo" href="#">Diário<span style="color:var(--brand)">.</span></a><nav><a href="#">Tecnologia</a><a href="#">Design</a><a href="#">Negócios</a><a href="#">Cultura</a></nav></div></header>
<main>
<section><div class="wrap feat"><div><span class="tag">Em destaque</span><h1>Como a internet mudou a maneira de contar histórias</h1><p class="muted">Uma análise sobre formatos, atenção e o futuro da leitura online, com especialistas de três países.</p><p class="meta" style="margin:.8rem 0 1.2rem">Por Marina Costa · 8 min de leitura</p><a class="btn" href="#">Ler matéria</a></div><div class="ph"></div></div></section>
<section style="padding-top:0"><div class="wrap"><div class="cats"><a class="on" href="#">Todos</a><a href="#">Tecnologia</a><a href="#">Design</a><a href="#">Negócios</a><a href="#">Cultura</a></div>
<div class="grid">
<article class="post"><div class="ph"></div><span class="tag">Design</span><h3>Sistemas de design: do caos à consistência</h3><p class="muted">Como equipes pequenas organizam componentes sem travar o produto.</p><span class="meta">12 jun · 5 min</span></article>
<article class="post"><div class="ph" style="filter:hue-rotate(60deg)"></div><span class="tag">Tecnologia</span><h3>O que esperar da próxima geração de navegadores</h3><p class="muted">CSS moderno, transições nativas e menos JavaScript.</p><span class="meta">10 jun · 6 min</span></article>
<article class="post"><div class="ph" style="filter:hue-rotate(140deg)"></div><span class="tag">Negócios</span><h3>Freelancer ou agência? Como decidir o formato</h3><p class="muted">Prós, contras e números reais de quem já passou pelos dois.</p><span class="meta">8 jun · 7 min</span></article>
<article class="post"><div class="ph" style="filter:hue-rotate(220deg)"></div><span class="tag">Cultura</span><h3>Por que todo mundo está falando de lentidão digital</h3><p class="muted">O movimento que defende menos telas e mais presença.</p><span class="meta">5 jun · 4 min</span></article>
</div></div></section>
<section style="padding-top:0"><div class="wrap"><div class="nl"><h2>Receba os melhores artigos</h2><p class="muted">Um e-mail por semana. Sem spam.</p><form onsubmit="return false"><input type="email" placeholder="seu@email.com" aria-label="E-mail"><button class="btn">Assinar</button></form></div></div></section>
</main>
<footer><div class="wrap">© 2026 Diário. Todos os direitos reservados.</div></footer>`,
  }),

  /* ============================== LOJA ============================== */
  T({
    slug: "loja-virtual", title: "Loja virtual (e-commerce)", category: "Vendas",
    description: "Barra de anúncio, cabeçalho com carrinho, banner, categorias e grade de produtos com selos e preços.",
    tags: ["e-commerce", "loja", "produtos", "carrinho"], themes: ["vibrante", "claro", "escuro", "minimal", "pastel"],
    css: `.ann{background:var(--text);color:var(--bg);text-align:center;font-size:.85rem;padding:.5rem}header{position:sticky;top:0;z-index:5;background:var(--bg);border-bottom:1px solid color-mix(in srgb,var(--text) 12%,transparent)}.top{display:flex;align-items:center;gap:1.2rem;padding:.9rem 0}.logo{font:800 1.5rem var(--head)}.search{flex:1;max-width:420px;padding:.6rem 1rem;border-radius:99px;border:1.5px solid color-mix(in srgb,var(--text) 15%,transparent);background:var(--surface);color:var(--text);font:inherit}.cart{margin-left:auto;position:relative;font-size:1.3rem}.cart b{position:absolute;top:-6px;right:-10px;background:var(--brand);color:var(--on);font-size:.7rem;border-radius:99px;padding:0 6px}
.banner{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:1.5rem;padding:2.5rem;border-radius:var(--radius);background:linear-gradient(120deg,var(--brand),var(--brand2));color:var(--on)}.banner h1{font-size:clamp(1.8rem,4vw,3rem)}.banner .btn{background:var(--on);color:var(--brand);margin-top:1rem}.banner .img{height:200px;border-radius:var(--radius);background:#fff3;display:grid;place-items:center;font-size:5rem}
.cats{display:flex;gap:.6rem;overflow-x:auto;padding-bottom:.3rem;margin:1.5rem 0}.cats a{flex:none;padding:.5rem 1.1rem;border-radius:99px;background:var(--surface);font-weight:600}.cats a:hover{background:var(--brand);color:var(--on)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:1.2rem}.p{background:var(--surface);border-radius:var(--radius);overflow:hidden;transition:transform .2s,box-shadow .2s}.p:hover{transform:translateY(-4px);box-shadow:0 14px 30px #0002}.p .img{position:relative;aspect-ratio:1;display:grid;place-items:center;font-size:3.5rem;background:color-mix(in srgb,var(--brand) 14%,var(--surface))}.sel{position:absolute;top:10px;left:10px;background:var(--brand);color:var(--on);font-size:.7rem;font-weight:800;padding:.15rem .6rem;border-radius:99px}.p .b{padding:1rem;display:grid;gap:.3rem}.old{text-decoration:line-through;color:var(--muted);font-size:.85rem}.price{font-weight:800;font-size:1.15rem}.p button{margin-top:.5rem}
.perks{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;text-align:center}footer{padding:2rem 0;background:var(--surface);color:var(--muted);text-align:center;font-size:.9rem}@media(max-width:640px){.banner{grid-template-columns:1fr;padding:1.5rem}.banner .img{display:none}.search{display:none}}`,
    body: `<div class="ann">🚚 Frete grátis acima de R$ 199 · parcele em até 10x</div>
<header><div class="wrap top"><a class="logo" href="#">Loja<span style="color:var(--brand)">+</span></a><input class="search" placeholder="Buscar produtos…" aria-label="Buscar"><a class="cart" href="#" aria-label="Carrinho">🛒<b id="n">0</b></a></div></header>
<main><section style="padding-bottom:0"><div class="wrap"><div class="banner"><div><span style="font-weight:700;opacity:.9">COLEÇÃO DE VERÃO</span><h1>Até 40% off em tudo</h1><p style="opacity:.9">Só até domingo. Aproveite.</p><a class="btn" href="#">Ver ofertas</a></div><div class="img">🛍️</div></div>
<div class="cats"><a href="#">Todos</a><a href="#">Moda</a><a href="#">Tecnologia</a><a href="#">Casa</a><a href="#">Esportes</a><a href="#">Beleza</a></div></div></section>
<section style="padding-top:0"><div class="wrap"><h2 style="margin-bottom:1rem">Mais vendidos</h2><div class="grid">
<article class="p"><div class="img"><span class="sel">-30%</span>👟</div><div class="b"><span class="muted">Tênis Runner</span><span class="old">R$ 399,90</span><span class="price">R$ 279,90</span><button class="btn add">Adicionar</button></div></article>
<article class="p"><div class="img">🎧</div><div class="b"><span class="muted">Fone Bluetooth</span><span class="price">R$ 249,00</span><button class="btn add">Adicionar</button></div></article>
<article class="p"><div class="img"><span class="sel">Novo</span>⌚</div><div class="b"><span class="muted">Smartwatch Fit</span><span class="price">R$ 599,00</span><button class="btn add">Adicionar</button></div></article>
<article class="p"><div class="img">🎒</div><div class="b"><span class="muted">Mochila Urbana</span><span class="old">R$ 189,90</span><span class="price">R$ 129,90</span><button class="btn add">Adicionar</button></div></article>
</div></div></section>
<section style="padding-top:0"><div class="wrap perks"><div class="card">🔒<br><b>Compra segura</b><br><span class="muted">Dados protegidos</span></div><div class="card">↩️<br><b>Troca grátis</b><br><span class="muted">Em até 30 dias</span></div><div class="card">💬<br><b>Suporte 24h</b><br><span class="muted">Chat e WhatsApp</span></div></div></section></main>
<footer><div class="wrap">© 2026 Loja+ · Todos os direitos reservados</div></footer>`,
    js: `let n=0;document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{document.getElementById('n').textContent=++n;b.textContent='Adicionado ✓';setTimeout(()=>b.textContent='Adicionar',1200)})`,
  }),

  /* ============================== SAAS ============================== */
  T({
    slug: "saas-produto", title: "Página de SaaS / aplicativo", category: "Vendas",
    description: "Hero com mockup de painel, logos, recursos, preços com alternância, FAQ e chamada final.",
    tags: ["saas", "startup", "landing", "preços", "faq"], themes: ["escuro", "claro", "neon", "pastel", "minimal"],
    css: `header{position:sticky;top:0;z-index:5;backdrop-filter:blur(12px);background:color-mix(in srgb,var(--bg) 80%,transparent)}.top{display:flex;align-items:center;justify-content:space-between;padding:.9rem 0}.logo{font:800 1.3rem var(--head)}nav{display:flex;gap:1.4rem;align-items:center}nav a:not(.btn){color:var(--muted);font-weight:600}
.hero{text-align:center;padding-bottom:1rem}.pill{display:inline-block;padding:.3rem .9rem;border-radius:99px;background:color-mix(in srgb,var(--brand) 16%,transparent);color:var(--brand);font-weight:700;font-size:.85rem}.hero h1{font-size:clamp(2.2rem,6vw,4rem);max-width:15ch;margin:1rem auto}.hero p{max-width:52ch;margin:0 auto 1.6rem}.hero .row{display:flex;gap:.8rem;justify-content:center;flex-wrap:wrap}
.mock{margin:3rem auto 0;max-width:880px;border-radius:var(--radius);background:var(--surface);border:1px solid color-mix(in srgb,var(--text) 12%,transparent);box-shadow:0 30px 80px color-mix(in srgb,var(--brand) 30%,transparent);padding:1rem}.mock .bar{display:flex;gap:6px;margin-bottom:1rem}.mock .bar i{width:10px;height:10px;border-radius:50%;background:color-mix(in srgb,var(--text) 25%,transparent)}.mock .cols{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.mock .k{padding:1rem;border-radius:calc(var(--radius)/1.5);background:var(--bg);text-align:left}.mock .k b{font-size:1.6rem;display:block}.mock .chart{height:120px;margin-top:.8rem;border-radius:calc(var(--radius)/1.5);background:linear-gradient(180deg,color-mix(in srgb,var(--brand) 35%,transparent),transparent),repeating-linear-gradient(90deg,transparent 0 38px,color-mix(in srgb,var(--text) 6%,transparent) 38px 40px)}
.logos{display:flex;gap:2.5rem;justify-content:center;flex-wrap:wrap;color:var(--muted);font-weight:800;font-size:1.2rem;opacity:.7}.feat{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}.feat .i{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:color-mix(in srgb,var(--brand) 16%,transparent);margin-bottom:.8rem;font-size:1.3rem}.feat h3{margin-bottom:.3rem}
.sw{display:flex;justify-content:center;gap:.5rem;margin:1rem 0 2rem}.sw button{padding:.5rem 1.1rem;border-radius:99px;border:1.5px solid color-mix(in srgb,var(--text) 20%,transparent);background:none;color:var(--text);font:inherit;cursor:pointer}.sw button.on{background:var(--brand);border-color:var(--brand);color:var(--on)}.plans{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:1rem}.pl{text-align:center;border:1.5px solid transparent}.pl.pop{border-color:var(--brand);box-shadow:0 14px 40px color-mix(in srgb,var(--brand) 25%,transparent)}.pl .v{font-size:2.4rem;font-weight:800;margin:.4rem 0}.pl ul{list-style:none;padding:0;margin:1rem 0;display:grid;gap:.4rem;color:var(--muted)}
details{background:var(--surface);border-radius:var(--radius);padding:1rem 1.2rem;margin-bottom:.6rem}summary{font-weight:700;cursor:pointer}details p{margin-top:.6rem}.cta{text-align:center;padding:3rem 1rem;border-radius:var(--radius);background:linear-gradient(120deg,var(--brand),var(--brand2));color:var(--on)}.cta .btn{background:var(--on);color:var(--brand);margin-top:1rem}footer{padding:2rem 0;text-align:center;color:var(--muted);font-size:.9rem}@media(max-width:640px){nav a:not(.btn){display:none}.mock .cols{grid-template-columns:1fr}}`,
    body: `<header><div class="wrap top"><a class="logo" href="#">◆ Fluxo</a><nav><a href="#recursos">Recursos</a><a href="#precos">Preços</a><a href="#faq">FAQ</a><a class="btn" href="#precos">Começar</a></nav></div></header>
<main>
<section class="hero"><div class="wrap"><span class="pill">✨ Novo: relatórios com IA</span><h1>Gerencie seu time sem complicação</h1><p class="muted">Projetos, tarefas e métricas em um só lugar. Comece em minutos, sem cartão de crédito.</p><div class="row"><a class="btn" href="#precos">Teste grátis por 14 dias</a><a class="btn ghost" href="#recursos">Ver recursos</a></div>
<div class="mock"><div class="bar"><i></i><i></i><i></i></div><div class="cols"><div class="k"><span class="muted">Receita</span><b>R$ 48,2k</b></div><div class="k"><span class="muted">Usuários</span><b>12.480</b></div><div class="k"><span class="muted">Conversão</span><b>4,8%</b></div></div><div class="chart"></div></div></div></section>
<section style="padding:1.5rem 0"><div class="wrap logos"><span>ACME</span><span>Globex</span><span>Initech</span><span>Umbrella</span><span>Stark</span></div></section>
<section id="recursos"><div class="wrap"><h2 style="text-align:center;margin-bottom:2rem">Tudo o que sua equipe precisa</h2><div class="feat"><div class="card"><div class="i">⚡</div><h3>Automação</h3><p class="muted">Elimine tarefas repetitivas com regras simples.</p></div><div class="card"><div class="i">📊</div><h3>Relatórios</h3><p class="muted">Painéis claros, atualizados em tempo real.</p></div><div class="card"><div class="i">🔗</div><h3>Integrações</h3><p class="muted">Conecte com mais de 50 ferramentas.</p></div></div></div></section>
<section id="precos" style="padding-top:0"><div class="wrap"><h2 style="text-align:center">Planos simples</h2><div class="sw"><button class="on" data-m="m">Mensal</button><button data-m="a">Anual · -20%</button></div><div class="plans">
<div class="card pl"><b>Starter</b><div class="v" data-m="0" data-a="0">R$ 0</div><ul><li>Até 3 projetos</li><li>1 usuário</li></ul><a class="btn ghost" href="#">Começar</a></div>
<div class="card pl pop"><b>Pro ⭐</b><div class="v" data-m="49" data-a="39">R$ 49</div><ul><li>Projetos ilimitados</li><li>10 usuários</li><li>Relatórios com IA</li></ul><a class="btn" href="#">Assinar</a></div>
<div class="card pl"><b>Equipe</b><div class="v" data-m="129" data-a="103">R$ 129</div><ul><li>Tudo do Pro</li><li>Usuários ilimitados</li><li>Suporte prioritário</li></ul><a class="btn ghost" href="#">Falar com vendas</a></div></div></div></section>
<section id="faq" style="padding-top:0"><div class="wrap" style="max-width:720px"><h2 style="margin-bottom:1.2rem">Perguntas frequentes</h2><details open><summary>Preciso de cartão para testar?</summary><p class="muted">Não. O teste de 14 dias é totalmente gratuito.</p></details><details><summary>Posso cancelar quando quiser?</summary><p class="muted">Sim, sem multa e sem burocracia.</p></details><details><summary>Meus dados estão seguros?</summary><p class="muted">Usamos criptografia e backups diários.</p></details></div></section>
<section style="padding-top:0"><div class="wrap"><div class="cta"><h2>Pronto para ganhar tempo?</h2><p style="opacity:.9">Junte-se a mais de 12 mil equipes.</p><a class="btn" href="#">Criar conta grátis</a></div></div></section></main>
<footer><div class="wrap">© 2026 Fluxo. Todos os direitos reservados.</div></footer>`,
    js: `document.querySelectorAll('.sw button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sw button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.pl .v').forEach(v=>v.textContent='R$ '+v.dataset[b.dataset.m==='a'?'a':'m'])})`,
  }),

  /* ============================== RESTAURANTE ============================== */
  T({
    slug: "restaurante", title: "Restaurante / cardápio", category: "Negócios locais",
    description: "Hero acolhedor, cardápio em duas colunas com preços, destaques do chef, horários e reserva.",
    tags: ["restaurante", "cardápio", "reserva", "negócio local"], themes: ["natureza", "vibrante", "editorial", "escuro", "claro"],
    css: `header{position:absolute;inset:0 0 auto;z-index:2;color:#fff}.top{display:flex;justify-content:space-between;align-items:center;padding:1.2rem 0}.logo{font:700 1.7rem var(--head)}nav{display:flex;gap:1.4rem}nav a{font-weight:600;opacity:.9}
.hero{position:relative;min-height:78vh;display:grid;place-items:center;text-align:center;color:#fff;background:linear-gradient(#0008,#000a),linear-gradient(135deg,var(--brand),var(--brand2));padding:6rem 1rem 3rem}.hero h1{font-size:clamp(2.4rem,7vw,4.5rem);margin:.4rem 0 1rem}.hero p{max-width:46ch;margin:0 auto 1.6rem;opacity:.9}.hero .btn{background:#fff;color:var(--brand)}
.menu{display:grid;grid-template-columns:1fr 1fr;gap:2rem 3rem}.menu h3{margin-bottom:.8rem;color:var(--brand);border-bottom:2px solid color-mix(in srgb,var(--brand) 30%,transparent);padding-bottom:.4rem}.it{display:flex;gap:.6rem;align-items:baseline;margin-bottom:.9rem}.it b{white-space:nowrap}.it i{flex:1;border-bottom:2px dotted color-mix(in srgb,var(--text) 25%,transparent);transform:translateY(-4px)}.it .p{font-weight:800;color:var(--brand)}.it small{display:block;color:var(--muted)}
.chef{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1.2rem}.chef .card{text-align:center}.chef .em{font-size:3rem;margin-bottom:.4rem}
.info{display:grid;grid-template-columns:1fr 1fr;gap:2rem;align-items:start}table{width:100%;border-collapse:collapse}td{padding:.5rem 0;border-bottom:1px solid color-mix(in srgb,var(--text) 12%,transparent)}td:last-child{text-align:right;font-weight:700}form{display:grid;gap:.7rem}input,select{padding:.75rem;border-radius:var(--radius);border:1.5px solid color-mix(in srgb,var(--text) 18%,transparent);background:var(--surface);color:var(--text);font:inherit}footer{padding:2rem 0;text-align:center;color:var(--muted)}@media(max-width:700px){.menu,.info{grid-template-columns:1fr}nav{display:none}}`,
    body: `<header><div class="wrap top"><a class="logo" href="#">Sabor &amp; Brasa</a><nav><a href="#cardapio">Cardápio</a><a href="#chef">Chef</a><a href="#reserva">Reservas</a></nav></div></header>
<div class="hero"><div><span style="letter-spacing:.2em;font-size:.85rem">COZINHA AUTORAL · DESDE 2012</span><h1>Sabores que contam histórias</h1><p>Ingredientes frescos da região, fogo de lenha e atendimento de casa.</p><a class="btn" href="#reserva">Reservar mesa</a></div></div>
<main>
<section id="cardapio"><div class="wrap"><h2 style="text-align:center;margin-bottom:2rem">Nosso cardápio</h2><div class="menu">
<div><h3>Entradas</h3><div class="it"><b>Bruschetta da casa</b><i></i><span class="p">R$ 28</span></div><div class="it"><b>Carpaccio de carne<small>Parmesão e rúcula</small></b><i></i><span class="p">R$ 42</span></div><div class="it"><b>Camarão ao alho</b><i></i><span class="p">R$ 54</span></div></div>
<div><h3>Pratos principais</h3><div class="it"><b>Risoto de cogumelos</b><i></i><span class="p">R$ 68</span></div><div class="it"><b>Picanha na brasa<small>Acompanha farofa e vinagrete</small></b><i></i><span class="p">R$ 96</span></div><div class="it"><b>Moqueca de peixe</b><i></i><span class="p">R$ 82</span></div></div>
<div><h3>Sobremesas</h3><div class="it"><b>Petit gâteau</b><i></i><span class="p">R$ 34</span></div><div class="it"><b>Pudim da vovó</b><i></i><span class="p">R$ 22</span></div></div>
<div><h3>Bebidas</h3><div class="it"><b>Suco natural</b><i></i><span class="p">R$ 14</span></div><div class="it"><b>Caipirinha</b><i></i><span class="p">R$ 26</span></div></div></div></div></section>
<section id="chef" style="padding-top:0"><div class="wrap"><h2 style="text-align:center;margin-bottom:1.5rem">Sugestões do chef</h2><div class="chef"><div class="card"><div class="em">🥩</div><h3>Picanha na brasa</h3><p class="muted">Assada devagar na lenha.</p></div><div class="card"><div class="em">🍤</div><h3>Camarão ao alho</h3><p class="muted">Frescos, direto do litoral.</p></div><div class="card"><div class="em">🍮</div><h3>Pudim da vovó</h3><p class="muted">Receita de família.</p></div></div></div></section>
<section id="reserva" style="padding-top:0"><div class="wrap info"><div><h2 style="margin-bottom:1rem">Horários</h2><table><tr><td>Terça a quinta</td><td>12h–15h · 19h–23h</td></tr><tr><td>Sexta e sábado</td><td>12h–00h</td></tr><tr><td>Domingo</td><td>12h–17h</td></tr></table><p class="muted" style="margin-top:1rem">📍 Rua das Palmeiras, 120 · Centro</p></div>
<div class="card"><h2 style="margin-bottom:1rem">Reservar mesa</h2><form onsubmit="return false"><input placeholder="Nome"><input type="tel" placeholder="Telefone"><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem"><input type="date"><select><option>2 pessoas</option><option>4 pessoas</option><option>6 pessoas</option></select></div><button class="btn">Confirmar reserva</button></form></div></div></section></main>
<footer>© 2026 Sabor &amp; Brasa</footer>`,
  }),

  /* ============================== AGÊNCIA ============================== */
  T({
    slug: "agencia-criativa", title: "Agência criativa / estúdio", category: "Portfólio",
    description: "Tipografia gigante, serviços numerados, portfólio em mosaico com hover e contato.",
    tags: ["agência", "portfólio", "tipografia", "criativo"], themes: ["minimal", "neon", "vibrante", "editorial", "escuro"],
    css: `header{position:sticky;top:0;z-index:5;background:var(--bg)}.top{display:flex;justify-content:space-between;align-items:center;padding:1.1rem 0}.logo{font:800 1.3rem var(--head);letter-spacing:-.03em}nav{display:flex;gap:1.6rem;font-weight:600}nav a:hover{color:var(--brand)}
.hero h1{font-size:clamp(2.8rem,11vw,8rem);letter-spacing:-.04em;line-height:.95;text-transform:uppercase}.hero h1 span{color:var(--brand)}.hero p{max-width:48ch;margin-top:1.5rem;font-size:1.15rem}
.srv{border-top:1px solid color-mix(in srgb,var(--text) 18%,transparent)}.srv div{display:grid;grid-template-columns:70px 1fr auto;gap:1rem;align-items:center;padding:1.4rem 0;border-bottom:1px solid color-mix(in srgb,var(--text) 18%,transparent);transition:padding .25s,color .25s}.srv div:hover{padding-left:1rem;color:var(--brand)}.srv span{color:var(--muted);font-weight:700}.srv h3{font-size:clamp(1.3rem,3vw,2rem)}
.work{display:grid;grid-template-columns:repeat(6,1fr);gap:1rem}.w{position:relative;overflow:hidden;border-radius:var(--radius);min-height:220px;display:flex;align-items:flex-end;padding:1.2rem;color:#fff;font-weight:700;transition:transform .35s}.w:hover{transform:scale(.98)}.w::before{content:"";position:absolute;inset:0;background:linear-gradient(transparent 40%,#000a)}.w span{position:relative}.w1{grid-column:span 4;background:linear-gradient(135deg,var(--brand),var(--brand2))}.w2{grid-column:span 2;background:linear-gradient(135deg,var(--brand2),#222)}.w3{grid-column:span 2;background:linear-gradient(135deg,#222,var(--brand))}.w4{grid-column:span 4;background:linear-gradient(135deg,var(--brand2),var(--brand))}
.contact{text-align:center}.contact a.big{font-size:clamp(1.6rem,6vw,4rem);font-weight:800;letter-spacing:-.03em;border-bottom:3px solid var(--brand)}.contact a.big:hover{color:var(--brand)}footer{padding:2rem 0;color:var(--muted);display:flex;justify-content:space-between;flex-wrap:wrap;gap:1rem}@media(max-width:640px){.work{grid-template-columns:1fr}.w1,.w2,.w3,.w4{grid-column:auto}nav{display:none}}`,
    body: `<header><div class="wrap top"><a class="logo" href="#">estúdio.</a><nav><a href="#servicos">Serviços</a><a href="#trabalhos">Trabalhos</a><a href="#contato">Contato</a></nav></div></header>
<main>
<section class="hero"><div class="wrap"><h1>Ideias que <span>movem</span> marcas</h1><p class="muted">Estúdio de design e tecnologia. Criamos identidades, sites e produtos digitais que as pessoas lembram.</p></div></section>
<section id="servicos" style="padding-top:0"><div class="wrap"><div class="srv"><div><span>01</span><h3>Identidade visual</h3><span>→</span></div><div><span>02</span><h3>Design de interfaces</h3><span>→</span></div><div><span>03</span><h3>Sites e e-commerce</h3><span>→</span></div><div><span>04</span><h3>Estratégia de conteúdo</h3><span>→</span></div></div></div></section>
<section id="trabalhos" style="padding-top:0"><div class="wrap"><h2 style="margin-bottom:1.2rem">Trabalhos selecionados</h2><div class="work"><a class="w w1" href="#"><span>Banco Aurora — Rebranding</span></a><a class="w w2" href="#"><span>Café Origem — Site</span></a><a class="w w3" href="#"><span>Fit+ — App</span></a><a class="w w4" href="#"><span>Galeria Norte — Identidade</span></a></div></div></section>
<section id="contato" class="contact"><div class="wrap"><p class="muted">Tem um projeto em mente?</p><a class="big" href="mailto:oi@estudio.com">oi@estudio.com</a></div></section></main>
<footer class="wrap"><span>© 2026 estúdio.</span><span>Instagram · LinkedIn · Behance</span></footer>`,
  }),

  /* ============================== LINK NA BIO ============================== */
  T({
    slug: "link-na-bio", title: "Link na bio (cartão de links)", category: "Pessoal",
    description: "Página mobile-first com avatar, bio, botões de links e ícones sociais. Ótima para Instagram e TikTok.",
    tags: ["link na bio", "redes sociais", "mobile", "criador"], themes: ["pastel", "escuro", "neon", "vibrante", "minimal", "natureza"],
    css: `body{min-height:100dvh;display:grid;place-items:start center;padding:2rem 1rem;background:radial-gradient(70% 50% at 50% 0,color-mix(in srgb,var(--brand) 25%,transparent),transparent),var(--bg)}.c{width:min(100%,440px);text-align:center}.av{width:96px;height:96px;border-radius:50%;margin:0 auto 1rem;border:4px solid var(--surface);background:linear-gradient(135deg,var(--brand),var(--brand2));display:grid;place-items:center;font-size:2.4rem;box-shadow:0 10px 30px color-mix(in srgb,var(--brand) 35%,transparent)}h1{font-size:1.5rem}.bio{color:var(--muted);margin:.4rem 0 1.4rem}.links{display:grid;gap:.8rem}.l{display:flex;align-items:center;gap:.9rem;padding:1rem 1.2rem;background:var(--surface);border-radius:var(--radius);font-weight:700;box-shadow:0 2px 10px #0001;transition:transform .2s,box-shadow .2s}.l:hover{transform:translateY(-3px) scale(1.01);box-shadow:0 12px 26px #0002}.l .i{width:38px;height:38px;border-radius:calc(var(--radius)/1.6);display:grid;place-items:center;background:color-mix(in srgb,var(--brand) 18%,transparent)}.l span:last-child{margin-left:auto;color:var(--muted)}.l.main{background:var(--brand);color:var(--on)}.l.main .i{background:#fff3}.soc{display:flex;gap:.7rem;justify-content:center;margin-top:1.6rem}.soc a{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:var(--surface);font-weight:800}.soc a:hover{background:var(--brand);color:var(--on)}small{display:block;margin-top:1.6rem;color:var(--muted)}`,
    body: `<main class="c"><div class="av">🧑‍💻</div><h1>@pedro.dev</h1><p class="bio">Desenvolvedor web · Compartilho dicas de HTML, CSS e JavaScript todo dia ✨</p>
<div class="links"><a class="l main" href="#"><span class="i">🚀</span><span>Meu curso de CSS</span><span>→</span></a><a class="l" href="#"><span class="i">📘</span><span>E-book gratuito</span><span>→</span></a><a class="l" href="#"><span class="i">🛠️</span><span>Ferramentas que eu uso</span><span>→</span></a><a class="l" href="#"><span class="i">💬</span><span>Chamar no WhatsApp</span><span>→</span></a></div>
<div class="soc"><a href="#" aria-label="Instagram">IG</a><a href="#" aria-label="YouTube">YT</a><a href="#" aria-label="GitHub">GH</a><a href="#" aria-label="LinkedIn">in</a></div><small>© 2026 · feito com HTML e CSS</small></main>`,
  }),

  /* ============================== DOCUMENTAÇÃO ============================== */
  T({
    slug: "documentacao", title: "Documentação técnica", category: "Conteúdo",
    description: "Barra superior com busca, menu lateral, conteúdo com blocos de código e índice da página à direita.",
    tags: ["docs", "documentação", "sidebar", "código"], themes: ["claro", "escuro", "neon", "minimal"],
    css: `header{position:sticky;top:0;z-index:5;background:color-mix(in srgb,var(--bg) 88%,transparent);backdrop-filter:blur(10px);border-bottom:1px solid color-mix(in srgb,var(--text) 12%,transparent)}.top{display:flex;align-items:center;gap:1rem;padding:.8rem 1.2rem}.logo{font:800 1.1rem var(--head)}.top input{flex:1;max-width:340px;padding:.5rem .9rem;border-radius:var(--radius);border:1px solid color-mix(in srgb,var(--text) 15%,transparent);background:var(--surface);color:var(--text);font:inherit}.top .v{margin-left:auto;color:var(--muted);font-size:.85rem}
.l{display:grid;grid-template-columns:230px minmax(0,1fr) 190px;gap:2rem;max-width:1280px;margin:auto;padding:0 1.2rem}aside{position:sticky;top:60px;align-self:start;max-height:calc(100dvh - 60px);overflow:auto;padding:1.5rem 0;font-size:.92rem}aside h4{font-size:.75rem;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);margin:1.2rem 0 .4rem}aside a{display:block;padding:.3rem .6rem;border-radius:8px;color:var(--muted)}aside a:hover{color:var(--text)}aside a.on{background:color-mix(in srgb,var(--brand) 15%,transparent);color:var(--brand);font-weight:700}
article{padding:2rem 0;min-width:0}article h1{font-size:2.2rem;margin-bottom:.5rem}article h2{margin:2rem 0 .6rem;font-size:1.4rem}article p{margin-bottom:1rem}pre{background:var(--surface);border:1px solid color-mix(in srgb,var(--text) 12%,transparent);border-radius:var(--radius);padding:1rem;overflow-x:auto;font:.88rem/1.6 ui-monospace,Menlo,monospace;margin-bottom:1rem}code{font-family:ui-monospace,Menlo,monospace;background:var(--surface);padding:.1rem .4rem;border-radius:5px;font-size:.88em}pre code{padding:0;background:none}.note{border-left:4px solid var(--brand);background:color-mix(in srgb,var(--brand) 10%,transparent);padding:.8rem 1rem;border-radius:0 var(--radius) var(--radius) 0;margin-bottom:1rem}
.toc{position:sticky;top:60px;align-self:start;padding:2rem 0;font-size:.85rem}.toc b{display:block;margin-bottom:.5rem}.toc a{display:block;color:var(--muted);padding:.2rem 0;border-left:2px solid transparent;padding-left:.7rem}.toc a:hover{color:var(--brand);border-color:var(--brand)}.pn{display:flex;justify-content:space-between;gap:1rem;margin-top:2.5rem}.pn a{flex:1;padding:1rem;border:1px solid color-mix(in srgb,var(--text) 15%,transparent);border-radius:var(--radius)}.pn a:last-child{text-align:right}.pn small{color:var(--muted);display:block}@media(max-width:1000px){.l{grid-template-columns:200px 1fr}.toc{display:none}}@media(max-width:640px){.l{grid-template-columns:1fr}aside{display:none}}`,
    body: `<header><div class="top"><a class="logo" href="#">📘 MeuPacote</a><input type="search" placeholder="Buscar na documentação…" aria-label="Buscar"><span class="v">v2.4.0</span></div></header>
<div class="l"><aside><h4>Começando</h4><a class="on" href="#">Instalação</a><a href="#">Primeiros passos</a><a href="#">Configuração</a><h4>Guias</h4><a href="#">Componentes</a><a href="#">Temas</a><a href="#">Acessibilidade</a><h4>Referência</h4><a href="#">API</a><a href="#">CLI</a><a href="#">Changelog</a></aside>
<article><span class="tag">Começando</span><h1>Instalação</h1><p class="muted">Em poucos minutos você terá o MeuPacote funcionando no seu projeto.</p>
<h2 id="requisitos">Requisitos</h2><p>Node.js 18 ou superior e um gerenciador de pacotes (<code>npm</code>, <code>pnpm</code> ou <code>yarn</code>).</p>
<h2 id="instalar">Instalar</h2><pre><code>npm install meupacote
# ou
pnpm add meupacote</code></pre>
<h2 id="usar">Uso básico</h2><pre><code>import { criar } from "meupacote";

const app = criar({ tema: "escuro" });
app.iniciar();</code></pre><div class="note"><b>Dica:</b> use a opção <code>tema</code> para trocar o visual de todo o projeto.</div>
<div class="pn"><a href="#"><small>← Anterior</small>Introdução</a><a href="#"><small>Próximo →</small>Primeiros passos</a></div></article>
<nav class="toc" aria-label="Nesta página"><b>Nesta página</b><a href="#requisitos">Requisitos</a><a href="#instalar">Instalar</a><a href="#usar">Uso básico</a></nav></div>`,
  }),

  /* ============================== EVENTO ============================== */
  T({
    slug: "evento-conferencia", title: "Evento / conferência", category: "Negócios locais",
    description: "Contagem regressiva, palestrantes, programação por horário e ingressos com lotes.",
    tags: ["evento", "conferência", "ingressos", "programação"], themes: ["neon", "vibrante", "claro", "escuro", "pastel"],
    css: `header{position:sticky;top:0;z-index:5;background:color-mix(in srgb,var(--bg) 85%,transparent);backdrop-filter:blur(10px)}.top{display:flex;justify-content:space-between;align-items:center;padding:.9rem 0}.logo{font:800 1.2rem var(--head)}
.hero{text-align:center;padding-top:clamp(3rem,8vw,6rem)}.hero .date{display:inline-block;padding:.35rem 1rem;border-radius:99px;border:1px solid var(--brand);color:var(--brand);font-weight:700;margin-bottom:1rem}.hero h1{font-size:clamp(2.4rem,8vw,5.5rem);letter-spacing:-.03em}.hero h1 span{background:linear-gradient(90deg,var(--brand),var(--brand2));-webkit-background-clip:text;background-clip:text;color:transparent}.hero p{max-width:50ch;margin:1rem auto 1.6rem}
.cd{display:flex;gap:.8rem;justify-content:center;margin:2rem 0}.cd div{min-width:78px;padding:.9rem .6rem;border-radius:var(--radius);background:var(--surface)}.cd b{display:block;font-size:2rem;font-variant-numeric:tabular-nums}.cd small{color:var(--muted)}
.spk{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem}.spk .card{text-align:center}.av{width:84px;height:84px;border-radius:50%;margin:0 auto .8rem;background:linear-gradient(135deg,var(--brand),var(--brand2))}.spk small{color:var(--muted)}
.ag{max-width:760px;margin:auto}.ag .r{display:grid;grid-template-columns:90px 1fr;gap:1rem;padding:1rem 0;border-bottom:1px solid color-mix(in srgb,var(--text) 12%,transparent)}.ag time{font-weight:800;color:var(--brand)}.ag p{color:var(--muted);font-size:.92rem}
.tk{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:1rem}.tk .card{text-align:center;border:1.5px solid transparent}.tk .pop{border-color:var(--brand)}.tk .v{font-size:2.2rem;font-weight:800;margin:.4rem 0 1rem}.tk small{color:var(--muted)}footer{padding:2rem 0;text-align:center;color:var(--muted)}@media(max-width:520px){.cd div{min-width:64px}.ag .r{grid-template-columns:1fr;gap:.2rem}}`,
    body: `<header><div class="wrap top"><a class="logo" href="#">DevConf<span style="color:var(--brand)">.26</span></a><a class="btn" href="#ingressos">Garantir ingresso</a></div></header>
<main>
<section class="hero"><div class="wrap"><span class="date">📅 14–15 de novembro · Natal, RN</span><h1>A maior conferência de <span>tecnologia</span> do Nordeste</h1><p class="muted">Dois dias de palestras, workshops e networking com quem está construindo o futuro da web.</p>
<div class="cd" aria-label="Contagem regressiva"><div><b id="d">00</b><small>dias</small></div><div><b id="h">00</b><small>horas</small></div><div><b id="m">00</b><small>min</small></div><div><b id="s">00</b><small>seg</small></div></div><a class="btn" href="#ingressos">Quero participar</a></div></section>
<section><div class="wrap"><h2 style="text-align:center;margin-bottom:1.5rem">Palestrantes</h2><div class="spk"><div class="card"><div class="av"></div><b>Marina Costa</b><br><small>Design Systems · Acme</small></div><div class="card"><div class="av" style="filter:hue-rotate(80deg)"></div><b>Carlos Lima</b><br><small>Engenharia · Globex</small></div><div class="card"><div class="av" style="filter:hue-rotate(160deg)"></div><b>Ana Souza</b><br><small>IA aplicada · Initech</small></div><div class="card"><div class="av" style="filter:hue-rotate(240deg)"></div><b>Rafael Dias</b><br><small>Segurança · Umbrella</small></div></div></div></section>
<section style="padding-top:0"><div class="wrap"><h2 style="text-align:center;margin-bottom:1rem">Programação</h2><div class="ag"><div class="r"><time>09:00</time><div><b>Abertura</b><p>Boas-vindas e visão geral do evento.</p></div></div><div class="r"><time>10:00</time><div><b>O futuro do CSS</b><p>Marina Costa · Palco principal</p></div></div><div class="r"><time>13:30</time><div><b>Workshop: React na prática</b><p>Carlos Lima · Sala 2</p></div></div><div class="r"><time>16:00</time><div><b>IA no dia a dia do dev</b><p>Ana Souza · Palco principal</p></div></div></div></div></section>
<section id="ingressos" style="padding-top:0"><div class="wrap"><h2 style="text-align:center;margin-bottom:1.5rem">Ingressos</h2><div class="tk"><div class="card"><b>1º lote</b><div class="v">R$ 99</div><small>Acesso aos dois dias</small><br><br><a class="btn ghost" href="#">Comprar</a></div><div class="card pop"><b>Combo ⭐</b><div class="v">R$ 179</div><small>Dois dias + workshops + certificado</small><br><br><a class="btn" href="#">Comprar</a></div><div class="card"><b>Estudante</b><div class="v">R$ 49</div><small>Com comprovante</small><br><br><a class="btn ghost" href="#">Comprar</a></div></div></div></section></main>
<footer>© 2026 DevConf · Natal, RN</footer>`,
    js: `const alvo=new Date(Date.now()+1000*60*60*24*45);const z=n=>String(n).padStart(2,'0');function t(){const r=Math.max(0,alvo-Date.now());d.textContent=z(Math.floor(r/864e5));h.textContent=z(Math.floor(r/36e5)%24);m.textContent=z(Math.floor(r/6e4)%60);s.textContent=z(Math.floor(r/1e3)%60)}t();setInterval(t,1000)`,
  }),
];
